### ISSUE TITLE
Simplified EC2 setup

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes-anywhere#111]
### Phase 1

Master:
- single instance
- runs etcd
- has an EIP

Nodes:
- TBC
### Phase 2
- easy to obtain kubeconfig file for local use
- use EIP in PKI image creation (or consider approach which #112 would enable)

**Comment by errordeveloper** [comment]
@mikedanese I have some WIP, but let's discuss first.

**Comment by errordeveloper** [comment]
Also, I'm not intending to go full-on with jsonnet right now, as I mostly find sensible ways around getting things done in HCL... However, I am thinking that it'd make a lot of sense to use jsonnet for remapping cluster config object into Terraform module instantiation.

**Comment by mikedanese** [comment]
Is this #115 now?

**Comment by errordeveloper** [comment]
It's a combination of #114 and #115, but both are WIP, so degrees of separation are to be discussed.
