### ISSUE TITLE
Move container images from weaveworks org

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes-anywhere#113]
Can probably use GCR.

It may be also a good idea to turn the current naming scheme

```
<org>/kubernetes-anywhere:<component>-<version>
```

into

```
kubernetes-anywhere/<component>:<version>
```

or even

```
k8s-anywhere/<component>:<version>
```

**Comment by mikedanese** [comment]
gcr.io/kubernetes works. More generally, we need to figure out a release process for v1.4. cc @david-mcmahon who has been nailing this down for kubernetes proper.
