### ISSUE TITLE
lookup kube-apiserver.weave.local: no such host

### ISSUE THREAD

**Issue by netroby** [kubernetes/kubernetes-anywhere#118]
kubectl get nodes
Unable to connect to the server: dial tcp: lookup kube-apiserver.weave.local: no such host

But dns work fine

⋊> ~ weave status dns                                                                                         09:30:15
etcd1        10.32.0.3       6aab145bc811 e2:58:9c:6a:47:cf
kube-apiserver 10.32.0.4       157f559b2ee1 e2:58:9c:6a:47:cf
kube-controller-manager 10.32.0.5       1bd0668ae2a1 e2:58:9c:6a:47:cf
kube-scheduler 10.32.0.6       8c5ba92c9736 e2:58:9c:6a:47:cf

**Comment by errordeveloper** [comment]
Are you using Docker on Linux directly?
