### ISSUE TITLE
guestbook-example can not execute due to gcr.io was blocked by firewall

### ISSUE THREAD

**Issue by netroby** [kubernetes/kubernetes-anywhere#119]
guestbook-example can not execute due to gcr.io was blocked by firewall
we can not reach gcr.io. so we can not success create image from gcr.io images

```
 7m     3m      2   {kubelet w}             Warning     FailedSync  Error syncing pod, skipping: failed to "StartContainer" for "POD" with ErrImagePull: "image pull failed for gcr.io/google_containers/pause:2.0, this may be because there are no credentials on this request.  details: (API error (500): Get https://gcr.io/v1/_ping: dial tcp 173.194.72.82:443: i/o timeout\n)"
```

**Comment by netroby** [comment]
https://github.com/kubernetes/kubernetes/issues/6888
	
	start the kubelet like below will solve the issue that when you cannot connect to google, but can connect to docker.io:
kubelet --pod-infra-container-image="docker.io/kubernetes/pause"

**Comment by errordeveloper** [comment]
Oh, isn't this just general K8s issue?

**Comment by netroby** [comment]
Yes. it was general k8s issue, but the solution i can not get into kubernetes-anywhere. i did not know how to apply this fix with kubernetes anywhere

**Comment by liuzhishan** [comment]
@netroby 
`kubelet --pod-infra-container-image="docker.io/kubernetes/pause"`
What is kubelet? When I run this, I get this error
`kubelet: command not found`
