### ISSUE TITLE
Add /usr/bin/kubecmd for getting kubectl console quick

### ISSUE THREAD

**Issue by netroby** [kubernetes/kubernetes-anywhere#121]
```
#!/bin/sh
eval $(weave env)
docker run --rm -ti --volumes-from=kube-toolbox-pki weaveworks/kubernetes-anywhere:toolbox
```

Here is my quick /usr/bin/kubecmd shell scripts. to let me quick get into the toolbox.
can we add a tips to document?

If we want to run kubectl, we can just type kubecmd , then we will get into the toolbox shell

**Comment by errordeveloper** [comment]
Yes, that's pretty handy, although you can use `kubectl` as well, just like shown here:

https://github.com/kubernetes/kubernetes-anywhere/blob/master/DOCKER_FOR_MAC.md

**Comment by netroby** [comment]
hum, I am using example to deploy kubernetes inside docker container. so it's hard for me to configure kubectl right. so the easy way will be using your prepared toolbox docker image. that's the easy way to do it . and i have not macos. i am using linux . i have docker. and i have not much more experience on kubernetes

**Comment by errordeveloper** [comment]
Ok, sure, that's why I created the toolbox in the first place ;)

The things are a bit in flux at the very moment, but let's keep this open and update the docs once we have a steady base.
