### ISSUE TITLE
What the basic contract between phases should be

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes-anywhere#133]
I think we need do define the contract between phases a bit better, and hopefully avoid bikeshedding  exact attributes names and object format.

More specifically, I am talking about things like "what info phase 1 is expected to pass to phase2?" vs "phase 2 is expected to do some basic auto-detection of certain artefacts of phase 1".

It's important to node that in some cases phase 1 doesn't have the info you'd expect it to have in theory, e.g. IPs of all nodes (at least in EC2 it's complicated). And passing some information makes phase 1 a bit more complicated, e.g. passing master IP to nodes introduces a dependency, where phase 1 has to do more synchronisation.

**Comment by bgrant0607** [comment]
We can keep numbers in order to convey ordering, but please add names to the phases, like "provision".

**Comment by errordeveloper** [comment]
I've had a few thoughts on this, one option would be to refer to those as `p1-provision` & `p2-bootstrap`, and use `p1` & `p2` as short names.
