### ISSUE TITLE
Docker version pinning strategy

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes-anywhere#137]
We are currently using 1.11, but the versions aren't pinned and we will get 1.12 as soon as it's out.

**Comment by errordeveloper** [comment]
I think it may be a good idea to stick with 1.11 for the time being, where possible. For example #136 is inevitable, as Docker for Mac is the bleeding edge.

**Comment by mikedanese** [comment]
Is this part of phase1? can we mandate that phase 1 providers bring a node with docker already enabled, then give them guidelines on which version they should be running?

**Comment by mikedanese** [comment]
For debian: http://apt.dockerproject.org/repo/pool/main/d/docker-engine/

**Comment by mikedanese** [comment]
https://github.com/kubernetes/kube-deploy/pull/34 is another possible solution for this (if we can get it to work)
