### ISSUE TITLE
On Docker For Mac does not handle suspend/resume well

### ISSUE THREAD

**Issue by the-destro** [kubernetes/kubernetes-anywhere#138]

**Comment by errordeveloper** [comment]
Yes, there are a few issue that hadn't been determined just yet. Also, right now #136 causes a much bigger problem. It would be great to identify what exactly is the issue, I think it's basically the case of pods not coming back, as the Docker for Mac VM effectively reboots on resume, however until recently Docker for Mac ate 200% of CPU and required app restart.
