### ISSUE TITLE
User should be able to run terraform apply from any directory

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes-anywhere#139]
Right now gce.tf assumes that it is being invoked from phase1/gce as `terraform apply .tmp` and it hard codes the paths to different files. For example, `san-extras` is assumed to be at `../../phase1b/crypto/san-extras` and hence `terraform apply` doesn't work if we invoke it from any other directory than phase1/gce. 

Users should have the flexibility to run terraform apply from where ever they want.

cc @mikedanese

**Comment by errordeveloper** [comment]
Good point, @madhusudancs. Do you think the user should be able to check-in the generate code and terraform state into a repo and potentially use on a different machine later? I'm just wondering if the answer to this would be simply about absolute path, or something else? If we were to use modules, [`${path.module}` is a thing](https://www.terraform.io/docs/modules/create.html).

**Comment by madhusudancs** [comment]
My intention when filing this issue was just about the absolute path. I am not sure about checking in the generated code and the state files.
