### ISSUE TITLE
terraform destroy .tmp for phase1/gce fails due to routes

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes-anywhere#141]
`routecontroller` installs GCE routes to route cluster traffic to appropriate pods on the cluster nodes. Since these routes aren't being managed by terraform, `terraform destroy` fails on the same cluster it setup with the following error message:

```
Error applying plan:

1 error(s) occurred:

* google_compute_network.network: The network resource 'networkname' is already being used by 'k-1-14679864-381e-11e6-b088-42010a800002'


Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

This isn't the expected behavior. I should be able to destroy the cluster I setup using terraform.

cc @mikedanese

**Comment by mikedanese** [comment]
Terraform is fairly inflexible in this way. It doesn't really have a concept of adopting resources. I think not using GCE networking and instead using e.g. weave is probably the way to go here in the short term. We will have the same problem with load balancers and firewall rules that the cloud-provider creates as well.

**Comment by madhusudancs** [comment]
I see. Does it make sense to implement Kubernetes as a provider plugin? Providers at least provide a way to destroy resources, right?

Alternatively, we could wrap terraform with make destroy that would delete enough resources to let terraform do its job. But at that point we are losing the benefits of declarative infrastructure specification.

**Comment by mikedanese** [comment]
I think that the next terraform release may help with this but I have not tested.

https://github.com/hashicorp/terraform/issues/581#issuecomment-225256493

**Comment by mikedanese** [comment]
This looks like it will require work in the gce terraform provider but seems doable.
