### ISSUE TITLE
Rename phase folders

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes-anywhere#150]
People complain that they don't mean anything. I'm thinking we do something that if lexically sorted would produce the correct order of execution, but with more descriptive names, e.g.:

```
10_provision
20_bootstrap
30_addons
```

**Comment by errordeveloper** [comment]
Indeed.

I was going to suggest something more like:
- `p1-provision`
- `p2-bootstrap`
- `p3-addons`

In any case, I'm happy with your suggestion, @mikedanese.

**Comment by mikedanese** [comment]
Yours works if we never add intermediate steps, e.g. we had a:
```
15_provision_pki
```
I guess we probably shouldn't ever do that though.

**Comment by errordeveloper** [comment]
Yeah, it feels like in-between phases aren't a great idea...
