### ISSUE TITLE
How to get a `kubeconfig` file for connecting to the cluster?

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes-anywhere#152]
Should we have Terraform output a `kubeconfig` file for the user?

Not sure the best way to accomplish this. Maybe using `local-exec` provisioner with the `kubeconfig` jsonnet function result piped into a file.

**Comment by mikedanese** [comment]
I've been doing this. https://github.com/kubernetes/kubernetes-anywhere/blob/master/phase1/gce/gce.jsonnet#L200-L208

**Comment by colemickens** [comment]
Ah, I missed that. Will copy. Thanks.

**Comment by colemickens** [comment]
Actually, I had that but I was looking in the wrong place. Should we be putting that sort of stuff into the `./.tmp/` directory?

As of now it's a bit weird with the TF state in `./.tmp` and `kubeconfig.json` outside it.
![screen shot 2016-06-27 at 7 18 26 pm](https://cloud.githubusercontent.com/assets/327028/16401799/2b055e10-3c9c-11e6-9b27-3533b9c33ee0.png)

**Comment by mikedanese** [comment]
yes that sounds good to me.
