### ISSUE TITLE
jsonnet `kubeconfig` outputs invalid json/yaml

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes-anywhere#153]
It's currently outputting some hybrid of json/yaml which doesn't seem to be valid json. (`kubectl` is complaining when I try to pull the `/srv/kubernetes/kubeconfig.json` from my cluster to check if my bringup works).

example file: https://gist.github.com/d9e9dd1008328583d497219c5a18dd36

**Comment by colemickens** [comment]
I'm using https://github.com/google/jsonnet/commit/66ade34c7fdff820b5e5eecc555ba54fa1eccc2c (last commit as of the time of my comment).

**Comment by mikedanese** [comment]
weird.... I'll investigate. cc @sparkprime

**Comment by colemickens** [comment]
It looks correct in the terraform state file; this must have something to do with how I'm getting it onto disk in the VM. No need to investigate this from the jsonnet side.
