### ISSUE TITLE
Use of self-hosting in "phase2/ansible" vs descrete approach "phase2/docker-images"

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes-anywhere#166]
As #149 states, we should consolidate boostrap implementation.

What's in `phase2/docker-images` doesn't use self-hosting, while `phase2/ansible` relies on self-hosting.

**Comment by errordeveloper** [comment]
For the record, my reason for no using self-hosting in `phase2/docker-images` were the following:

- It's not as easy to make Weave DNS work with self-hosting
- I find self-hosting somewhat hard to reason about and find it much easier to run individual components in systemd units of their own
- Self-hosting still lacks clear user-facing documentation and at a distance seems like an incidental feature (rather then explicit behaviour)
- At times, I also found self-hosting to be somewhat hard to reason about

Additionally, `phase2/docker-images` provides very simple path for upgrades, where very little need to be done on the hosts. Patch releases can be rolled-out through unit restarts, and minor releases can be rolled-out by updating a single systemd environment file.

**Comment by errordeveloper** [comment]
Few more things I wanted to clarify on the above:

> - At times, I also found self-hosting to be somewhat hard to reason about
> - Self-hosting still lacks clear user-facing documentation

This effectively impacts transparency a little bit.

> - It feels much easier to run individual components in systemd units of their own

This implies that all the components are managed the same way. Self-hosting sort of implies that too, but as far as I understand, static pods are effectively read-only from the API perspective. Self-hosted kubelet seems to be a solution to some of the limitation, but it seems like non-trivial layer of indirection...

@mikedanese I have to say, I didn't user self-hosting very extensively myself, so I leave it to you to list the pros of it. Also, to be honest, Jsonnet makes self-hosting much nicer.

**Comment by errordeveloper** [comment]
I think I should expand on why
> - It's not as easy to make Weave DNS work with self-hosting

The primary reason for this is the lack of DNS plugin API in Docker, so we have to use the API proxy. The proxy sets DNS records based on either the container name or the hostname, alternatively it can use container labels also, however it's currently not possible to do either of those things on a pod infra container.

**Comment by mikedanese** [comment]
Generic self hosting motiviation: Kubernetes components are just applications. They have much the same needs as any other application. Kubernetes needs a solution for  packaging/image-building, configuration, deployment and upgrades, auth[nz], naming/discovery, process management, high availability, scalability and so on. We have designed a system that can generically facilitates these needs. We can therefore benefit from these capabilities by running Kubernetes on Kubernetes.

Brain dump specific to static pods for the master config:
* reduce host config (less systemd units)
  * reduces work to port phase2 to non systemd systems
* declaritive config that k8s users should be familiar with (pod spec)
* more introspectable
  * heapster can monitor resource usage
  * kubectl logs/exec works
* straightforward path to actual self hosting (running in deployments) which should be the eventual state IMO
* kubelet handles reconciliation of pod state (process managment e.g. liveness and readiness checking)

Static pods documentation here: http://kubernetes.io/docs/admin/static-pods/
Full self hosting documentation is lacking but will be added when we start using it.

How does weave DNS interact with kube-dns?

**Comment by errordeveloper** [comment]
> How does weave DNS interact with kube-dns?

At the moment it doesn't at all. It has a slightly different model, and doesn't support SRV records. I like to be able to use it instead of kube-dns, but kube-dns works and has seen some improvements lately (which I still didn't catch-up on).
