### ISSUE TITLE
CI/CD for Kubernetes-Anywhere

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes-anywhere#171]
What's the current thinking for this? The stuff in `{kubernetes}/hack/jenkins` seemed like it was fairly tied to: 
1. A full release build of Kubernetes
2. The kube-up infrastructure, even taking dependencies on certain functions being implemented in the `$KUBERNETES_PROVIDER/util.sh`.

Given that `kubernetes-anywhere` only needs the `hyperkube` container (which can be built easily by itself with `hack/dev-push-hyperkube.sh`), and given that this is meant to replace `kube-up`, I was wondering if something else should be put together.

What were others thinking?

**Comment by colemickens** [comment]
CC: @mikedanese. I'm brainstorming here rather than adding a bunch of noise to your PR (https://github.com/kubernetes/kubernetes-anywhere/pull/208)

I think we need four jobs (per phase1 provider):

* kubernetes-anywhere master + kubernetes stable
* kubernetes-anywhere PRs + kubernetes stable
* kubernetes master + kubernetes-anywhere stable
* kubernets PRs + kubernetes-anywhere stable

It seems like putting the actual job definitions in kubernetes/test-infra is best for preventing testing drift and making sure this is a proper first-party solution for deploying Kubernetes.

Is this along the lines of what you were thinking about?

For Azure... I've been down this path before and got a bit lost, but I can start taking a look at what it would take to add Azure definitions to the test-infra repo (and eventually effectively remove the Jenkinsfile I added here, though it is providing value for now)

**Comment by mikedanese** [comment]
That test matrix sounds like what we eventually want. What is the priority and bare minimum for v1.4? We need to define what kubernetes stable means. I'm going to be working more on testing today.

**Comment by colemickens** [comment]
> What is the priority and bare minimum for v1.4? 

For now I think priority is master of `kubernetes` along with master of `kubernetes-anywhere` so we make sure things don't regress for 1.4 release.

I'd like to look at testing again tomorrow, let me know where you get with it today.

**Comment by cmluciano** [comment]
/close

Opened #476 to track this effort with prow
