### ISSUE TITLE
apt-get is configured to install unauthenticated packages

### ISSUE THREAD

**Issue by obi1kenobi** [kubernetes/kubernetes-anywhere#173]
Excerpt:
```
apt-get install -y --allow-unauthenticated --force-yes  docker-engine
```

Original location:
https://github.com/kubernetes/kubernetes-anywhere/blob/901671a6eea055ef524e50b80e1409cc424ee2c8/phase1/aws-ec2-terraform/secure-v1.2-user-data.yaml#L200

I'm not sure why `--allow-unauthenticated` was originally added, but it definitely shouldn't be there -- it's a shoot-yourself-in-the-foot option from a security standpoint.

**Comment by errordeveloper** [comment]
If you look at the commit history, you will learn that this is due to docker/docker#22599, which is still unresolved.

**Comment by errordeveloper** [comment]
It looks like @codepainters got to the bottom of this (https://github.com/docker/docker/issues/22599#issuecomment-225632998), it'd be great to try fixing this by clearing the cache, as @codepainters suggests.

**Comment by obi1kenobi** [comment]
The entire `aws-ec2-terraform` folder appears to have been removed from the repo, so I'm closing this issue.
