### ISSUE TITLE
[Azure CP] Bad number of nodes / Missing Nodes

### ISSUE THREAD

**Issue by theobolo** [kubernetes/kubernetes-anywhere#177]
Hello guys,

I'm testing hardly the azure implementation within kubernetes-anywhere and found something weird.

Everytime i made a cluster the number of the nodes that provide the Terraform script is correctly within the Azure ressource group, but not inside the cluster that seeing the kubernetes master.

For exemple if i decide to deploy a cluster with 3 nodes : Standard_DS3_v2 
Kubernetes is only able to see 2 nodes... There is always one missing 

I tried with a bigger cluster 10 nodes : Standard_DS3_v2
Kubernetes was only able to use 7 nodes : kubectl get nodes gives me 7 nodes and not 10.

This is the last cluster i deployed with 3 nodes in the ressource group : 0 / 1 / 2 
```
ghosty@workstation-coursierprive:~$ ./kubectl --kubeconfig="kubernetes-anywhere/phase1/azure/.tmp/kubeconfig.json" get nodes
NAME                     STATUS                     AGE
lolilol-cluster-master   Ready,SchedulingDisabled   18m
lolilol-cluster-node-1   Ready                      11m
lolilol-cluster-node-2   Ready                      12m
``` 

Screenshot of my deployment : 

![image](https://cloud.githubusercontent.com/assets/7281773/16985853/7a8116c0-4e83-11e6-8ed3-1ae0a29f74be.png)

Another thing is that when i deploy a Service with LoadBalancer type : it's create a Backend rule only for two nodes as Kubernetes is able to see.

Any ideas :)

**Comment by theobolo** [comment]
Ok so i've investigated a little bit more : 

I deployed a cluster with 5 nodes, Kubernetes is only able to see 3 of them.

I ssh into the nodes that are not registered by kubernetes and without surprise on that nodes the kubelet docker image is not running, not even pushed.

That's strange because the docker.service is correctly started on that nodes. 

I found one strange error on the docker.service of one of the nodes corresponding to the Post to create the kubelet container  : 

```
Jul 20 12:17:49 serious-cluster-node-1 docker[3976]: time="2016-07-20T12:17:49.072185444Z" level=warning msg="Your kernel does not support swap memory limit."
Jul 20 12:17:49 serious-cluster-node-1 docker[3976]: time="2016-07-20T12:17:49.072562044Z" level=info msg="Loading containers: start."
Jul 20 12:17:49 serious-cluster-node-1 docker[3976]: time="2016-07-20T12:17:49.072606144Z" level=info msg="Loading containers: done."
Jul 20 12:17:49 serious-cluster-node-1 docker[3976]: time="2016-07-20T12:17:49.072614744Z" level=info msg="Daemon has completed initialization"
Jul 20 12:17:49 serious-cluster-node-1 docker[3976]: time="2016-07-20T12:17:49.072628144Z" level=info msg="Docker daemon" commit=b9f10c9 graphdriver=overlay version=1.11.2
Jul 20 12:17:49 serious-cluster-node-1 systemd[1]: Started Docker Application Container Engine.
Jul 20 12:17:49 serious-cluster-node-1 docker[3976]: time="2016-07-20T12:17:49.083469744Z" level=info msg="API listen on /var/run/docker.sock"
Jul 20 12:17:50 serious-cluster-node-1 systemd[1]: Started Docker Application Container Engine.
Jul 20 12:18:40 serious-cluster-node-1 docker[3976]: time="2016-07-20T12:18:40.716272365Z" level=error msg="Handler for POST /v1.23/containers/create returned error: No such image: colemickens/hyperkube-amd64:v1.4.0-alpha.1-azure"
Jul 20 12:18:55 serious-cluster-node-1 docker[3976]: time="2016-07-20T12:18:55.231185165Z" level=warning msg="Security options with `:` as a separator are deprecated and will be completely unsupported in 1.13, use `=` instead."
```

By the way the Colemickens image exists on his DockerHub repo. Maybe a probleme with the Docker Daemon ?

**Comment by mikedanese** [comment]
@colemickens

**Comment by colemickens** [comment]
@theobolo Can you please provide `/var/log/cloud-init-output.log` from a node where `kubelet` did not come up correctly?

**Comment by theobolo** [comment]
There it is : 

https://gist.github.com/theobolo/1b28f47fd95db95a0a3cd65a07c9ba24

**Comment by colemickens** [comment]
@mikedanese Have you seen anything like this before from Ansible? `fatal: [/host_root]: FAILED! => {"changed": true, "failed": true, "rc": 56, "stderr": "+ INSTALL_DIR=/opt/pypy\n+ PYPY_PATH=https://bitbucket.org/pypy/pypy/downloads/pypy-5.1.0-linux64.tar.bz2\n+ PYPY_HASH=0e8913351d043a50740b98cb89d99852b8bd6d11225a41c8abfc0baf7084cbf6\n+ [[ ! -f /opt/pypy/bin/pypy ]]\n+ install\n+ rm -rf /opt/pypy\n+ mkdir -p /opt/pypy\n+ curl -sL --fail -o /opt/pypy/pypy.tar.bz2 https://bitbucket.org/pypy/pypy/downloads/pypy-5.1.0-linux64.tar.bz2\n", "stdout": "", "stdout_lines": []}
`

I'm wondering if there's a sporadic network error and Ansible can't fetch pypy? Another +1 for something-other-than-Ansible.

@theobolo Are you deploying into a particular region? And is it safe to assume most of your attempts have been all around the same time?

**Comment by theobolo** [comment]
@colemickens I'm deploying my cluster at "Northeurope" location every time !

Sometimes when the cluster is deploying i can see a strange Subnet error but not always, by the way the node problem is always present :/

**Comment by theobolo** [comment]
Ok so i tried in different regions with different number of nodes.

But it seems that the Cloud-init process is sporadically failing and even on the Master some times that makes the cluster unusable :/

**Comment by mikedanese** [comment]
@colemickens I haven't seen that failure before, maybe we should just start using https://github.com/kubernetes/kubernetes-anywhere/pull/161 or assume the host has python installed.

**Comment by theobolo** [comment]
@colemickens @mikedanese Today is the first day without any error about the cloud-init-final process, all my nodes are available and running at the same time, 3min after the kubernetes-anywhere deployment.

**Comment by theobolo** [comment]
Since the new ignition implementation i'm closing that ;)
