### ISSUE TITLE
azure: add helper to phase1 for AAD Service Principal creation

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes-anywhere#184]
Follow the same pattern that I use in [`azkube`](https://github.com/colemickens/azkube):
1. Create the resource group using `phase1.deployment_name`
2. Create a AD App, AD SP for the App. Add a `client_secret`/`password` to the App.
3. Grant `Contributor` RBAC role to the SP, scoped to the resource group.
4. Place these creds into `config.json`.

This will get kubernetes-anywhere usability closer to azkube's, while being more standard and benefitting from the cluster mutability that terraform provides.

**Comment by theobolo** [comment]
That'd be great ! :+1:
