### ISSUE TITLE
Document GCE example

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes-anywhere#21]
Now that #5 is fulfilled for the GCE example, we can document it properly, i.e. provide instructions and not just scripts with _Obvious Naming Convention™_.

**Comment by errordeveloper** [comment]
@abuehrle would you like to try it out give [this example](https://github.com/weaveworks/weave-kubernetes-anywhere/blob/master/examples/google-compute-engine/README.md) a touch? It doesn't need to be A-Z, just a little bit more polished then what it currently is.

**Comment by abuehrle** [comment]
@errordeveloper will have a look over the next couple of days.
