### ISSUE TITLE
Choosing 'n' to a bool kconfig option results in it being omitted from the config

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes-anywhere#229]
Bools don't seem to work properly. If you choose 'n' to them, they don't wind up in `.config` properly.

This affected the PR that @theobolo hit and it also affects the addons (someone actually tried to turn one off and noticed it doesn't work).

**Comment by theobolo** [comment]
Any news about that ? I know that some guys are waiting about possibility to use Ephemeral on the Azure bring up :/

**Comment by colemickens** [comment]
Sorry @theobolo, I haven't had time to look into this. Curious if @mikedanese or @madhusudancs  has any thoughts on this one...

**Comment by theobolo** [comment]
Expected also something like that :P Mike !!!! help !! xD
