### ISSUE TITLE
Notes on etcd

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes-anywhere#23]
From speaking to @jonboulle, there are a few things that need to be documented.

Firstly, it's enough to pass only one address of a node, thereby the API server doesn't really have to care about having the `ETCD_CLUSTER_SIZE` parameter and we can just pass it `etcd1.weave.local` and drop our [amazing node list generator](https://github.com/weaveworks/weave-kubernetes-anywhere/blob/master/docker-images/apiserver-anywhere.sh#L3).

Secondly, etcd node replacement story won't work and magically just because the DNS name is the same, as all nodes are considered unique, although this could have worked with some very old version. So all user really benefits from is that no API server config change is needed when etcd cluster changes in any way.

**Comment by jonboulle** [comment]
Here's the relevant parts of the etcd client that control the cluster member list being updated:
Manual: https://github.com/coreos/etcd/blob/595cfd9a11de7fafe5d0282c643d8d56e5608999/client/client.go#L172
Automatic: https://github.com/coreos/etcd/blob/595cfd9a11de7fafe5d0282c643d8d56e5608999/client/client.go#L175

**Comment by errordeveloper** [comment]
@jonboulle thank you for the references!
