### ISSUE TITLE
Hanging after provisioning cluster - "Waiting for Cluster: Expected 2 healthy nodes; found 0."

### ISSUE THREAD

**Issue by brunoriscado** [kubernetes/kubernetes-anywhere#230]
This seems like it's running the utils validate script and validating whether the kubernetes nodes are running and it's failing.

Any idea?

**Comment by mikedanese** [comment]
What cloud provider are you using?

**Comment by brunoriscado** [comment]
sorry, I completely missed that, I'm using azure.

**Comment by colemickens** [comment]
1. How long did you wait for the nodes to come up?

2. Did you supply your own Service Principal credentials?

The only thing I can suggest, if you made it all the way to the validation step... is to look to SSH into the master node, make sure `sudo systemctl status kubelet`  says that kubelet is running, and then SSH to your nodes (from the master since they don't themselves have public ips) and check the same thing.

**Comment by brunoriscado** [comment]
Hi,

I've waited over 3000s, eventually interrupted the loop of the validation script.
Yes, the principal credentials have been supplied, the cluster was fully provisioned on azure.

I was going to check if the kubelet is running, not sure where kubernetes-anywhere is storing the rsa key though, in azkube they could be copied with the util script.

**Comment by colemickens** [comment]
Kubernetes-Anywhere just uses password auth for now. Switching to key auth is on the backlog. There aren't quite as many post-deployment niceties as there were with azkube, but I'm open to adding them here over time as well.

"The cluster was fully provisioned" means that the resources were created? I assume it was still not in a good state... otherwise the validation script would have succeeded. Did you end up tearing down the resources and trying again, or have you just been stuck since your last attempt?

**Comment by brunoriscado** [comment]
It created a Vnet, a storage account, master vm, node, availability set, network interfaces for both nodes, a public ip address tied to the master network interface and a route table. So pretty much the resources needed in azure.

I've done this a number of times and usually tear the env down by deleting the resource group. Terraform seems to complete with no errors.

When I log into the master and check kubelet status, I see:

```
 kubelet.service - Kubernetes Kubelet Server
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2016-09-20 14:06:23 UTC; 5h 1min ago
     Docs: https://github.com/kubernetes/kubernetes
  Process: 6172 ExecStartPre=/bin/mount --make-shared /var/lib/kubelet (code=exited, status=0/SUCCESS)
  Process: 6169 ExecStartPre=/bin/mount --bind /var/lib/kubelet /var/lib/kubelet (code=exited, status=0/SUCCESS)
  Process: 6165 ExecStartPre=/bin/mkdir -p /var/lib/kubelet (code=exited, status=0/SUCCESS)
 Main PID: 6176 (docker)
    Tasks: 4
   Memory: 4.8M
      CPU: 235ms
   CGroup: /system.slice/kubelet.service
           └─6176 /usr/bin/docker run --net=host --pid=host --privileged -v /dev:/dev -v /sys:/sys:ro -v /var/run:/var/run:rw -v /var/lib/docker/:/var/lib/docker:rw -v /var/lib/kubelet/:/var/lib/kubelet:shared -v /srv/kubernetes:/srv/kube

Sep 20 19:07:02 sayt-master docker[6176]: I0920 19:07:02.072305    6289 conversion.go:133] failed to handle multiple devices for container. Skipping Filesystem stats
Sep 20 19:07:02 sayt-master docker[6176]: I0920 19:07:02.072496    6289 conversion.go:133] failed to handle multiple devices for container. Skipping Filesystem stats
Sep 20 19:07:12 sayt-master docker[6176]: I0920 19:07:12.104934    6289 conversion.go:133] failed to handle multiple devices for container. Skipping Filesystem stats
Sep 20 19:07:12 sayt-master docker[6176]: I0920 19:07:12.105069    6289 conversion.go:133] failed to handle multiple devices for container. Skipping Filesystem stats
Sep 20 19:07:22 sayt-master docker[6176]: I0920 19:07:22.117304    6289 conversion.go:133] failed to handle multiple devices for container. Skipping Filesystem stats
Sep 20 19:07:22 sayt-master docker[6176]: I0920 19:07:22.117447    6289 conversion.go:133] failed to handle multiple devices for container. Skipping Filesystem stats
Sep 20 19:07:32 sayt-master docker[6176]: I0920 19:07:32.162878    6289 conversion.go:133] failed to handle multiple devices for container. Skipping Filesystem stats
Sep 20 19:07:32 sayt-master docker[6176]: I0920 19:07:32.163111    6289 conversion.go:133] failed to handle multiple devices for container. Skipping Filesystem stats
Sep 20 19:07:42 sayt-master docker[6176]: I0920 19:07:42.182058    6289 conversion.go:133] failed to handle multiple devices for container. Skipping Filesystem stats
Sep 20 19:07:42 sayt-master docker[6176]: I0920 19:07:42.182206    6289 conversion.go:133] failed to handle multiple devices for container. Skipping Filesystem stats

```


I've made a util script which contains the following:

```
#!/bin/sh
createCluster() {
    make docker-dev;
    docker exec "$(docker ps -a | grep "kubernetes-anywhere:v0.0.1" | awk '{print $1}')" make deploy;
}

tearDownCluster() {
    azure group delete $1; docker rmi -f $(docker images -q); docker rm -f $(docker ps -a -q);
}

cleanAllContainerProcesses() {
    docker rm -f $(docker ps -a -q);
}

cleanAllImages() {
    docker rmi -f $(docker images -q);
}

```

**Comment by brunoriscado** [comment]
Still having issues, essentially this is what is being ran to create the cluster:

```
docker build -t kubernetes-anywhere:v0.0.1 .;
docker run -d -it --net=host --volume="`pwd`:/opt/kubernetes-anywhere" kubernetes-anywhere:v0.0.1 bash
docker exec "$(docker ps -a | grep "kubernetes-anywhere:v0.0.1" | awk '{print $1}')" make deploy;
```

**Comment by brunoriscado** [comment]
Ok, I think the problem is sorted, and it was related with the fact that I was not tearing down the cluster correctly. I appreciate the assistance.
