### ISSUE TITLE
Documentation change for Azure

### ISSUE THREAD

**Issue by dcieslak19973** [kubernetes/kubernetes-anywhere#234]
Where it says:

The name chosen for phase1.cluster_name needs to be globally unique.

It should also include the restriction that the name _may not_ include numbers. The name _must only_ contain characters.

**Comment by ahmetalpbalkan** [comment]
@dcieslak19973 I don't think the "may not include numbers" part is entirely correct. I just created a cluster with name `ahmet0`.

As far as I can tell, the cluster name is used to specify a storage account name which should be:

- Must be unique across azure
- Must be at most 64 characters
- only alphanumeric characters and underscores are valid (same as domain name requirements)
- must start with a letter

I do not see the name being used anywhere else than storage account on Azure API plane, @colemickens can confirm.

**Comment by colemickens** [comment]
The name is actually used as a prefix for all resources and is the "cluster name" used by Kubernetes internally (only in a few places). It happens to be the case that the storage account name is the most restrictive one (and happens to be the thing that demands global uniqueness).

For example, this looks like a cluster deployed with a `cluster_name` of `ahmet-k8s` (dashes are automatically removed for the storage account name):

<img width="504" alt="screen shot 2016-09-28 at 10 58 52 am" src="https://cloud.githubusercontent.com/assets/327028/18925973/dc4e0b10-856a-11e6-9ad2-744864c978e5.png">

I can send a PR to update the docs with the requirements that @ahmetalpbalkan has pointed out. Thanks Ahmet!

**Comment by colemickens** [comment]
(Except I think the max length is 24, not 64. That's what your link says as well @ahmetalpbalkan.)

**Comment by ahmetalpbalkan** [comment]
my bad. it's 24.

**Comment by ggm-at-apnic** [comment]
I was deeply confused by the word 'global' -this must be unique, inside the given account in Azure, it is not a uuid, and does not have to be a domain name, or unique worldwide, its global for the namespace in question, which is your Azure account, and all names within it.

**Comment by colemickens** [comment]
That's not correct, storage accounts are in a shared global namespace.

**Comment by ahmetalpbalkan** [comment]
@colemickens would generating a random storage account name solve the globally-unique requirement? afaict, we don't use the name in FQDNs or anything and we store the storage account name in config/state files anyway?

**Comment by colemickens** [comment]
That's possible, but neither `jsonnet` nor `terraform` have any ability to generate a random identifier. It could be hacked into `phase1/azure/do`... possibly, but it would be a bit messy.

**Comment by ggm-at-apnic** [comment]
If its truly global then a shell generated UUID feels like the best option.
the prompt could eg say "If you pre-made one in the UI, put the value here
or [$uuid]" where $uuid is spun from the local host.

**Comment by colemickens** [comment]
Yes, understood, I will evaluate adding something like this. I think it can be achieved by adding a new deployment parameter "Storage_account" and encouraging people to leave it blank.

Then in the pre-deploy-validation step (where I currently do the SP auto-generation work), we can detect an empty storage account name and generate a GUID.

Good suggestions, I'll implement this ASAP. Thanks!

**Comment by colemickens** [comment]
This has been implemented. Going to close this one out. Thanks for the discussion.
