### ISSUE TITLE
Discussion: Adopt kubeadm instead of ignition

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes-anywhere#239]
Does it make sense to completely remove ignition and just switch to `kubeadm`?

`phase2` could more or less go away and `phase1` implementations would be required to install the `kubeadm` package from their package manager (or otherwise) and then execute `kubeadm` with a pre-seeded token.

CC: @errordeveloper @mikedanese

**Comment by colemickens** [comment]
Looks like there's someone doing AWS+Terraform+Kubeadm already: https://github.com/upmc-enterprises/kubeadm-aws and

**Comment by errordeveloper** [comment]
I think we still need ignition to install packages and run kubeadm, or do
we?

**Comment by mikedanese** [comment]
:+1: This would be great. Is the install process simple enough to shove into the configure-vm.sh script?

**Comment by colemickens** [comment]
Yeah, if there is an apt repo with kubeadm packages, I'm hoping it'd be pretty easy to add it, install kubeadm and let it handle the rest. That's what I was thinking at least. I'll try to explore it as an option more.

**Comment by theobolo** [comment]
Like this one ? 

`curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF > /etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main`

**Comment by colemickens** [comment]
@mikedanese Just saw your comment: https://github.com/kubernetes/kubernetes/issues/34136#issuecomment-253872071

Is this something you're going to actively start working on soon?

**Comment by mikedanese** [comment]
No one is working on it, I'm hoping to get to it but I have to wrap up some other PRs. @pipejakob might be interested in it.

**Comment by pipejakob** [comment]
Pull request: https://github.com/kubernetes/kubernetes-anywhere/pull/270
