### ISSUE TITLE
High Availability

### ISSUE THREAD

**Issue by dcieslak19973** [kubernetes/kubernetes-anywhere#242]
If its within the scope of this project, having an option to create a High Availability cluster (e.g. 3 master nodes) would be good

**Comment by ekozan** [comment]
I think this will comme with kubeadm

**Comment by colemickens** [comment]
Can you clarify @ekozan ?

**Comment by colemickens** [comment]
I've only seen examples of `kubeadm` usage with single-master, and it doesn't really help with the phase1 changes that would be necessary to support HA. Put another way, the changes to support kubeadm and the changes needed to support HA are a bit orthogonal from my perspective.

**Comment by ekozan** [comment]
kubeadm will support HA
Kubeadm will be integrated to kubernetes-anywhere soon 

So i think HA will not be integrated before :)

**Comment by carpenterm** [comment]
+1
