### ISSUE TITLE
The interactions with Client ID, Service Principal, Application permissions is not clear

### ISSUE THREAD

**Issue by ggm-at-apnic** [kubernetes/kubernetes-anywhere#244]
I'm a clean skin, I just brought up Azure free edition from scratch Empty state. This script is unable to bootstrap kubernetes because of the interactions through the azure command tool to make the Service Principal phase work. 

I have tried about three different paths to do this, using other peoples documentation on how to give the right permissions, none of which make sense because they assume prior knowledge of AD and Microsoft behaviours: this script is trying to elide over this problem but I think misses a stage.

I think one of your core developers needs to swing up a new, clean Microsoft Azure account and try bootstrap from scratch because the current package can't do it.

A typical error state is:

```
Error refreshing state: 1 error(s) occurred:

* Credentials for acessing the Azure Resource Manager API are likely to be incorrect, or
  the service principal does not have permission to use the Azure Service Management
  API.
Error refreshing state: 1 error(s) occurred:

* Credentials for acessing the Azure Resource Manager API are likely to be incorrect, or
  the service principal does not have permission to use the Azure Service Management
  API.
```

**Comment by ggm-at-apnic** [comment]
For example: in clean, unused state, I have a login in Microsoft Azure with a single account in the AD. the login is <username>@host.domain. Is this my Service Principal ID? 

If I was to make a service principal via the azure command I would be invoking something like this:
```azure ad sp create -n <nice name> -p <password>```
Which takes no other arguments, and does not require an application ID

I would then be expected in AD to assign a role status to this:

```azure role assignment create --objectId <uuid from above> -o Contributor -c /subscriptions/<uuid of this subscription/```

It's not clear how this applies to the script. Does the <nice name> become the value for the Client ID? Does <password> become the value for Client Password? Do I need the <uuid> equivalents of this new role?

**Comment by ggm-at-apnic** [comment]
I cribbed the commands to run in the Azure CLI from:
```https://azure.microsoft.com/en-us/documentation/articles/resource-group-authenticate-service-principal-cli/```

**Comment by ggm-at-apnic** [comment]
i cribbed the commands to run from:

https://azure.microsoft.com/en-us/documentation/articles/resource-group-authenticate-service-principal-cli/

But I had to delete most of the extended arguments which appear not to exist in the version of Azure I have on OSX

**Comment by colemickens** [comment]
>I think one of your core developers needs to swing up a new, clean Microsoft Azure account and try bootstrap from scratch because the current package can't do it.

I can assure you I'm doing that on a regular basis.

There is a very small bug related to AAD propagation delays. If you had merely waited and executed `make deploy` again it would've worked fine. I will be documenting this in the next few minutes.

**Comment by colemickens** [comment]
Also, yes, AAD concepts can be confusing. Unfortunately, I can't explain it any better than [the official Azure AAD documentation does](https://azure.microsoft.com/en-us/documentation/articles/active-directory-application-objects/).

**Comment by colemickens** [comment]
This pull request will document the edge case you hit, as well as a workaround. It also attempts to prevent you from ever seeing this problem in the first place. https://github.com/kubernetes/kubernetes-anywhere/pull/247

**Comment by ggm-at-apnic** [comment]
Thanks! Close the issue, there's nothing to see here.
