### ISSUE TITLE
Service Principal doesn't reference a valid application object

### ISSUE THREAD

**Issue by ggm-at-apnic** [kubernetes/kubernetes-anywhere#251]
inside  the docker, after `make docker-dev` a run of `make deploy` dies shortly after the creation of the client ID instance.

The error state ls:

```
2016-09-30T03:58:24.611Z:
{ Error: {"odata.error":{"code":"Request_BadRequest","message":{"lang":"en","value":"The appId of the service principal does not reference a valid application object."},"values":[{"item":"PropertyName","value":"appId"},{"item":"PropertyErrorCode","value":"NoBackingApplicationObject"}]}}
  <<< async stack >>>
  at __1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/ad/ad.servicePrincipals.js:174:41)
  at __3 (/usr/lib/node_modules/azure-cli/lib/commands/arm/ad/ad.servicePrincipals.js:172:30)
  <<< raw stack >>>
    at /usr/lib/node_modules/azure-cli/node_modules/azure-graph/lib/operations/servicePrincipals.js:145:19
    at retryCallback (/usr/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (/usr/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/redirectFilter.js:36:9)
    at /usr/lib/node_modules/azure-cli/lib/util/utils.js:587:7
    at handleRedirect (/usr/lib/node_modules/azure-cli/lib/util/utils.js:564:9)
    at /usr/lib/node_modules/azure-cli/lib/util/logging.js:339:7
    at Request._callback (/usr/lib/node_modules/azure-cli/node_modules/ms-rest/lib/requestPipeline.js:125:16)
    at Request.self.callback (/usr/lib/node_modules/azure-cli/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
  stack: [Getter/Setter],
  statusCode: 400,
  request: 
   { rawResponse: false,
     queryString: {},
     method: 'POST',
     headers: 
      { 'x-ms-client-request-id': '50ab48e0-85d7-4000-83cb-aa9094b67cfe',
        'accept-language': 'en-US',
        'Content-Type': 'application/json; charset=utf-8',
        'user-agent': 'WindowsAzureXplatCLI/0.10.5' },
     url: 'https://graph.windows.net/8134123d-2209-41c1-87f1-c410786b408f/servicePrincipals?api-version=1.6',
     body: '{"appId":"36c3f8b4-f370-4782-a6ac-a459833329b3","accountEnabled":true}' },
  response: 
   { body: '{"odata.error":{"code":"Request_BadRequest","message":{"lang":"en","value":"The appId of the service principal does not reference a valid application object."},"values":[{"item":"PropertyName","value":"appId"},{"item":"PropertyErrorCode","value":"NoBackingApplicationObject"}]}}',
     headers: 
      { 'cache-control': 'private',
        'content-type': 'application/json;odata=minimalmetadata;charset=utf-8',
        server: 'Microsoft-IIS/8.5',
        'ocp-aad-diagnostics-server-name': 'HgGHeNSQrM9XpX3oc/01cDMvT65hkzBBO7e+bQY/4x4=',
        'request-id': '2afba286-0eab-453c-9214-48ff0c73ecf4',
        'client-request-id': '83d133c1-61d6-4bfc-9133-b98df79922c5',
        'x-ms-dirapi-data-contract-version': '1.6',
        'ocp-aad-session-key': '<removed>',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        'access-control-allow-origin': '*',
        'x-aspnet-version': '4.0.30319',
        'x-powered-by': 'ASP.NET, ASP.NET',
        duration: '2357676',
        date: 'Fri, 30 Sep 2016 03:58:25 GMT',
        connection: 'close',
        'content-length': '278' },
     statusCode: 400 },
  body: 
   { code: 'Request_BadRequest',
     message: 'The appId of the service principal does not reference a valid application object.' },
  __frame: 
   { name: '__1',
     line: 173,
     file: '/usr/lib/node_modules/azure-cli/lib/commands/arm/ad/ad.servicePrincipals.js',
     prev: 
      { name: '__3',
        line: 103,
        file: '/usr/lib/node_modules/azure-cli/lib/commands/arm/ad/ad.servicePrincipals.js',
        prev: undefined,
        calls: 1,
        active: false,
        offset: 69,
        col: 29 },
     calls: 0,
     active: false,
     offset: 1,
     col: 40 },
  rawStack: [Getter] }
Error: {"odata.error":{"code":"Request_BadRequest","message":{"lang":"en","value":"The appId of the service principal does not reference a valid application object."},"values":[{"item":"PropertyName","value":"appId"},{"item":"PropertyErrorCode","value":"NoBackingApplicationObject"}]}}
  <<< async stack >>>
  at __1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/ad/ad.servicePrincipals.js:174:41)
  at __3 (/usr/lib/node_modules/azure-cli/lib/commands/arm/ad/ad.servicePrincipals.js:172:30)
  <<< raw stack >>>
    at /usr/lib/node_modules/azure-cli/node_modules/azure-graph/lib/operations/servicePrincipals.js:145:19
    at retryCallback (/usr/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (/usr/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/redirectFilter.js:36:9)
    at /usr/lib/node_modules/azure-cli/lib/util/utils.js:587:7
    at handleRedirect (/usr/lib/node_modules/azure-cli/lib/util/utils.js:564:9)
    at /usr/lib/node_modules/azure-cli/lib/util/logging.js:339:7
    at Request._callback (/usr/lib/node_modules/azure-cli/node_modules/ms-rest/lib/requestPipeline.js:125:16)
    at Request.self.callback (/usr/lib/node_modules/azure-cli/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
```

**Comment by ggm-at-apnic** [comment]
my git state is: efd642dfb0d09995e5fe1c27664cfa5a1dcd3410

**Comment by colemickens** [comment]
Can you please delete your `.config` and `.config.json` and try again? I
strongly suspect some stale state from a previous attempt is interfering.

**Comment by ggm-at-apnic** [comment]
I re-ran with make clean and rm -f .config .config.json. Same outcome.

**Comment by ggm-at-apnic** [comment]
```
Successfully built 942eb6dc568c
Starting Kuberetes Anywhere deployment shell in a container
docker run -it --rm --env="PS1=[container]:\w> " --net=host --volume="`pwd`:/opt/kubernetes-anywhere" kubernetes-anywhere:v0.0.1 /bin/bash
[container]:/opt/kubernetes-anywhere> make clean
rm -rf .tmp
rm -rf phase3/.tmp
rm -rf phase1/gce/.tmp
rm -rf phase1/azure/.tmp
[container]:/opt/kubernetes-anywhere> rm .config .config.json 
[container]:/opt/kubernetes-anywhere> make deploy
make config
make[1]: Entering directory '/opt/kubernetes-anywhere'
CONFIG_="." kconfig-conf Kconfig
*
* Kubernetes Minimal Turnup Configuration
*
*
* Phase 1: Cluster Resource Provisioning
*
number of nodes (phase1.num_nodes) [4] (NEW) 
cluster name (phase1.cluster_name) [kubernetes] (NEW) ggm4
*
* cloud provider
*
cloud provider (phase1.cloud_provider) [gce] (NEW) azure
  *
  * Azure configuration
  *
  Azure SubscriptionID (phase1.azure.subscription_id) [] (NEW) 4babca81-4251-40e1-9f9c-def756f4db23
  Azure TenantID (phase1.azure.tenant_id) [] (NEW)  8134123d-2209-41c1-87f1-c410786b408f
  Azure Active Directory ServicePrincipal ClientID (phase1.azure.client_id) [] (NEW)   
  Azure Active Directory ServicePrincipal ClientSecret (phase1.azure.client_secret) [] (NEW) 
  Base Virtual Machine OS Image (phase1.azure.image_publisher) [canonical] (NEW) 
  Base Virtual Machine OS Image (phase1.azure.image_offer) [ubuntuserver] (NEW) 
  Base Virtual Machine OS Image (phase1.azure.image_sku) [16.04.0-LTS] (NEW) 
  Base Virtual Machine OS Image (phase1.azure.image_version) [latest] (NEW) 
  Virtual Machine Size (Master) (phase1.azure.master_vm_size) [Standard_D1_v2] (NEW) 
  Virtual Machine Size (Node) (phase1.azure.node_vm_size) [Standard_D1_v2] (NEW) 
  Private IP address of Master (phase1.azure.master_private_ip) [10.240.1.4] (NEW) 
  Resource Location (phase1.azure.location) [westus2] (NEW) 
  Virtual Machine Admin Username (phase1.azure.admin_username) [kube] (NEW) 
  Virtual Machine Admin Password (phase1.azure.admin_password) [Ch@ng3ThisPassword] (NEW) <removed>
*
* Phase 2: Node Bootstrapping
*
installer container (phase2.installer_container) [docker.io/colemickens/k8s-ignition:latest] (NEW) 
docker registry (phase2.docker_registry) [gcr.io/google-containers] (NEW) 
kubernetes version (phase2.kubernetes_version) [v1.4.0] (NEW) 
*
* Phase 3: Deploying Addons
*
Run the addon manager? (phase3.run_addons) [Y/n/?] (NEW) 
  Run kube-proxy? (phase3.kube_proxy) [Y/n/?] (NEW) 
  Run the dashboard? (phase3.dashboard) [Y/n/?] (NEW) 
  Run heapster? (phase3.heapster) [Y/n/?] (NEW) 
  Run kube-dns? (phase3.kube_dns) [Y/n/?] (NEW) 
#
# configuration written to .config
#
make[1]: Leaving directory '/opt/kubernetes-anywhere'
util/config_to_json .config > .config.json
make do WHAT=deploy-cluster
make[1]: Entering directory '/opt/kubernetes-anywhere'
( cd "phase1/$(jq -r '.phase1.cloud_provider' .config.json)"; ./do deploy-cluster )

Azure 'client_id' and 'client_secret' are empty.
This will now create a ServicePrincipal named 'ggm4', identified by 'http://ggm4' which will be granted 'Contributor' access to the specific subscription.
Proceed and create new ServicePrincipal? [y/n] y
info:    Executing command login
/info:    To sign in, use a web browser to open the page https://aka.ms/devicelogin. Enter the code HAHSHDNGF to authenticate.
-info:    Added subscription Free Trial
info:    Setting subscription "Free Trial" as default
+
info:    login command OK
error:   {"odata.error":{"code":"Request_BadRequest","message":{"lang":"en","value":"The appId of the service principal does not reference a valid application object."},"values":[{"item":"PropertyName","value":"appId"},{"item":"PropertyErrorCode","value":"NoBackingApplicationObject"}]}}
error:   Error information has been recorded to /root/.azure/azure.err
error:   ad sp create command failed

Makefile:53: recipe for target 'do' failed
make[1]: *** [do] Error 1
make[1]: Leaving directory '/opt/kubernetes-anywhere'
Makefile:41: recipe for target 'deploy-cluster' failed
make: *** [deploy-cluster] Error 2
[container]:/opt/kubernetes-anywhere>
```

**Comment by colemickens** [comment]
Hi @ggm-at-apnic. On the other thread you wrote that you "applied the patches, and got the outcome". Does that mean things are working now?

The only change made today that would've affected you is adding an additional sleep to workaround AAD propagation delays. (It's possible that it can still happen. Unfortunately the best I can do for now is to add that extra sleep and document that users may have to wait a minute or two and retry.)

If it's all working we can go ahead and close this out, hopefully. Thanks!

**Comment by ggm-at-apnic** [comment]
No, It is not working.

I applied all the patches you have shipped, I am on head. I get the error I
consistently send you, in any response. The added delay has not fixed my
problem.

Please don't close this out: the docker and commands as documented *do not
work* for me, on a clean state.

**Comment by colemickens** [comment]
I'm not going to close it until we get it sorted.

Can you please change `cluster_name` and try again? Again, I suspect that you are having issues because you are re-using a SP/App name that was misconfigured by your other attempts.

**Comment by colemickens** [comment]
Alternatively, you can login to the new AAD section of the Azure Portal and clear out the existing `ggm4` Application and see if that helps you progress further.

**Comment by ggm-at-apnic** [comment]
here is a log of a clean-state run.

I even blew away the package and re-cloned.

ggmwork-2 $ rm -rf kubernetes-anywhere

ggmwork-2 $ git clone https://github.com/kubernetes/kubernetes-anywhere.git
(push)

-bash: syntax error near unexpected token `('

ggmwork-2 $ git clone https://github.com/kubernetes/kubernetes-anywhere.git

Cloning into 'kubernetes-anywhere'...

remote: Counting objects: 3774, done.

remote: Total 3774 (delta 0), reused 0 (delta 0), pack-reused 3774

Receiving objects: 100% (3774/3774), 3.92 MiB | 1.11 MiB/s, done.

Resolving deltas: 100% (2360/2360), done.

ggmwork-2 $ cd kubernetes-anywhere/

ggmwork-2 $ make docker-dev

docker build -t kubernetes-anywhere:v0.0.1 .

Sending build context to Docker daemon 158.7 kB

Step 1 : FROM mhart/alpine-node:6.4.0

 ---> ecd37ad77c2b

Step 2 : RUN apk add --update bash

 ---> Using cache

 ---> 3ccd42197a72

Step 3 : ADD ./util/docker-build.sh /opt/

 ---> Using cache

 ---> 2ec520abd49b

Step 4 : RUN /opt/docker-build.sh

 ---> Using cache

 ---> dfcab737b706

Step 5 : WORKDIR /opt/kubernetes-anywhere

 ---> Using cache

 ---> d95255151329

Step 6 : ADD . /opt/kubernetes-anywhere/

 ---> Using cache

 ---> af4ea238493b

Step 7 : CMD make

 ---> Using cache

 ---> 6bef7b3aba25

Successfully built 6bef7b3aba25

Starting Kuberetes Anywhere deployment shell in a container

docker run -it --rm --env="PS1=[container]:\w> " --net=host
--volume="`pwd`:/opt/kubernetes-anywhere" kubernetes-anywhere:v0.0.1
/bin/bash

[container]:/opt/kubernetes-anywhere> make clean

rm -rf .tmp

rm -rf phase3/.tmp

rm -rf phase1/gce/.tmp

rm -rf phase1/azure/.tmp

[container]:/opt/kubernetes-anywhere> rm .config .config-json

rm: can't remove '.config': No such file or directory

rm: can't remove '.config-json': No such file or directory

[container]:/opt/kubernetes-anywhere>

[container]:/opt/kubernetes-anywhere> rm .config .config.json

rm: can't remove '.config': No such file or directory

rm: can't remove '.config.json': No such file or directory

[container]:/opt/kubernetes-anywhere> make deploy

make config

make[1]: Entering directory '/opt/kubernetes-anywhere'

CONFIG_="." kconfig-conf Kconfig

*

* Kubernetes Minimal Turnup Configuration

*

*

* Phase 1: Cluster Resource Provisioning

*

number of nodes (phase1.num_nodes) [4] (NEW)

cluster name (phase1.cluster_name) [kubernetes] (NEW) newrandomkube

*

* cloud provider

*

cloud provider (phase1.cloud_provider) [gce] (NEW) azure

  *

  * Azure configuration

  *

  Azure SubscriptionID (phase1.azure.subscription_id) [] (NEW)
4babca81-4251-40e1-9f9c-def756f4db23

  Azure Active Directory ServicePrincipal ClientID (phase1.azure.client_id)
[] (NEW)

  Azure Active Directory ServicePrincipal ClientSecret
(phase1.azure.client_secret) [] (NEW)

  Base Virtual Machine OS Image (phase1.azure.image_publisher) [canonical]
(NEW)

  Base Virtual Machine OS Image (phase1.azure.image_offer) [ubuntuserver]
(NEW)

  Base Virtual Machine OS Image (phase1.azure.image_sku) [16.04.0-LTS]
(NEW)

  Base Virtual Machine OS Image (phase1.azure.image_version) [latest] (NEW)

  Azure Storage Account Name (phase1.azure.storage_account_name) [] (NEW)

  Virtual Machine Size (Master) (phase1.azure.master_vm_size)
[Standard_D1_v2] (NEW)

  Virtual Machine Size (Node) (phase1.azure.node_vm_size) [Standard_D1_v2]
(NEW)

  Private IP address of Master (phase1.azure.master_private_ip)
[10.240.1.4] (NEW)

  Resource Location (phase1.azure.location) [westus2] (NEW)

  Virtual Machine Admin Username (phase1.azure.admin_username) [kube] (NEW)

  Virtual Machine Admin Password (phase1.azure.admin_password)
[Ch@ng3ThisPassword] (NEW) <removed>

*

* Phase 2: Node Bootstrapping

*

installer container (phase2.installer_container) [
docker.io/colemickens/k8s-ignition:latest] (NEW)

docker registry (phase2.docker_registry) [gcr.io/google-containers] (NEW)

kubernetes version (phase2.kubernetes_version) [v1.4.0] (NEW)

*

* Phase 3: Deploying Addons

*

Run the addon manager? (phase3.run_addons) [Y/n/?] (NEW)

  Run kube-proxy? (phase3.kube_proxy) [Y/n/?] (NEW)

  Run the dashboard? (phase3.dashboard) [Y/n/?] (NEW)

  Run heapster? (phase3.heapster) [Y/n/?] (NEW)

  Run kube-dns? (phase3.kube_dns) [Y/n/?] (NEW)

#

# configuration written to .config

#

make[1]: Leaving directory '/opt/kubernetes-anywhere'

util/config_to_json .config > .config.json

make do WHAT=deploy-cluster

make[1]: Entering directory '/opt/kubernetes-anywhere'

( cd "phase1/$(jq -r '.phase1.cloud_provider' .config.json)"; ./do
deploy-cluster )


Azure 'client_id' and 'client_secret' are empty.

This will now create a ServicePrincipal named 'newrandomkube', identified
by 'http://newrandomkube' which will be granted 'Contributor' access to the
specific subscription.

Proceed and create new ServicePrincipal? [y/n] y


info:    Executing command login

/info:    To sign in, use a web browser to open the page
https://aka.ms/devicelogin. Enter the code HBLPTK9MH to authenticate.

/info:    Added subscription Free Trial

info:    Setting subscription "Free Trial" as default

+

info:    login command OK

error:
{"odata.error":{"code":"Request_BadRequest","message":{"lang":"en","value":"The
appId of the service principal does not reference a valid application
object."},"values":[{"item":"PropertyName","value":"appId"},{"item":"PropertyErrorCode","value":"NoBackingApplicationObject"}]}}

error:   Error information has been recorded to /root/.azure/azure.err

error:   ad sp create command failed


Makefile:53: recipe for target 'do' failed

make[1]: *** [do] Error 1

make[1]: Leaving directory '/opt/kubernetes-anywhere'

Makefile:41: recipe for target 'deploy-cluster' failed

make: *** [deploy-cluster] Error 2

[container]:/opt/kubernetes-anywhere>

**Comment by colemickens** [comment]
Hm! Thanks for your patience and help in troubleshooting this.

Would you mind giving me a copy of the `azure.err` file? If you want, you can run this (`cp /root/.azure/azure.err /opt/kubernetes-anywhere/azure.err), and it will copy it into the volume so you can access it from your host to drag/drop on Github or as a Gist.

I may have to consult with some more folks tomorrow to make more forward progress.

**Comment by ggm-at-apnic** [comment]
Ok. here it is.

[azure.err.zip](https://github.com/kubernetes/kubernetes-anywhere/files/502311/azure.err.zip)

**Comment by ggm-at-apnic** [comment]
status? I am basically roadblocked on this.

-G

**Comment by colemickens** [comment]
Hi @ggm-at-apnic, I'll take a look at this again today.

In the meantime, you can create your own App / Service Principal through the legacy portal and unblock yourself: https://www.terraform.io/docs/providers/azurerm/ has instructions.

**Comment by colemickens** [comment]
Additionally, if you can edit the file `phase1/azure/create-azure-service-principal.sh` and add `set -x` near the top, and then try the deployment again (with a new/unique `cluster_name`) and send me the output, that would be helpful.

So far, I'm having a hard time understanding why Graph API is telling you that it created the App but then when you go to create an SP, it claims to not know about that App. That's not meant to happen, and I'm unable to repro, so more hints from you would be helpful depending on how much you want to help debug this.

**Comment by ggm-at-apnic** [comment]
```
[container]:/opt/kubernetes-anywhere> make deploy
make config
make[1]: Entering directory '/opt/kubernetes-anywhere'
CONFIG_="." kconfig-conf Kconfig
*
* Kubernetes Minimal Turnup Configuration
*
*
* Phase 1: Cluster Resource Provisioning
*
number of nodes (phase1.num_nodes) [4] (NEW)
cluster name (phase1.cluster_name) [kubernetes] (NEW) ggmtestingatapnicdotnet
*
* cloud provider
*
cloud provider (phase1.cloud_provider) [gce] (NEW) azure
  *
  * Azure configuration
  *
  Azure SubscriptionID (phase1.azure.subscription_id) [] (NEW) 4babca81-4251-40e1-9f9c-def756f4db23
  Azure Active Directory ServicePrincipal ClientID (phase1.azure.client_id) [] (NEW)
  Azure Active Directory ServicePrincipal ClientSecret (phase1.azure.client_secret) [] (NEW)
  Base Virtual Machine OS Image (phase1.azure.image_publisher) [canonical] (NEW)
  Base Virtual Machine OS Image (phase1.azure.image_offer) [ubuntuserver] (NEW)
  Base Virtual Machine OS Image (phase1.azure.image_sku) [16.04.0-LTS] (NEW)
  Base Virtual Machine OS Image (phase1.azure.image_version) [latest] (NEW)
  Azure Storage Account Name (phase1.azure.storage_account_name) [] (NEW)
  Virtual Machine Size (Master) (phase1.azure.master_vm_size) [Standard_D1_v2] (NEW)
  Virtual Machine Size (Node) (phase1.azure.node_vm_size) [Standard_D1_v2] (NEW)
  Private IP address of Master (phase1.azure.master_private_ip) [10.240.1.4] (NEW)
  Resource Location (phase1.azure.location) [westus2] (NEW)
  Virtual Machine Admin Username (phase1.azure.admin_username) [kube] (NEW)
  Virtual Machine Admin Password (phase1.azure.admin_password) [Ch@ng3ThisPassword] (NEW) mumbledypeg
*
* Phase 2: Node Bootstrapping
*
installer container (phase2.installer_container) [docker.io/colemickens/k8s-ignition:latest] (NEW)
docker registry (phase2.docker_registry) [gcr.io/google-containers] (NEW)
kubernetes version (phase2.kubernetes_version) [v1.4.1] (NEW)
*
* Phase 3: Deploying Addons
*
Run the addon manager? (phase3.run_addons) [Y/n/?] (NEW)
  Run kube-proxy? (phase3.kube_proxy) [Y/n/?] (NEW)
  Run the dashboard? (phase3.dashboard) [Y/n/?] (NEW)
  Run heapster? (phase3.heapster) [Y/n/?] (NEW)
  Run kube-dns? (phase3.kube_dns) [Y/n/?] (NEW)
#
# configuration written to .config
#
make[1]: Leaving directory '/opt/kubernetes-anywhere'
util/config_to_json .config > .config.json
make do WHAT=deploy-cluster
make[1]: Entering directory '/opt/kubernetes-anywhere'
( cd "phase1/$(jq -r '.phase1.cloud_provider' .config.json)"; ./do deploy-cluster )

Azure 'client_id' and 'client_secret' are empty.
This will now create a ServicePrincipal named 'ggmtestingatapnicdotnet', identified by 'http://ggmtestingatapnicdotnet' which will be granted 'Contributor' access to the specific subscription.
Proceed and create new ServicePrincipal? [y/n] y
+ set -eu -o pipefail
+ :
+ case ${1:-} in
+ subscription_id=4babca81-4251-40e1-9f9c-def756f4db23
+ shift
+ :
+ case ${1:-} in
+ app_name=ggmtestingatapnicdotnet
+ shift
+ :
+ case ${1:-} in
+ client_secret=56506c9e-3a8e-43b8-b70a-83e58dfb9adf
+ shift
+ :
+ case ${1:-} in
+ app_url=http://ggmtestingatapnicdotnet
+ shift
+ :
+ case ${1:-} in
+ output_format=text
+ shift
+ :
+ case ${1:-} in
+ break
+ [[ ! -z 4babca81-4251-40e1-9f9c-def756f4db23 ]]
+ [[ ! -z http://ggmtestingatapnicdotnet ]]
+ [[ ! -z 56506c9e-3a8e-43b8-b70a-83e58dfb9adf ]]
+ [[ ! -z '' ]]
+ which jq
+ which azure
+ azure account show

++ azure account show --json
++ jq -r '.[] | .tenantId'
+ tenant_id=127d8d0d-7ccf-473d-ab09-6e44ad752ded
++ azure ad app create -n ggmtestingatapnicdotnet -i http://ggmtestingatapnicdotnet --home-page http://ggmtestingatapnicdotnet -p 56506c9e-3a8e-43b8-b70a-83e58dfb9adf --json
+ raw_json='{
  "objectId": "8c355709-70f6-49c3-9c3d-c83a382fe177",
  "objectType": "Application",
  "appId": "2c18775b-56ab-4d67-9975-e854b46c0769",
  "availableToOtherTenants": false,
  "displayName": "ggmtestingatapnicdotnet",
  "identifierUris": [
    "http://ggmtestingatapnicdotnet"
  ],
  "replyUrls": [],
  "homepage": "http://ggmtestingatapnicdotnet"
}'
++ jq -r .appId
++ echo '{' '"objectId":' '"8c355709-70f6-49c3-9c3d-c83a382fe177",' '"objectType":' '"Application",' '"appId":' '"2c18775b-56ab-4d67-9975-e854b46c0769",' '"availableToOtherTenants":' false, '"displayName":' '"ggmtestingatapnicdotnet",' '"identifierUris":' '[' '"http://ggmtestingatapnicdotnet"' '],' '"replyUrls":' '[],' '"homepage":' '"http://ggmtestingatapnicdotnet"' '}'
+ app_id=2c18775b-56ab-4d67-9975-e854b46c0769
+ azure ad sp create --applicationId 2c18775b-56ab-4d67-9975-e854b46c0769
error:   {"odata.error":{"code":"Request_ResourceNotFound","message":{"lang":"en","value":"Resource 'ServicePrincipal_e70ec1f9-5e1e-426d-b3c4-caab61536b18' does not exist or one of its queried reference-property objects are not present."}}}
error:   Error information has been recorded to /root/.azure/azure.err
error:   ad sp create command failed

Makefile:53: recipe for target 'do' failed
make[1]: *** [do] Error 1
make[1]: Leaving directory '/opt/kubernetes-anywhere'
Makefile:41: recipe for target 'deploy-cluster' failed
make: *** [deploy-cluster] Error 2
[container]:/opt/kubernetes-anywhere>
```

**Comment by colemickens** [comment]
Thank you. I'm trying to run this down internally. Please feel free to ping me if I don't get back by early next week.

**Comment by colemickens** [comment]
It's not a great situation, but if you were to insert a `sleep 60` in that script between the `azure ad app create` line and the `azure ad sp create` line, you'll likely make further progress.

**Comment by ggm-at-apnic** [comment]
ok. I've hit the weekend and I am trying to get a decent work-life balance,
so this will wait until next week now.

if the value(s) in question are pollable, perhaps the azure script could
re-write to do some simple while $(true test); do sleep 2;  test-the-value
if [ condition -eq 'ok' ] ... type logic with a sleep 2; or some other form
which in shell did a smaller cost busy-wait cycle around completion? 60
feels like the kind of arbitrary value which we both know is going to fail
for somebody, or enrage the people who live closer to the factory and
really only needed to wait 10

**Comment by colemickens** [comment]
Yeah, I've been asking about that as well...  the problem is: you might poll one server that is replicated, proceed, and then hit another server that hasn't actually replicated.

Unfortunately, global replication status isn't exposed so you can't query that and wait either.

I'll push on this and figure out how we're supposed to handle these sorts of things without just inserting large sleeps... I'm definitely not a fan of that solution.

**Comment by colemickens** [comment]
(Thanks again for the patience)

**Comment by uthark** [comment]
I had the same issue, for me it solved by manual removal of application account in AAD.
