### ISSUE TITLE
Kubernetes-anywhere on azure (networking)

### ISSUE THREAD

**Issue by brunoriscado** [kubernetes/kubernetes-anywhere#253]
I'm facing an issue right now with an azure/kubernetes migration, which is related with the following:

We have a VNET1 (ex: 10.66.0.0/16) and a VNET2 (ex:10.55.0.0/16), within each of the VNETs we have a gateway and we connect both VNETs using these gateways and VPN connections.

VNET1 has an elasticsearch cluster, hosted on subnet 10.66.1.0/24 and VNET2 has a kubernetes cluster hosted on 10.55.1.0/24 (which is provisioned by kubernetes-anywhere).

VNET1 has 3 client boxes for elastic (ex: 10.66.1.4, 10.66.1.5 and 10.66.1.6), and VNET2 has 2 kuberenetes nodes (ex: 10.55.1.4 and 10.55.1.5) as well as a master.

Inside the VNET2 kuberenetes nodes run kubernetes pods (which have a containerized api, that needs a connection to the elasticsearch cluster).

Our kubenetes nodes (ex: VNET2 - 10.55.1.4 and 10.55.1.5), can connect to the elasticsearch nodes (ex: VNET1 - 10.66.1.4, 10.66.1.5 and 10.66.1.6).

However the pods/containers which run on these nodes, and are assigned to their own subnets (ex: 10.244.0.0/24, 10.244.1.0/24), cannot connect to the elasticsearch nodes/VMs or to VM outside of the nodes subnet for that matter. Independent of which VNET this VM might sit on.

Is there something misconfigured in the networking model? Should I be using an overlay network? If I deploy my pods with shared host network, I get connection to elastic, but I can only share one pod per host, otherwise they conflict.

Any help is greatly appreciated.

**Comment by colemickens** [comment]
Hi Bruno. I think that Tim was right on the mailing list. Can you try adjusting your CIDRs or adjusting the `non-masquerade-flag` on the kubelets?

**Comment by colemickens** [comment]
I'm also trying to get an answer from internal sources to determine if Tim's assumption is correct. Based on the fact that it works from the host network, I'm inclined to agree with him.

**Comment by brunoriscado** [comment]
Hi Cole,

a bit of an update on this one. If I create a completely new VM/network interface on a diferent subnet in the k8s cluster VNET, I am now able to have the pods ping it, as long as I add that subnet on the route tables generated on azure.

I'm still not able to ping a VM that is on the other VNET (connected by gateway vpn connections). 

So the node can ping these VMs, but the container still cannot.

I tried adding the non-masquerade-flag on the kubelet service, set to 172.0.0.0/8 and restart the service, but still no luck.

**Comment by colemickens** [comment]
(Cross-linking the mailing list post since the discussion is split between here and there: https://groups.google.com/forum/#!msg/kubernetes-dev/Gp2QBEcuTwI/hl7RKdn2GgAJ)

**Comment by brunoriscado** [comment]
Thanks Cole,

I would love if someone could help me with this network configuration, but I realise that is a bit of a hard request, as it involves having two VNETs and gateway vpn connections between them in order to be able to replicate.

**Comment by NarayanAnnamalai** [comment]
Hello folks,
  IP addresses assigned to pods are not visible in the network. Hence to route to it, you need explicit UDRs (User defined route tables) that point to the hosting node as the next hop IP address. Such an UDR mechanism would nto work for cross referring across VNets that are connected via S2S gateway. You should be using VNet Peering (https://azure.microsoft.com/en-us/documentation/articles/virtual-network-peering-overview/) which allows UDRs to work across VNets, meaning the nexthop IP address can be in a peered VNet.

**Comment by brunoriscado** [comment]
@NarayanAnnamalai -  thanks for the suggestion, I used the nodejs azure sdk to create the vnet peerings and that did sort the connectivity between VM in the first vnet and pods in the second vnet.
