### ISSUE TITLE
Azure ssh keys vs passwords

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes-anywhere#254]
@colemickens is there a reason why k8s-anywhere uses admin password instead of ssh keys? it appears like terraform supports it.

I also see some openssh public keys in `phase1/azure/.tmp/terraform.tfstate.backup`. It appears like the VMs get assigned some form of ssh key?

```
"os_profile_linux_config.2972667452.ssh_keys.#": "0",
```

(not sure what this refers to) but there are fields like `"public_key_openssh"` under keys like `"tls_locally_signed_cert.ahmetb-k8s-node"` too.

It would be good to either:
- accept a public key string (to be used on all nodes) from the user
- or drop the genereted ssh private keys to some output directory

**Comment by colemickens** [comment]
Agreed. Not sure what Terraform is auto-generating, but I was hoping that would be a way of achieving to keep inputs to the deployment minimal. Similar issue: https://github.com/kubernetes/kubernetes-anywhere/issues/182
