### ISSUE TITLE
Error while running "make deploy" on OSX - El Capitan

### ISSUE THREAD

**Issue by Rushit** [kubernetes/kubernetes-anywhere#257]
` kubernetes-anywhere (master) $ make deploy`
`/Applications/Xcode.app/Contents/Developer/usr/bin/make config`
`CONFIG_="." kconfig-conf Kconfig`
`/bin/bash: kconfig-conf: command not found`
`make[1]: *** [config] Error 127`
`make: *** [.config] Error 2`

I am doing this very first time. Am I missing Anything? I am following these instructions - https://github.com/kubernetes/kubernetes-anywhere/blob/master/phase1/azure/README.md

**Comment by Rushit** [comment]
Proper tap was missing....Here is how you get rid of this message

`brew tap PX4/homebrew-px4`
`brew install kconfig-frontends`

**Comment by colemickens** [comment]
It's easier to just run `make docker-dev` first so you can run the deployment from an environment that has everything installed already.

**Comment by Rushit** [comment]
yes. that worked for me. It took me little while to learn that running `make deploy` inside docker (`make docker-dev`) is simpler.
