### ISSUE TITLE
API server build parameters in phase2

### ISSUE THREAD

**Issue by abrarshivani** [kubernetes/kubernetes-anywhere#264]
Shouldn't [api-server](https://github.com/kubernetes/kubernetes-anywhere/blob/master/phase2/ignition/vanilla/manifest/kube-apiserver.jsonnet#L29) bind to "0.0.0.0" instead of "127.0.0.1"?

**Comment by mikedanese** [comment]
This is correct. --address is an alias for --insecure-bind-address which listens on http without auth.

https://github.com/kubernetes/kubernetes/blob/master/pkg/genericapiserver/options/server_run_options.go#L358-L360
