### ISSUE TITLE
unable to execute kubectl exec on pod with nohup command 

### ISSUE THREAD

**Issue by fw0037** [kubernetes/kubernetes-anywhere#266]
my command is below:
kubectl exec -it c-engine-1613829755-v2bov -- nohup sh /home/webadmin/shell/deploy.sh 01 " COMMON_REST COMMON_DUBBO COMMERCE_REST COMMERCE_DUBBO" >/dev/null 2>&1 &

When I press the Enter key, & disappeared, the nohup command stopped and display error, how should I write to make it successful?

>>>[root@szxts10004464 logs]# kubectl exec -it c-service--4-2005015123-c8vsz -- nohup sh /home/webadmin/shell/deploy.sh 01 " COMMON_REST COMMON_DUBBO COMMERCE_REST COMMERCE_DUBBO"  >/dev/null 2>&1 &
>>>[1] 63616
>>>[root@szxts10004464 logs]# 
>>>
>>>[1]+  Stopped                 kubectl exec -it c-service--4-2005015123-c8vsz -- nohup sh /home/webadmin/shell/deploy.sh 01 " COMMON_REST COMMON_DUBBO COMMERCE_REST COMMERCE_DUBBO" > /dev/null 2>&1
>>>[root@szxts10004464 logs]# 
>>>[root@szxts10004464 logs]# 
>>>[root@szxts10004464 logs]# docker --version
>>>Docker version 1.12.1, build 23cf638
>>>[root@szxts10004464 logs]#

**Comment by fw0037** [comment]
when i use the python commands function to run this nohup command, the error is below:

>>> import commands
>>> podname="c-engine--1-0-1-1--common--ear-1613829755-v2bov"
>>> cmd="nohup sh -c /home/webadmin/shell/deploy.sh 01 'COMMON_REST COMMON_DUBBO COMMERCE_REST COMMERCE_DUBBO' >myout.file &"
>>> execcmd= "kubectl exec -it "+podname+" -- "+cmd+""
>>> status,returnval = commands.getstatusoutput(execcmd)
sh: -c: line 0: syntax error near unexpected token ';' 
sh: -c: line 0: `{ kubectl exec -it c-engine--1-0-1-1--common--ear-1613829755-v2bov -- nohup sh -c /home/webadmin/shell/deploy.sh 01 'COMMON_REST COMMON_DUBBO COMMERCE_REST COMMERCE_DUBBO' >myout.file &; } 2>&1'
>>> print status,returnval
256 
>>>

**Comment by colemickens** [comment]
This error is not related to this project in any way. It is not appropriate to spam this same Issue in 4+ different projects [as](https://github.com/kubernetes/kubernetes.github.io/issues/1588), [you](https://github.com/kubernetes/kubernetes/issues/35846), [have](https://github.com/kubernetes/minikube/issues/777), [done](https://github.com/kubernetes/kubernetes-anywhere/issues/266).

**Comment by colemickens** [comment]
I guess it was spammed to 7 different repos. As this is unrelated to `kubernetes-anywhere`, this Issue is being closed. (Further, you're having problems with your shell, your problem very likely has nothing at all to do with `kubernetes`.)
