### ISSUE TITLE
does not deploy containers on hosts

### ISSUE THREAD

**Issue by barrymac** [kubernetes/kubernetes-anywhere#269]
Phase 1 appears to have completed ok and then the script hangs on the validation step without making any further progress. Kubelets are not installed on the hosts. I used it with default target vm image, ubuntu 16.04 and also with CoreOs. When I ssh into the master host on Ubuntu there is no docker installed and in CoreOs there is no containers running. It appears to have an issue communicating with the hosts to complete the automation on the host side. I chose k8s version 1.4.5.  I also noticed that cloud init had failed to start on CoreOs with a command not found error. 

`k8soncore-master kube # systemctl status coreos-cloudinit-691521544
● coreos-cloudinit-691521544.service - Unit generated and executed by coreos-cloudinit on behalf of user
   Loaded: loaded (/run/systemd/transient/coreos-cloudinit-691521544.service; transient; vendor preset: disabled)
Transient: yes
   Active: failed (Result: exit-code) since Tue 2016-11-08 00:18:18 UTC; 10ms ago
  Process: 1805 ExecStart=/bin/bash /var/lib/coreos-cloudinit/scripts/691521544 (code=exited, status=127)
 Main PID: 1805 (code=exited, status=127)

Nov 08 00:18:18 k8soncore-master bash[1805]:   installation instructions:
Nov 08 00:18:18 k8soncore-master bash[1805]:     https://docs.docker.com/engine/installation/
Nov 08 00:18:18 k8soncore-master bash[1805]: + true
Nov 08 00:18:18 k8soncore-master bash[1805]: + systemctl start docker
Nov 08 00:18:18 k8soncore-master bash[1805]: Warning: docker.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Nov 08 00:18:18 k8soncore-master bash[1805]: + apt-get install -y jq
Nov 08 00:18:18 k8soncore-master bash[1805]: /var/lib/coreos-cloudinit/scripts/691521544: line 26: apt-get: command not found
Nov 08 00:18:18 k8soncore-master systemd[1]: coreos-cloudinit-691521544.service: Main process exited, code=exited, status=127/n/a
Nov 08 00:18:18 k8soncore-master systemd[1]: coreos-cloudinit-691521544.service: Unit entered failed state.
Nov 08 00:18:18 k8soncore-master systemd[1]: coreos-cloudinit-691521544.service: Failed with result 'exit-code'.
`

**Comment by barrymac** [comment]
on further investigation I found the following:

`journalctl --identifier=ignition --all `

`Nov 07 23:24:37 localhost ignition[507]: op(2): [started]  unmounting "/dev/disk/by-id/ata-Virtual_CD" at "/tmp/ignition-azure285863710"
Nov 07 23:24:37 localhost ignition[507]: op(2): [finished] unmounting "/dev/disk/by-id/ata-Virtual_CD" at "/tmp/ignition-azure285863710"
Nov 07 23:24:37 localhost ignition[507]: failed to fetch config: not a config (found coreos-cloudinit script)
Nov 07 23:24:37 localhost ignition[507]: not a config (found coreos-cloudinit script): ignoring user-provided config
`

**Comment by colemickens** [comment]
Is this on Azure? CoreOS isn't supported.

**Comment by colemickens** [comment]
The relevant log lines:

```
Nov 08 00:18:18 k8soncore-master bash[1805]: + apt-get install -y jq
Nov 08 00:18:18 k8soncore-master bash[1805]: /var/lib/coreos-cloudinit/scripts/691521544: line 26: apt-get: command not found
```

**Comment by barrymac** [comment]
Yes that was coreos, thanks for letting me know about support. With Ubuntu then docker was not installed however, with a similar result. will post what I can find out about that setup

**Comment by colemickens** [comment]
Sure. Please post the full log again and I'll take a look.

Alternatively, Kubernetes is now available in ACS and you can point/click in the portal to get a cluster running.

**Comment by barrymac** [comment]
Didn't know about ACS support, thanks for the reply. Is acs-engine likely to become the recommended Azure deployment strategy going forward?

**Comment by colemickens** [comment]
Yes. I'll be updating my status page to indicate that very soon.
