### ISSUE TITLE
Azure, issue with inter-pod communication

### ISSUE THREAD

**Issue by danhawkes** [kubernetes/kubernetes-anywhere#276]
Hi, I've been directed here from an issue with https://github.com/deis/workflow/issues/604.

> This looks like the underlying platform (kubernetes) is failing. I would submit a ticket to kubernetes-anywhere and see if they have any open issues related to this one.
```
Failed to setup network for pod 
\"dockerbuild-another-5d313d57-a3ef8932_deis(4d7a6cc8-aa5b-11e6-b9d9-000d3af76add)\" 
using network plugins \"kubenet\": Failed to retrieve pods from runtime: operation timeout: 
context deadline exceeded; Skipping pod"
```

There's some context in the linked issue, but unfortunately I'm new to kubernetes and not sure what typical debugging steps are. Any input would be appreciated. 

As a start, here's the output of `cluster-info dump`: 

[dump.txt](https://github.com/kubernetes/kubernetes-anywhere/files/596005/dump.txt)

(note, the output's truncated because the process seems to hang indefinitely at that point of getting logs)

**Comment by colemickens** [comment]
@mikedanese Do you have any idea what might be going on here?

@danhawkes Can you please tell me where the message came from that you've posted in this bug description? We've not had any other reports of pod networking issues in Azure so far.

**Comment by danhawkes** [comment]
@colemickens  Hi, thanks for the response.
The message is from the events section of `kubectl describe pod` in [this comment](https://github.com/deis/workflow/issues/604#issuecomment-260310304). Not sure of its provenance - can't find any reference to "Error syncing pod" in the `deis/deis` or `deis/workflow`, though it may have come from some other dependency.

**Comment by colemickens** [comment]
That error strikes me as `kubenet` trying to setup the network and first trying to ask `docker` about the running containers and failing to do so, but I'm sure about the internals of `kubenet`.

What size of VM was this cluster running?

**Comment by danhawkes** [comment]
@colemickens Hi, sorry for going silent on this. Ended up testing Deis on some other cloud and forgot all about it. 
Anyway, I'm afraid I've long since lost the details on this so will close this issue. Thanks for your time anyway.
