### ISSUE TITLE
Allow user to change the default password of the VM once the kubernetes cluster is up in vSphere

### ISSUE THREAD

**Issue by BaluDontu** [kubernetes/kubernetes-anywhere#294]
Currently, the default password for the nodes is "kubernetes" on a kubernetes cluster in vSphere.  After successful deployment the user doesn't have a way to change the default password on first login. 

It is better to make sure the root user is forced to change the default password after the first login so that no other user can login into this node other than the root user.

**Comment by davidchua** [comment]
Just an observation on this, I did not know that the default root password is `kubernetes`. On the OVA installation, the notice said that it was `changeme`. I had to search here to find that out.

**Comment by DekkerEdwin** [comment]
Same here... The OVA states the default password is changeme.
