### ISSUE TITLE
Change the default names of the nodes after a kubernetes cluster is deployed in vSphere

### ISSUE THREAD

**Issue by BaluDontu** [kubernetes/kubernetes-anywhere#295]
Currently, after a successful deployment of kubernetes cluster in vSphere, the master is named as "master" and the nodes are named as "node1", "node2" and so on.

It is better if we prefix the name of the nodes with kubernetes so that the user can identify this is a kubernetes cluster deployed in the vSphere. So the plan is to modify the default name of the nodes to

"kubernetes-master"
"kubernetes-worker-1"
"kubernetes-worker-2" etc.

**Comment by vmtocloud** [comment]
Also second this request, ability to be able to set the name prefix in the make config portion would be ideal!
