### ISSUE TITLE
Azure - Elasticsearch discovery mechanism incompatible with default settings

### ISSUE THREAD

**Issue by RossWilliams** [kubernetes/kubernetes-anywhere#298]
The blessed image for Elasticsearch seems to be https://github.com/pires/docker-elasticsearch-kubernetes
The instructions for setting up node discovery, and templates are here: https://github.com/pires/kubernetes-elasticsearch-cluster

Unfortunately, the default setup on Azure does not have components setup to run the discovery process correctly. Specifically, it appears that communication with kube-apiserver is not successful from the pods. It is using a service account to authenticate.

I'm not sure if this is a problem with the default configuration values, or if the pod is using non-standard techniques. Let me know if this isn't the right place to file this.

**Comment by colemickens** [comment]
I don't think that is the blessed method for setting up elasticsearch with kubernetes. That would be by using the upstream kube-addons elasticsearch from the kubernetes repo (in the cluster/ directory).

I've launched kibana/elasticsearch/fluentd on a kubernetes-anywhere cluster before and it worked fine.

Can you explain why you think the discovery mechanism is wrong? The dashboard, among other things, would flat out not work if the ServiceAccount or KubeDNS were not functioning properly.

**Comment by colemickens** [comment]
(for example, error messages that led you to believe it doesn't work would be helpful).

Also, you might want to check out [the Azure Container Service which now supports Kubernetes](https://docs.microsoft.com/en-us/azure/container-service/container-service-kubernetes-walkthrough). Or the open source heart of ACS, which is [ACS-Engine](https://github.com/Azure/acs-engine).

**Comment by pires** [comment]
If the default service account is not mounted in pod containers, you won't be able to query the API. If you need to use a specific service account, it should be as easy as changing the deployment descriptors to use said service account.

Now, as @colemickens said, no logs doesn't help us helping you.

**Comment by RossWilliams** [comment]
Sorry, should have posted to ACS-Engine repo. I'll post logs there.
Kubernetes' example cluster uses the same image, that's why I thought it was most popular.

**Comment by advishnuprasad** [comment]
@RossWilliams I am getting the same error. How did you fix the problem ? Did you create a different service account ?

**Comment by colemickens** [comment]
What error? There's no error message listed in this thread or the other.

**Comment by advishnuprasad** [comment]
Oops sorry. This is thread I am talking about. If you think it is unrelated please ignore.
https://github.com/pires/kubernetes-elasticsearch-cluster/issues/68

**Comment by colemickens** [comment]
I'll subscribe to that issue, but there's still nothing actionable. Let's keep the discussion over there for now unless we find the Azure error and we can open a new issue in the appropriate location.
