### ISSUE TITLE
kube-anywhere fails with "unexpected EOF" or "connection shut down" when photon OS template is not within the cluster

### ISSUE THREAD

**Issue by BaluDontu** [kubernetes/kubernetes-anywhere#300]
When trying to deploy a kubernetes on cluster A and datastore DS1 inside a VC, I observe the following 

1. uploading the photonOS template on "datastore DS2" on a different cluster say "cluster B" altogether is not working.
2. uploading the photonOS template on "datastore DS3" in the same cluster "clusterA" is working.

The deployment fails with errors "unexpected EOF", "connection shut down". Its because terraform crashes for vsphere plugin. However, I see this errors only after the kubernetes nodes are created sometimes (or) after powering on those kubernetes nodes. So this is not something related to that it couldn't find the template.

**Comment by datagen24** [comment]
+1 I am seeing the same failure. is there a solution?

**Comment by BaluDontu** [comment]
@datagen24 : Can you upload the photon OS template in the cluster itself?
Currently for terraform we have to give the current context where to search for this template. It is the same place where you deploy kubernetes cluster.

**Comment by datagen24** [comment]
The Photon os template is in the root of the cluster, Kubernets is being deployed into a folder called Kubernets.

Should i put the OVA in the folder?
--
Steven C. Peterson
Mainstream Technology Group
scp@mainstream.net
Office: (603)966-4607 x 2409
Cell/SMS: (603) 913-7006
Skype: datagen24
OpenPGP KeyID: CC16FE24 Fingerprint: 596A F093 33FF FEC3 7CC3  9E82 7099 D155 CC16 FE2
Digitally Signed CaCERT, more info at cacert.org

**Comment by BaluDontu** [comment]
You can deploy the OVA inside a valid Cluster, Host or Resource Pool in which you deploy ur Kubernetes VM's.

For example, if you want to deploy your kubernetes cluster inside a VSAN cluster. Then you need to deploy the OVA on a VSAN cluster.

If you plan to deploy your kubernetes cluster inside a ESX host. Then you need to deploy the OVA on a ESX host.

Also, you might have specified the resource pool while deploying the cluster.
Resource pool/cluster (same as destination for OVA import). (phase1.vSphere.resourcepool) [] (NEW) - xxx
This should be same place where you might want to deploy your resource pool.

**Comment by datagen24** [comment]
I may have figured out the issue on my side,  it appears that the password string is not properly escaped, I use randomly generated passwords with no restrictions on the upper ASCII. 
I captured an area where I think this happened. 

As a test, I created a new user gave it admin rights with no upper ASCII and it all worked.

I have a section of the screen where it died it includes passwords and other sensitive info so I can not post the log to the github, if someone would reach out to me via private message i will send it along.

**Comment by BaluDontu** [comment]
So this password is a VC password? U can email me at bdontu@vmware.com. I can take a look.

**Comment by datagen24** [comment]
Sent

**Comment by BaluDontu** [comment]
If you pass the full template Path, you can deploy a kubernetes cluster successfully even though the template is not in the current cluster.
