### ISSUE TITLE
Correct value for MountFlags

### ISSUE THREAD

**Issue by edevil** [kubernetes/kubernetes-anywhere#304]
I'm following the CoreOS guide and merging with this one for Azure cloudprovider specific sttuff. However, they differ in the value of the MountFlags variable in the Docker drop-in, so I'm not really sure which value to use.

In the [CoreOS](https://github.com/coreos/coreos-kubernetes/blob/master/Documentation/deploy-master.md) guide no value is given for MountFlags, while in [this](https://github.com/kubernetes/kubernetes-anywhere/blob/55737c3818549f06f3af074f8d71b727568c00f2/phase1/azure/configure-vm.sh) guide the "shared" value is used. I think this makes sense since kubelet is run inside a Docker container and we want Azure mounted volumes to be available to other pods, but in the CoreOS setup kubelet is run inside a rkt container, not Docker. Can this be reason for the difference?

The default value used to be slave: https://github.com/docker/docker/commit/2aee081cad72352f8b0c37ba0414ebc925b022e8

Thanks.

**Comment by mikedanese** [comment]
Shared is required for the iginition phase 2 because kubelet is running in a container.

**Comment by edevil** [comment]
Ah, I see. Thank you @mikedanese  for the insight. So, in my case, as I'm running kubelet in a rkt container and using ansible for the host configuration (not in a container), should I use "slave" or just never specify the option at all?

**Comment by mikedanese** [comment]
Either should be fine.

**Comment by edevil** [comment]
Thanks!
