### ISSUE TITLE
vSphere: Increase size of image and include instructions for configuring the template OS ova

### ISSUE THREAD

**Issue by kerneltime** [kubernetes/kubernetes-anywhere#309]
The current size of the image used for vSphere is pretty small and there are no instructions available as how can it be customized

- [ ] Include steps for how to generate the image using base Photon OS image

- [ ] Documentation for customizations

- [ ] Increase the size of the default image and make it thin provisioned.

**Comment by stefanhdao** [comment]
I needed to resize my partition so what I did was power on the base Photon OS image and follow the following instructions to resize:

http://unix.stackexchange.com/questions/134796/how-to-increase-size-of-dev-sda2-in-suse-running-on-vmware

Basically you want to run the following:
`tdnf install parted`
`parted /dev/sda`
`resizepart` (Enter in your values here)
`resize2fs /dev/sda2`

`df -h` to confirm your changes were successful

Then at the very end, run `echo -n > /etc/machine-id`

**Comment by kerneltime** [comment]
@stefanhdao if you want you can open an PR with the steps on the vsphere documentation markdown file.

**Comment by stefanhdao** [comment]
Sure, I'm still verifying 100% that it works (confirmed by `df -h` so far) but wanted to run a few builds just to make sure
