### ISSUE TITLE
Get TLS certs from Amazon Certificate Manager

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes-anywhere#31]
It should be pretty doable actually. We should be able to transparently fetch certs from the ACM API when tools config container is ran.

**Comment by myoung34** [comment]
You can't use acm for non aws services. 

https://aws.amazon.com/certificate-manager/faqs/

```
Q: Can I use certificates on Amazon EC2 instances or on my own servers?

No. At this time, certificates provided by ACM can only be used with specific AWS services. See With which AWS services can I use certificates provided by ACM?.
```

**Comment by myoung34** [comment]
Fyi You'd want to use let's encrypt
