### ISSUE TITLE
make deploy fails on "* data.tls_cert_request.kubernetes-master: unexpected EOF"

### ISSUE THREAD

**Issue by thakala** [kubernetes/kubernetes-anywhere#312]
I have had one successful Kubernetes deployment on vSphere 6. I removed it with "make destroy" and tried to redeploy but it is now failing on TLS error. Configuration is still set to allow self signed certificates.

[container]:/opt/kubernetes-anywhere> make clean
rm -rf .tmp
rm -rf phase3/.tmp
rm -rf phase1/gce/.tmp
rm -rf phase1/azure/.tmp
rm -rf phase1/vsphere/.tmp

[container]:/opt/kubernetes-anywhere> make deploy
util/config_to_json .config > .config.json
make do WHAT=deploy-cluster
make[1]: Entering directory '/opt/kubernetes-anywhere'
( cd "phase1/$(jq -r '.phase1.cloud_provider' .config.json)"; ./do deploy-cluster )
.tmp/vSphere-kubernetes.tf
data.template_file.cloudprovider: Refreshing state...
tls_private_key.kubernetes-root: Creating...
  algorithm:          "" => "RSA"
  ecdsa_curve:        "" => "P224"
  private_key_pem:    "" => "<computed>"
  public_key_openssh: "" => "<computed>"
  public_key_pem:     "" => "<computed>"
  rsa_bits:           "" => "2048"
tls_private_key.kubernetes-node: Creating...
  algorithm:          "" => "RSA"
  ecdsa_curve:        "" => "P224"
  private_key_pem:    "" => "<computed>"
  public_key_openssh: "" => "<computed>"
  public_key_pem:     "" => "<computed>"
  rsa_bits:           "" => "2048"
tls_private_key.kubernetes-master: Creating...
  algorithm:          "" => "RSA"
  ecdsa_curve:        "" => "P224"
  private_key_pem:    "" => "<computed>"
  public_key_openssh: "" => "<computed>"
  public_key_pem:     "" => "<computed>"
  rsa_bits:           "" => "2048"
tls_private_key.kubernetes-admin: Creating...
  algorithm:          "" => "RSA"
  ecdsa_curve:        "" => "P224"
  private_key_pem:    "" => "<computed>"
  public_key_openssh: "" => "<computed>"
  public_key_pem:     "" => "<computed>"
  rsa_bits:           "" => "2048"
vsphere_folder.cluster_folder: Creating...
  datacenter:    "" => "Derby"
  existing_path: "" => "<computed>"
  path:          "" => "kubernetes"
vsphere_folder.cluster_folder: Creation complete
vsphere_virtual_machine.kubevm1: Creating...
..
..
vsphere_virtual_machine.kubevm5: Still creating... (2m10s elapsed)
vsphere_virtual_machine.kubevm4: Still creating... (2m10s elapsed)
vsphere_virtual_machine.kubevm2: Still creating... (2m10s elapsed)
vsphere_virtual_machine.kubevm5: Still creating... (2m20s elapsed)
vsphere_virtual_machine.kubevm4: Still creating... (2m20s elapsed)
vsphere_virtual_machine.kubevm2: Still creating... (2m20s elapsed)
vsphere_virtual_machine.kubevm2: Creation complete
vsphere_virtual_machine.kubevm4: Creation complete
vsphere_virtual_machine.kubevm5: Creation complete
Error applying plan:

1 error(s) occurred:

* data.tls_cert_request.kubernetes-master: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
Makefile:63: recipe for target 'do' failed
make[1]: *** [do] Error 1
make[1]: Leaving directory '/opt/kubernetes-anywhere'
Makefile:41: recipe for target 'deploy-cluster' failed
make: *** [deploy-cluster] Error 2
[container]:/opt/kubernetes-anywhere>

**Comment by adtrsa** [comment]
Encountered exact same error (data.tls_cert_request... : unexpected EOF) with self-signed host certificate option enabled.

VMs are created but cluster setup incomplete.

Using vSphere 6.0 and latest version of kubernetes-anywhere.

**Comment by adtrsa** [comment]
vsphere_virtual_machine.kubevm2: Creation complete
Error applying plan:

1 error(s) occurred:

* data.tls_cert_request.cluster-master: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
panic: interface conversion: interface is nil, not string
2017/01/17 13:54:48 [DEBUG] plugin: terraform: 
2017/01/17 13:54:48 [DEBUG] plugin: terraform: goroutine 103 [running]:
2017/01/17 13:54:48 [DEBUG] plugin: terraform: panic(0x2876840, 0xc42045b2c0)
2017/01/17 13:54:48 [DEBUG] plugin: terraform: 	/opt/go/src/runtime/panic.go:500 +0x1a1
2017/01/17 13:54:48 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/tls.ReadCertRequest(0xc420428420, 0x0, 0x0, 0x28, 0xc4204308f1)
2017/01/17 13:54:48 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/tls/data_source_cert_request.go:94 +0x448
2017/01/17 13:54:48 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Resource).ReadDataApply(0xc420316ba0, 0xc420614100, 0x0, 0x0, 0xc42031acb8, 0x1, 0x18)
2017/01/17 13:54:48 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:207 +0xda
2017/01/17 13:54:48 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provider).ReadDataApply(0xc4203beb70, 0xc42045a100, 0xc420614100, 0x0, 0x0, 0x0)
2017/01/17 13:54:48 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:315 +0x91
2017/01/17 13:54:48 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).ReadDataApply(0xc4203197c0, 0xc42049c0b0, 0xc42049c320, 0x0, 0x0)
2017/01/17 13:54:48 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:537 +0x4e
2017/01/17 13:54:48 [DEBUG] plugin: terraform: reflect.Value.call(0xc4203b45a0, 0xc4203d8088, 0x13, 0x2da4800, 0x4, 0xc4204a1ed0, 0x3, 0x3, 0xc, 0xc, ...)
2017/01/17 13:54:48 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:434 +0x5c8
2017/01/17 13:54:48 [DEBUG] plugin: terraform: reflect.Value.Call(0xc4203b45a0, 0xc4203d8088, 0x13, 0xc4204a1ed0, 0x3, 0x3, 0x180002, 0x0, 0x0)
2017/01/17 13:54:48 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:302 +0xa4
2017/01/17 13:54:48 [DEBUG] plugin: terraform: net/rpc.(*service).call(0xc420458b00, 0xc420458ac0, 0xc420430d38, 0xc4203ce400, 0xc4201fab40, 0x255f880, 0xc42049c0b0, 0x16, 0x255f8c0, 0xc42049c320, ...)
2017/01/17 13:54:48 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:383 +0x148
2017/01/17 13:54:48 [DEBUG] plugin: terraform: created by net/rpc.(*Server).ServeCodec
2017/01/17 13:54:48 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:477 +0x421
2017/01/17 13:54:48 [DEBUG] plugin: /bin/terraform: plugin process exited
2017/01/17 13:54:48 [ERROR] root: eval: *terraform.EvalReadDataApply, err: data.tls_cert_request.cluster-master: unexpected EOF
2017/01/17 13:54:48 [ERROR] root: eval: *terraform.EvalSequence, err: data.tls_cert_request.cluster-master: unexpected EOF
2017/01/17 13:54:48 [ERROR] root: eval: *terraform.EvalOpFilter, err: data.tls_cert_request.cluster-master: unexpected EOF
2017/01/17 13:54:48 [ERROR] root: eval: *terraform.EvalSequence, err: data.tls_cert_request

**Comment by adtrsa** [comment]
Still getting this crash.  Updated to latest master, using v1.4.8 kubernetes (as recommended for vsphere provider) etc.  If self-signed option is selected for host, why is 
data.tls_cert_request.kubernetes-master necessary? Or is this when an attempt is made to retrieve the master cert? Currently resorting to running terraform 0.7.2 in dlv to try and debug what's up.

**Comment by stefanhdao** [comment]
I solved this by deleting the VM from the OVA template and re-adding it to vsphere. Not sure why that made a difference.

**Comment by abrarshivani** [comment]
@adtrsa @stefanhdao @thakala Were you able to destroy cluster successfully?

**Comment by stefanhdao** [comment]
@abrarshivani Here and there. Sometimes running `make destroy` destroyed the cluster successfully. Other times I had to intervene and remove the VMs from vsphere myself in order for `make destroy` to succeed.

**Comment by abrarshivani** [comment]
@stefanhdao Yes that is know [issue](https://github.com/kubernetes/kubernetes-anywhere/issues/285). You found this issue when you manually deleted the VMs or when the ```make destroy``` worked fine?

**Comment by stefanhdao** [comment]
@abrarshivani I don't remember the exact build up to this issue. It happened after several iterations of doing `make destroy` which involved both manually deleting and `make destroy` completing all the way through.

**Comment by kerneltime** [comment]
@stefanhdao from what we have seen if the cloned VM do not have an IP address the deployment fails.

**Comment by wkrapohl** [comment]
Any updates on this issue. I can't seem to get by this problem using kubernetes-anywhere?

**Comment by alejdg** [comment]
I'm in the same situation as @wkrapohl. I tried all the alternatives mentioned here but none could make the deploy work.

**Comment by aaron-comyn** [comment]
Same issue here, having little luck getting past it.

We are installing on a single host and using self-signed certificates (ie insecure mode).


tls_cert_request.kubernetes-master: Creating...
  cert_request_pem:       "" => "<computed>"
  dns_names.#:            "" => "6"
  dns_names.0:            "" => "kubernetes-master"
  dns_names.1:            "" => "kubernetes"
  dns_names.2:            "" => "kubernetes.default"
  dns_names.3:            "" => "kubernetes.default.svc"
  dns_names.4:            "" => "kubernetes.default.svc.local"
  dns_names.5:            "" => "kubernetes.default.svc.local"
  ip_addresses.#:         "" => "2"
  ip_addresses.1:         "" => "10.0.0.1"
  key_algorithm:          "" => "RSA"
  private_key_pem:        "" => "9fcbcd82dc148cc5c2bacc804080c2518eed1947"
  subject.#:              "" => "1"
  subject.0.common_name:  "" => "kubernetes-master_certificate"
  subject.0.organization: "" => "kubernetes-anywhere"
Error applying plan:

1 error(s) occurred:

* tls_cert_request.kubernetes-master: 1 error(s) occurred:

* tls_cert_request.kubernetes-master: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
panic: interface conversion: interface {} is nil/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/tls/res
ource_cert_request.go:101 +0x80din: terraform:
2017/09/06 09:01:48 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc42025fd
a0, 0xc420225040, 0xc4202362a0, 0x0, 0x0, 0x1, 0x28, 0xc4206dd020)p/terraform/builtin/providers/tls.CreateCertRequest(0x
2017/09/06 09:01:48 [DEBUG] plugin: terraform:  /opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go
:186 +0x48d09:01:48 [DEBUG] plugin: terraform:  /opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go
:242 +0x9b 09:01:48 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc42021fd
2017/09/06 09:01:48 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc
4206142c0, 0xc4202361c0, 0xc4204f8690, 0x0, 0x0)/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.
go:488 +0x579:01:48 [DEBUG] plugin: terraform:  /opt/go/src/reflect/value.go:434 +0x91f
2017/09/06 09:01:48 [DEBUG] plugin: terraform: reflect.Value.Call(0xc4203f6180, 0xc420457bd0, 0x13, 0xc420659f20, 0x3, 0
x3, 0x0, 0x0, 0xc4200166c0)0, ...)
2017/09/06 09:01:48 [DEBUG] plugin: terraform:  /opt/go/src/net/rpc/server.go:387 +0x144
2017/09/06 09:01:48 [DEBUG] plugin: terraform: created by net/rpc.(*Server).ServeCodecxc42060e6c0, 0xc4206127c8, 0xc4203
2017/09/06 09:01:48 [DEBUG] plugin: terraform: x/opt/go/src/net/rpc/server.go:481 +0x404
2017/09/06 09:01:48 [DEBUG] root: eval: *terraform.EvalWriteState
2017/09/06 09:01:48 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2017/09/06 09:01:48 [DEBUG] root: eval: *terraform.EvalIf
2017/09/06 09:01:48 [DEBUG] root: eval: *terraform.EvalWriteState
2017/09/06 09:01:48 [DEBUG] root: eval: *terraform.EvalWriteDiff
2017/09/06 09:01:48 [DEBUG] root: eval: *terraform.EvalApplyPost
2017/09/06 09:01:48 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* tls_cert_request.kubernetes-master: unexpected EOF
2017/09/06 09:01:48 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* tls_cert_request.kubernetes-master: unexpected EOF
2017/09/06 09:01:48 [TRACE] [walkApply] Exiting eval tree: tls_cert_request.kubernetes-master
2017/09/06 09:01:48 [DEBUG] dag/walk: upstream errored, not walking "tls_locally_signed_cert.kubernetes-master"
2017/09/06 09:01:48 [DEBUG] dag/walk: upstream errored, not walking "provider.tls (close)"
2017/09/06 09:01:48 [DEBUG] dag/walk: upstream errored, not walking "data.template_file.configure_master"
2017/09/06 09:01:48 [DEBUG] dag/walk: upstream errored, not walking "null_resource.master"
2017/09/06 09:01:48 [DEBUG] dag/walk: upstream errored, not walking "provisioner.local-exec (close)"
2017/09/06 09:01:48 [DEBUG] dag/walk: upstream errored, not walking "data.template_file.configure_node"
2017/09/06 09:01:48 [DEBUG] dag/walk: upstream errored, not walking "null_resource.node2"
2017/09/06 09:01:48 [DEBUG] dag/walk: upstream errored, not walking "null_resource.node5"
2017/09/06 09:01:48 [DEBUG] dag/walk: upstream errored, not walking "null_resource.node3"
2017/09/06 09:01:48 [DEBUG] dag/walk: upstream errored, not walking "provider.template (close)"
2017/09/06 09:01:48 [DEBUG] dag/walk: upstream errored, not walking "null_resource.node4"
2017/09/06 09:01:48 [DEBUG] dag/walk: upstream errored, not walking "provider.null (close)"
2017/09/06 09:01:48 [DEBUG] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2017/09/06 09:01:48 [DEBUG] dag/walk: upstream errored, not walking "provisioner.remote-exec (close)"
2017/09/06 09:01:48 [DEBUG] dag/walk: upstream errored, not walking "root"
2017/09/06 09:01:48 [TRACE] Preserving existing state lineage "83109a07-9186-41d4-a56f-bcfe9882fa76"
2017/09/06 09:01:48 [DEBUG] plugin: /bin/terraform: plugin process exited
2017/09/06 09:01:48 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/09/06 09:01:48 [DEBUG] plugin: terraform: null-provider (internal) 2017/09/06 09:01:48 [DEBUG] plugin: waiting for
all plugin processes to complete...
2017/09/06 09:01:48 [WARN] plugin: error closing client during Kill: connection is shut down
2017/09/06 09:01:48 [DEBUG] plugin: terraform: template-provider (internal) 2017/09/06 09:01:48 [DEBUG] plugin: waiting
for all plugin processes to complete...
2017/09/06 09:01:48 [DEBUG] plugin: terraform: local-exec-provisioner (internal) 2017/09/06 09:01:48 [DEBUG] plugin: wai
ting for all plugin processes to complete...
2017/09/06 09:01:48 [DEBUG] plugin: terraform: remote-exec-provisioner (internal) 2017/09/06 09:01:48 [DEBUG] plugin: wa
iting for all plugin processes to complete...
2017/09/06 09:01:48 [DEBUG] plugin: /bin/terraform: plugin process exited
2017/09/06 09:01:48 [DEBUG] plugin: /bin/terraform: plugin process exited
2017/09/06 09:01:48 [DEBUG] plugin: terraform: vsphere-provider (internal) 2017/09/06 09:01:48 [DEBUG] plugin: waiting f
or all plugin processes to complete...
2017/09/06 09:01:48 [DEBUG] plugin: /bin/terraform: plugin process exited
2017/09/06 09:01:48 [DEBUG] plugin: /bin/terraform: plugin process exited
2017/09/06 09:01:48 [DEBUG] plugin: /bin/terraform: plugin process exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by phimic** [comment]
Any updates about this issue? I never could build the kubernetes cluster with kubernetes-anywhere, my error is 

```
tls_cert_request.kubernetes-master: 1 error(s) occurred:
tls_cert_request.kubernetes-master: unexpected EOF
```
VMware vSphere 6U3 with latest VCSA build (7462485)
