### ISSUE TITLE
VSphere Failed to start Kubernetes Kubelet Server

### ISSUE THREAD

**Issue by upendrasahu** [kubernetes/kubernetes-anywhere#316]
root@photon-zv1KbtvMG [ ~ ]# journalctl -u kubelet
-- Logs begin at Tue 2017-01-17 10:31:08 UTC, end at Tue 2017-01-17 11:25:17 UTC. --
Jan 17 10:32:14 photon-zv1KbtvMG systemd[1]: Starting Kubernetes Kubelet Server...
Jan 17 10:32:14 photon-zv1KbtvMG systemd[1]: Started Kubernetes Kubelet Server.
Jan 17 10:32:14 photon-zv1KbtvMG docker[735]: Unable to find image 'gcr.io/google-containers/hyperkube-amd64:v1.4.7' locally
Jan 17 10:32:15 photon-zv1KbtvMG docker[735]: v1.4.7: Pulling from google-containers/hyperkube-amd64
Jan 17 10:32:15 photon-zv1KbtvMG docker[735]: 386a066cd84a: Pulling fs layer
Jan 17 10:32:15 photon-zv1KbtvMG docker[735]: c3d846c7ae5a: Pulling fs layer
Jan 17 10:32:15 photon-zv1KbtvMG docker[735]: 0be0d8e6181f: Pulling fs layer
Jan 17 10:32:15 photon-zv1KbtvMG docker[735]: fa2a0296b51e: Pulling fs layer
Jan 17 10:32:15 photon-zv1KbtvMG docker[735]: 3bed2e6f9b4b: Pulling fs layer
Jan 17 10:32:15 photon-zv1KbtvMG docker[735]: 88b87718c8bc: Pulling fs layer
Jan 17 10:32:15 photon-zv1KbtvMG docker[735]: ad569c29c6d9: Pulling fs layer
Jan 17 10:32:15 photon-zv1KbtvMG docker[735]: 0b137deb028d: Pulling fs layer
Jan 17 10:32:15 photon-zv1KbtvMG docker[735]: 1546671cc328: Pulling fs layer
Jan 17 10:32:15 photon-zv1KbtvMG docker[735]: 37f0af6ff931: Pulling fs layer
Jan 17 10:32:15 photon-zv1KbtvMG docker[735]: bceffa791df4: Pulling fs layer
Jan 17 10:32:15 photon-zv1KbtvMG docker[735]: 7410e97eb86f: Pulling fs layer
Jan 17 10:32:15 photon-zv1KbtvMG docker[735]: 88b87718c8bc: Waiting
Jan 17 10:32:15 photon-zv1KbtvMG docker[735]: ad569c29c6d9: Waiting
Jan 17 10:32:15 photon-zv1KbtvMG docker[735]: 0b137deb028d: Waiting
Jan 17 10:32:15 photon-zv1KbtvMG docker[735]: 1546671cc328: Waiting
Jan 17 10:32:15 photon-zv1KbtvMG docker[735]: 37f0af6ff931: Waiting
Jan 17 10:32:15 photon-zv1KbtvMG docker[735]: bceffa791df4: Waiting
Jan 17 10:32:15 photon-zv1KbtvMG docker[735]: 7410e97eb86f: Waiting
Jan 17 10:32:15 photon-zv1KbtvMG docker[735]: fa2a0296b51e: Waiting
Jan 17 10:32:15 photon-zv1KbtvMG docker[735]: 3bed2e6f9b4b: Waiting
Jan 17 10:32:15 photon-zv1KbtvMG docker[735]: 0be0d8e6181f: Verifying Checksum
Jan 17 10:32:15 photon-zv1KbtvMG docker[735]: 0be0d8e6181f: Download complete
Jan 17 10:32:28 photon-zv1KbtvMG docker[735]: fa2a0296b51e: Verifying Checksum
Jan 17 10:32:28 photon-zv1KbtvMG docker[735]: fa2a0296b51e: Download complete
Jan 17 10:32:28 photon-zv1KbtvMG docker[735]: 3bed2e6f9b4b: Verifying Checksum
Jan 17 10:32:28 photon-zv1KbtvMG docker[735]: 3bed2e6f9b4b: Download complete
Jan 17 10:32:29 photon-zv1KbtvMG docker[735]: 88b87718c8bc: Verifying Checksum
Jan 17 10:32:29 photon-zv1KbtvMG docker[735]: 88b87718c8bc: Download complete
Jan 17 10:32:29 photon-zv1KbtvMG docker[735]: ad569c29c6d9: Verifying Checksum
Jan 17 10:32:29 photon-zv1KbtvMG docker[735]: ad569c29c6d9: Download complete
Jan 17 10:32:29 photon-zv1KbtvMG docker[735]: 0b137deb028d: Verifying Checksum
Jan 17 10:32:29 photon-zv1KbtvMG docker[735]: 0b137deb028d: Download complete
Jan 17 10:32:30 photon-zv1KbtvMG docker[735]: 1546671cc328: Verifying Checksum
Jan 17 10:32:30 photon-zv1KbtvMG docker[735]: 1546671cc328: Download complete
Jan 17 10:32:33 photon-zv1KbtvMG docker[735]: 386a066cd84a: Verifying Checksum
Jan 17 10:32:33 photon-zv1KbtvMG docker[735]: 386a066cd84a: Download complete
Jan 17 10:32:33 photon-zv1KbtvMG docker[735]: bceffa791df4: Verifying Checksum
Jan 17 10:32:33 photon-zv1KbtvMG docker[735]: bceffa791df4: Download complete
Jan 17 10:32:34 photon-zv1KbtvMG docker[735]: 7410e97eb86f: Verifying Checksum
Jan 17 10:32:34 photon-zv1KbtvMG docker[735]: 7410e97eb86f: Download complete
Jan 17 10:32:36 photon-zv1KbtvMG docker[735]: 37f0af6ff931: Verifying Checksum
Jan 17 10:32:36 photon-zv1KbtvMG docker[735]: 37f0af6ff931: Download complete
Jan 17 10:32:38 photon-zv1KbtvMG docker[735]: 386a066cd84a: Pull complete
Jan 17 10:32:39 photon-zv1KbtvMG docker[735]: c3d846c7ae5a: Verifying Checksum
Jan 17 10:32:39 photon-zv1KbtvMG docker[735]: c3d846c7ae5a: Download complete
Jan 17 10:32:46 photon-zv1KbtvMG docker[735]: c3d846c7ae5a: Pull complete
Jan 17 10:32:47 photon-zv1KbtvMG docker[735]: 0be0d8e6181f: Pull complete
Jan 17 10:32:51 photon-zv1KbtvMG docker[735]: fa2a0296b51e: Pull complete
Jan 17 10:32:52 photon-zv1KbtvMG docker[735]: 3bed2e6f9b4b: Pull complete
Jan 17 10:32:52 photon-zv1KbtvMG docker[735]: 88b87718c8bc: Pull complete
Jan 17 10:32:52 photon-zv1KbtvMG docker[735]: ad569c29c6d9: Pull complete
Jan 17 10:32:53 photon-zv1KbtvMG docker[735]: 0b137deb028d: Pull complete
Jan 17 10:32:54 photon-zv1KbtvMG docker[735]: 1546671cc328: Pull complete
Jan 17 10:32:55 photon-zv1KbtvMG docker[735]: 37f0af6ff931: Pull complete
Jan 17 10:32:56 photon-zv1KbtvMG docker[735]: bceffa791df4: Pull complete
Jan 17 10:32:57 photon-zv1KbtvMG docker[735]: 7410e97eb86f: Pull complete
Jan 17 10:32:57 photon-zv1KbtvMG docker[735]: Digest: sha256:ea917942c2b69cdabb2430e67e06c6b7522f992f4882c971a8af9670284b0190
Jan 17 10:32:57 photon-zv1KbtvMG docker[735]: Status: Downloaded newer image for gcr.io/google-containers/hyperkube-amd64:v1.4.7
Jan 17 10:32:57 photon-zv1KbtvMG docker[735]: Flag --config has been deprecated, Use --pod-manifest-path instead. Will be removed in a future version.
Jan 17 10:32:57 photon-zv1KbtvMG docker[735]: Flag --api-servers has been deprecated, Use --kubeconfig instead. Will be removed in a future version.
Jan 17 10:32:57 photon-zv1KbtvMG docker[735]: F0117 10:32:57.407126     846 plugins.go:80] Couldn't open cloud provider configuration /etc/kubernetes/vsphere.conf: &os.PathError{Op:"open
", Path:"/etc/kubernetes/vsphere.conf", Err:0x2}
Jan 17 10:32:57 photon-zv1KbtvMG systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Jan 17 10:32:57 photon-zv1KbtvMG systemd[1]: kubelet.service: Unit entered failed state.
Jan 17 10:32:57 photon-zv1KbtvMG systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jan 17 10:32:57 photon-zv1KbtvMG systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Jan 17 10:32:57 photon-zv1KbtvMG systemd[1]: Stopped Kubernetes Kubelet Server.
Jan 17 10:32:57 photon-zv1KbtvMG systemd[1]: Starting Kubernetes Kubelet Server...
Jan 17 10:32:57 photon-zv1KbtvMG systemd[1]: Started Kubernetes Kubelet Server.
Jan 17 10:32:57 photon-zv1KbtvMG docker[887]: Flag --config has been deprecated, Use --pod-manifest-path instead. Will be removed in a future version.
Jan 17 10:32:57 photon-zv1KbtvMG docker[887]: Flag --api-servers has been deprecated, Use --kubeconfig instead. Will be removed in a future version.
Jan 17 10:32:57 photon-zv1KbtvMG docker[887]: F0117 10:32:57.880972     914 plugins.go:80] Couldn't open cloud provider configuration /etc/kubernetes/vsphere.conf: &os.PathError{Op:"open
", Path:"/etc/kubernetes/vsphere.conf", Err:0x2}
Jan 17 10:32:57 photon-zv1KbtvMG systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Jan 17 10:32:57 photon-zv1KbtvMG systemd[1]: kubelet.service: Unit entered failed state.
Jan 17 10:32:57 photon-zv1KbtvMG systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jan 17 10:32:58 photon-zv1KbtvMG systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Jan 17 10:32:58 photon-zv1KbtvMG systemd[1]: Stopped Kubernetes Kubelet Server.
Jan 17 10:32:58 photon-zv1KbtvMG systemd[1]: Starting Kubernetes Kubelet Server...
Jan 17 10:32:58 photon-zv1KbtvMG systemd[1]: Started Kubernetes Kubelet Server.
Jan 17 10:32:58 photon-zv1KbtvMG docker[954]: Flag --config has been deprecated, Use --pod-manifest-path instead. Will be removed in a future version.
Jan 17 10:32:58 photon-zv1KbtvMG docker[954]: Flag --api-servers has been deprecated, Use --kubeconfig instead. Will be removed in a future version.
Jan 17 10:32:58 photon-zv1KbtvMG docker[954]: F0117 10:32:58.372526     980 plugins.go:80] Couldn't open cloud provider configuration /etc/kubernetes/vsphere.conf: &os.PathError{Op:"open
", Path:"/etc/kubernetes/vsphere.conf", Err:0x2}
Jan 17 10:32:58 photon-zv1KbtvMG systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Jan 17 10:32:58 photon-zv1KbtvMG systemd[1]: kubelet.service: Unit entered failed state.
Jan 17 10:32:58 photon-zv1KbtvMG systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jan 17 10:32:58 photon-zv1KbtvMG systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Jan 17 10:32:58 photon-zv1KbtvMG systemd[1]: Stopped Kubernetes Kubelet Server.
Jan 17 10:32:58 photon-zv1KbtvMG systemd[1]: Starting Kubernetes Kubelet Server...
Jan 17 10:32:58 photon-zv1KbtvMG systemd[1]: Started Kubernetes Kubelet Server.
Jan 17 10:32:58 photon-zv1KbtvMG docker[1022]: Flag --config has been deprecated, Use --pod-manifest-path instead. Will be removed in a future version.
Jan 17 10:32:58 photon-zv1KbtvMG docker[1022]: Flag --api-servers has been deprecated, Use --kubeconfig instead. Will be removed in a future version.
Jan 17 10:32:58 photon-zv1KbtvMG docker[1022]: F0117 10:32:58.876802    1047 plugins.go:80] Couldn't open cloud provider configuration /etc/kubernetes/vsphere.conf: &os.PathError{Op:"ope
n", Path:"/etc/kubernetes/vsphere.conf", Err:0x2}
Jan 17 10:32:58 photon-zv1KbtvMG systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Jan 17 10:32:58 photon-zv1KbtvMG systemd[1]: kubelet.service: Unit entered failed state.
Jan 17 10:32:58 photon-zv1KbtvMG systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jan 17 10:32:59 photon-zv1KbtvMG systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Jan 17 10:32:59 photon-zv1KbtvMG systemd[1]: Stopped Kubernetes Kubelet Server.
Jan 17 10:32:59 photon-zv1KbtvMG systemd[1]: Starting Kubernetes Kubelet Server...
Jan 17 10:32:59 photon-zv1KbtvMG systemd[1]: Started Kubernetes Kubelet Server.
Jan 17 10:32:59 photon-zv1KbtvMG docker[1091]: Flag --config has been deprecated, Use --pod-manifest-path instead. Will be removed in a future version.
Jan 17 10:32:59 photon-zv1KbtvMG docker[1091]: Flag --api-servers has been deprecated, Use --kubeconfig instead. Will be removed in a future version.
Jan 17 10:32:59 photon-zv1KbtvMG docker[1091]: F0117 10:32:59.396996    1115 plugins.go:80] Couldn't open cloud provider configuration /etc/kubernetes/vsphere.conf: &os.PathError{Op:"ope
n", Path:"/etc/kubernetes/vsphere.conf", Err:0x2}
Jan 17 10:32:59 photon-zv1KbtvMG systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Jan 17 10:32:59 photon-zv1KbtvMG systemd[1]: kubelet.service: Unit entered failed state.
Jan 17 10:32:59 photon-zv1KbtvMG systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jan 17 10:32:59 photon-zv1KbtvMG systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Jan 17 10:32:59 photon-zv1KbtvMG systemd[1]: Stopped Kubernetes Kubelet Server.
Jan 17 10:32:59 photon-zv1KbtvMG systemd[1]: Starting Kubernetes Kubelet Server...
Jan 17 10:32:59 photon-zv1KbtvMG systemd[1]: Started Kubernetes Kubelet Server.
Jan 17 10:32:59 photon-zv1KbtvMG docker[1157]: Flag --config has been deprecated, Use --pod-manifest-path instead. Will be removed in a future version.
Jan 17 10:32:59 photon-zv1KbtvMG docker[1157]: Flag --api-servers has been deprecated, Use --kubeconfig instead. Will be removed in a future version.
Jan 17 10:32:59 photon-zv1KbtvMG docker[1157]: F0117 10:32:59.889406    1180 plugins.go:80] Couldn't open cloud provider configuration /etc/kubernetes/vsphere.conf: &os.PathError{Op:"ope
n", Path:"/etc/kubernetes/vsphere.conf", Err:0x2}
Jan 17 10:32:59 photon-zv1KbtvMG systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Jan 17 10:32:59 photon-zv1KbtvMG systemd[1]: kubelet.service: Unit entered failed state.
Jan 17 10:32:59 photon-zv1KbtvMG systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jan 17 10:33:00 photon-zv1KbtvMG systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Jan 17 10:33:00 photon-zv1KbtvMG systemd[1]: Stopped Kubernetes Kubelet Server.
Jan 17 10:33:00 photon-zv1KbtvMG systemd[1]: kubelet.service: Start request repeated too quickly.
Jan 17 10:33:00 photon-zv1KbtvMG systemd[1]: Failed to start Kubernetes Kubelet Server.
Jan 17 10:33:00 photon-zv1KbtvMG systemd[1]: kubelet.service: Unit entered failed state.
Jan 17 10:33:00 photon-zv1KbtvMG systemd[1]: kubelet.service: Failed with result 'start-limit'.

**Comment by abrarshivani** [comment]
@upendrasahu Can you please let me know if the file '/etc/kubernetes/vsphere.conf' exist?

**Comment by kerneltime** [comment]
```Jan 17 10:32:58 photon-zv1KbtvMG docker[1022]: F0117 10:32:58.876802 1047 plugins.go:80] Couldn't open cloud provider configuration /etc/kubernetes/vsphere.conf: &os.PathError{Op:"ope
n", Path:"/etc/kubernetes/vsphere.conf", Err:0x2}```

**Comment by kerneltime** [comment]
Fixed in https://github.com/kubernetes/kubernetes-anywhere/pull/335
