### ISSUE TITLE
Kubernetes Anywhere - PhotonOS Template Issue

### ISSUE THREAD

**Issue by 2vcps** [kubernetes/kubernetes-anywhere#319]
I was using the photonOS OVA linked in the readme for vSphere and Kubernetes Anywhere. The deployment was seemingly fine except every VM would get the same IP. This makes networking really hard. 
I had to boot up the Template VM and run this command from the Photon OS Administration guide.

#echo -n > /etc/machine-id

[](https://github.com/vmware/photon/blob/master/docs/photon-admin-guide.md#clearing-the-machine-id-of-a-cloned-instance-for-dhcp)

This make sure each VM has a unique MAC and DHCP works as expected.

**Comment by kerneltime** [comment]
Did you power on the template VM before deploying? That might have led to /etc/machine-id getting created.. if you just did an import followed by deploying k8s you should not run into this issue.. can you confirm that is the case?

**Comment by kerneltime** [comment]
cc @BaluDontu @abrarshivani

**Comment by 2vcps** [comment]
I did. That is just a habit. May want to put it in bold in the readme to avoid confusion. 
Thanks.

**Comment by sjpotter** [comment]
Is there a reason why a deploy can't import the ova via govc to avoid this issue?

**Comment by kerneltime** [comment]
@sjpotter govc also works for import, that is what I use. Though do check the name of the VM after import and use the same name during make deploy
