### ISSUE TITLE
Changes to kube-apiserver.jsonnet don't show up on the generated json file on the master node

### ISSUE THREAD

**Issue by stefanhdao** [kubernetes/kubernetes-anywhere#322]
I've modified `kubernetes-anywhere/phase2/ignition/vanilla/manifest/kube-apiserver.jsonnet` and added the `--basic-auth-file` flag but the file `/etc/kubernetes/manifests/kube-apiserver.json` on the master node doesn't reflect my changes. I'm running `make destroy` and `make clean` before I do `make deploy` after my changes.

**Comment by abrarshivani** [comment]
@stefanhdao You need to create ignition container and use that while deploying. You can create container by running DockerFile [here](https://github.com/kubernetes/kubernetes-anywhere/blob/master/phase2/ignition/Dockerfile)

**Comment by stefanhdao** [comment]
@abrarshivani I'm not 100% sure I understand. I destroyed all my docker images and rebuilt them after I made the change. Or is this line where I set `phase2.installer_container = "docker.io/ashivani/k8s-ignition:v4"` and need to change it to something else?

**Comment by carpenterm** [comment]
@stefanhdao - I managed to get this running by making the changes I needed, building the new ignition container and pushing it to an external private repo, and updating the config file to point to that new ignition container, its a bit convoluted but it works:

Make necessary changes to the following file to add api arguments:
`/root/kubernetes-anywhere/phase2/ignition/vanilla/manifest/kube-apiserver.jsonnet`
e.g. 
              `....`
              `"--secure-port=443",`
              ` "--storage-backend=etcd3", `
              `"--allow-privileged",`
              `"--v=4",`
              `"--basic-auth-file=/srv/kubernetes/authfile.csv",`
           `],`

Make necessary changes to the following file to perform host based changes e.g. write to a file:
`/root/kubernetes-anywhere/phase1/vsphere/configure-vm.sh`
e.g.
    `# Start flannel`
    `systemctl enable flanneld`
    `systemctl start flanneld`
    `# Add password`
    `echo -n "MyPassword,carpenterm,1234" > "/srv/kubernetes/authfile.csv"`
    
Change to ignition directory:
`cd /root/kubernetes-anywhere/phase2/ignition`

Build and push new ignition image:
`docker build -t docker.repo/k8s-ignition:latest .`
`docker push docker.repo/k8s-ignition:latest`

Update kubernetes-anywhere/.config to set correct value for phase 2 installer container:
`.phase2.installer_container="docker-dev.csp-artifactory.eng.vmware.com/k8s-ignition:latest"`

Run the kubernetes-anywhere container:
`docker run -it --rm --env="PS1=[container]:\w> " --net=host --volume="/root/kubernetes-anywhere:/opt/kubernetes-anywhere" kubernetes-anywhere:v0.0.1 /bin/bash`

Destroy existing cluster:
`make destroy`

Deploy new configuration:
`make deploy`
