### ISSUE TITLE
vSphere: VMs land up having the same hostname as reported by kubernetes.

### ISSUE THREAD

**Issue by kerneltime** [kubernetes/kubernetes-anywhere#324]
Nodes cloned land up having the same hostname as reported to kubernetes.

**Comment by colemickens** [comment]
What provider and what is your expectation?

**Comment by kerneltime** [comment]
Oops! Had the edit for the subject in my browser but missed clicking save. 
This I believe has to do with how we clone the VMs, have not RCAed it yet but reported it to help track the issue.

**Comment by kerneltime** [comment]
Same as https://github.com/kubernetes/kubernetes-anywhere/issues/295
