### ISSUE TITLE
vSphere: Add UUID for vSphere deployment

### ISSUE THREAD

**Issue by kerneltime** [kubernetes/kubernetes-anywhere#329]
Once https://github.com/kubernetes/kubernetes/pull/41217 merged we need to add support for UUID to the config file.

**Comment by pdhamdhere** [comment]
kubernetes-anywhere for vSphere uses Photon OS which has "/sys/devices/virtual/dmi/id/product_uuid" and available in hypercube container so this is not an issue. We should close this issue.
