### ISSUE TITLE
make deploy fails with: "Failed to upload script: Error reading script: EOF"

### ISSUE THREAD

**Issue by ilchebedelovski** [kubernetes/kubernetes-anywhere#330]
I am trying to deploy kubernetes-anywhere v.1.4.8 on vSphere where vCenter is configured.

After filling the .config.json file I start the deployment with `make deploy`, the virtual machines are created on the ESXi host but the Kubernetes is not successfully deployed.

The following error is displayed:

`Failed to upload script: Error reading script: EOF`

`Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
`

**Comment by kerneltime** [comment]
@ilchebedelovski Can you confirm that the cloned VMs have an IP address, you can verify this from the vCenter UI or using govc tool. Can you also provider the entire console log?

**Comment by ilchebedelovski** [comment]
Thanks for the replay @kerneltime .

The nodes are successfully started on the ESXi host, I receive an IP address for each of them, but nothing is deployed on the nodes.

I am providing the console log:

`data.template_file.cloudprovider: Refreshing state...
tls_private_key.k8s-node: Creating...
  algorithm:          "" => "RSA"
  ecdsa_curve:        "" => "P224"
  private_key_pem:    "" => "<computed>"
  public_key_openssh: "" => "<computed>"
  public_key_pem:     "" => "<computed>"
  rsa_bits:           "" => "2048"
tls_private_key.k8s-master: Creating...
  algorithm:          "" => "RSA"
  ecdsa_curve:        "" => "P224"
  private_key_pem:    "" => "<computed>"
  public_key_openssh: "" => "<computed>"
  public_key_pem:     "" => "<computed>"
  rsa_bits:           "" => "2048"
tls_private_key.k8s-admin: Creating...
  algorithm:          "" => "RSA"
  ecdsa_curve:        "" => "P224"
  private_key_pem:    "" => "<computed>"
  public_key_openssh: "" => "<computed>"
  public_key_pem:     "" => "<computed>"
  rsa_bits:           "" => "2048"
tls_private_key.k8s-root: Creating...
  algorithm:          "" => "RSA"
  ecdsa_curve:        "" => "P224"
  private_key_pem:    "" => "<computed>"
  public_key_openssh: "" => "<computed>"
  public_key_pem:     "" => "<computed>"
  rsa_bits:           "" => "2048"
vsphere_folder.cluster_folder: Creating...
  datacenter:    "" => "SystemAdministration"
  existing_path: "" => "<computed>"
  path:          "" => "k8s"
vsphere_folder.cluster_folder: Creation complete
vsphere_virtual_machine.kubevm2: Creating...
  datacenter:                             "" => "SystemAdministration"
  disk.#:                                 "" => "1"
  disk.470060450.bootable:                "" => "true"
  disk.470060450.controller_type:         "" => "scsi"
  disk.470060450.datastore:               "" => "datastore1"
  disk.470060450.iops:                    "" => ""
  disk.470060450.keep_on_remove:          "" => ""
  disk.470060450.key:                     "" => "<computed>"
  disk.470060450.name:                    "" => ""
  disk.470060450.size:                    "" => ""
  disk.470060450.template:                "" => "Photon"
  disk.470060450.type:                    "" => "thin"
  disk.470060450.uuid:                    "" => "<computed>"
  disk.470060450.vmdk:                    "" => ""
  domain:                                 "" => "vsphere.local"
  enable_disk_uuid:                       "" => "true"
  folder:                                 "" => "k8s"
  linked_clone:                           "" => "false"
  memory:                                 "" => "1024"
  memory_reservation:                     "" => "0"
  name:                                   "" => "node1"
  network_interface.#:                    "" => "1"
  network_interface.0.ip_address:         "" => "<computed>"
  network_interface.0.ipv4_address:       "" => "<computed>"
  network_interface.0.ipv4_gateway:       "" => "<computed>"
  network_interface.0.ipv4_prefix_length: "" => "<computed>"
  network_interface.0.ipv6_address:       "" => "<computed>"
  network_interface.0.ipv6_gateway:       "" => "<computed>"
  network_interface.0.ipv6_prefix_length: "" => "<computed>"
  network_interface.0.label:              "" => "VM Network"
  network_interface.0.mac_address:        "" => "<computed>"
  network_interface.0.subnet_mask:        "" => "<computed>"
  resource_pool:                          "" => "192.168.178.50"
  skip_customization:                     "" => "true"
  time_zone:                              "" => "Etc/UTC"
  uuid:                                   "" => "<computed>"
  vcpu:                                   "" => "1"
vsphere_virtual_machine.kubevm1: Creating...
  datacenter:                             "" => "SystemAdministration"
  disk.#:                                 "" => "1"
  disk.470060450.bootable:                "" => "true"
  disk.470060450.controller_type:         "" => "scsi"
  disk.470060450.datastore:               "" => "datastore1"
  disk.470060450.iops:                    "" => ""
  disk.470060450.keep_on_remove:          "" => ""
  disk.470060450.key:                     "" => "<computed>"
  disk.470060450.name:                    "" => ""
  disk.470060450.size:                    "" => ""
  disk.470060450.template:                "" => "Photon"
  disk.470060450.type:                    "" => "thin"
  disk.470060450.uuid:                    "" => "<computed>"
  disk.470060450.vmdk:                    "" => ""
  domain:                                 "" => "vsphere.local"
  enable_disk_uuid:                       "" => "true"
  folder:                                 "" => "k8s"
  linked_clone:                           "" => "false"
  memory:                                 "" => "1024"
  memory_reservation:                     "" => "0"
  name:                                   "" => "master"
  network_interface.#:                    "" => "1"
  network_interface.0.ip_address:         "" => "<computed>"
  network_interface.0.ipv4_address:       "" => "<computed>"
  network_interface.0.ipv4_gateway:       "" => "<computed>"
  network_interface.0.ipv4_prefix_length: "" => "<computed>"
  network_interface.0.ipv6_address:       "" => "<computed>"
  network_interface.0.ipv6_gateway:       "" => "<computed>"
  network_interface.0.ipv6_prefix_length: "" => "<computed>"
  network_interface.0.label:              "" => "VM Network"
  network_interface.0.mac_address:        "" => "<computed>"
  network_interface.0.subnet_mask:        "" => "<computed>"
  resource_pool:                          "" => "192.168.178.50"
  skip_customization:                     "" => "true"
  time_zone:                              "" => "Etc/UTC"
  uuid:                                   "" => "<computed>"
  vcpu:                                   "" => "1"
tls_private_key.k8s-node: Creation complete
data.tls_cert_request.k8s-node: Refreshing state...
tls_private_key.k8s-root: Creation complete
tls_self_signed_cert.k8s-root: Creating...
  allowed_uses.#:         "" => "3"
  allowed_uses.0:         "" => "key_encipherment"
  allowed_uses.1:         "" => "digital_signature"
  allowed_uses.2:         "" => "cert_signing"
  cert_pem:               "" => "<computed>"
  early_renewal_hours:    "" => "0"
  is_ca_certificate:      "" => "true"
  key_algorithm:          "" => "RSA"
  private_key_pem:        "" => "edaa28b9f7276e83b374886d052acc7de8a012a7"
  subject.#:              "" => "1"
  subject.0.common_name:  "" => "k8s-root_certificate"
  subject.0.organization: "" => "kubernetes-anywhere"
  validity_end_time:      "" => "<computed>"
  validity_period_hours:  "" => "8760"
  validity_start_time:    "" => "<computed>"
tls_self_signed_cert.k8s-root: Creation complete
tls_locally_signed_cert.k8s-node: Creating...
  allowed_uses.#:        "" => "3"
  allowed_uses.0:        "" => "digital_signature"
  allowed_uses.1:        "" => "server_auth"
  allowed_uses.2:        "" => "client_auth"
  ca_cert_pem:           "" => "1f4e8dcaad9d7db4c336870c58f07d329a7d478e"
  ca_key_algorithm:      "" => "RSA"
  ca_private_key_pem:    "" => "edaa28b9f7276e83b374886d052acc7de8a012a7"
  cert_pem:              "" => "<computed>"
  cert_request_pem:      "" => "15f09d9229fc12830dc558e198c8640468c4e06f"
  early_renewal_hours:   "" => "0"
  validity_end_time:     "" => "<computed>"
  validity_period_hours: "" => "8760"
  validity_start_time:   "" => "<computed>"
tls_locally_signed_cert.k8s-node: Creation complete
tls_private_key.k8s-master: Creation complete
tls_private_key.k8s-admin: Creation complete
data.tls_cert_request.k8s-admin: Refreshing state...
tls_locally_signed_cert.k8s-admin: Creating...
  allowed_uses.#:        "" => "3"
  allowed_uses.0:        "" => "digital_signature"
  allowed_uses.1:        "" => "server_auth"
  allowed_uses.2:        "" => "client_auth"
  ca_cert_pem:           "" => "1f4e8dcaad9d7db4c336870c58f07d329a7d478e"
  ca_key_algorithm:      "" => "RSA"
  ca_private_key_pem:    "" => "edaa28b9f7276e83b374886d052acc7de8a012a7"
  cert_pem:              "" => "<computed>"
  cert_request_pem:      "" => "0efae91a399f36bee2c454b9a75933e1e7b42f2f"
  early_renewal_hours:   "" => "0"
  validity_end_time:     "" => "<computed>"
  validity_period_hours: "" => "8760"
  validity_start_time:   "" => "<computed>"
tls_locally_signed_cert.k8s-admin: Creation complete
vsphere_virtual_machine.kubevm2: Still creating... (10s elapsed)
vsphere_virtual_machine.kubevm1: Still creating... (10s elapsed)
vsphere_virtual_machine.kubevm2: Still creating... (20s elapsed)
vsphere_virtual_machine.kubevm1: Still creating... (20s elapsed)
vsphere_virtual_machine.kubevm2: Still creating... (30s elapsed)
vsphere_virtual_machine.kubevm1: Still creating... (30s elapsed)
vsphere_virtual_machine.kubevm2: Still creating... (40s elapsed)
vsphere_virtual_machine.kubevm1: Still creating... (40s elapsed)
vsphere_virtual_machine.kubevm2: Still creating... (50s elapsed)
vsphere_virtual_machine.kubevm1: Still creating... (50s elapsed)
vsphere_virtual_machine.kubevm2: Still creating... (1m0s elapsed)
vsphere_virtual_machine.kubevm1: Still creating... (1m0s elapsed)
vsphere_virtual_machine.kubevm1: Still creating... (1m10s elapsed)
vsphere_virtual_machine.kubevm2: Still creating... (1m10s elapsed)
vsphere_virtual_machine.kubevm2: Still creating... (1m20s elapsed)
vsphere_virtual_machine.kubevm1: Still creating... (1m20s elapsed)
vsphere_virtual_machine.kubevm1: Still creating... (1m30s elapsed)
vsphere_virtual_machine.kubevm2: Still creating... (1m30s elapsed)
vsphere_virtual_machine.kubevm2: Still creating... (1m40s elapsed)
vsphere_virtual_machine.kubevm1: Still creating... (1m40s elapsed)
vsphere_virtual_machine.kubevm2: Still creating... (1m50s elapsed)
vsphere_virtual_machine.kubevm1: Still creating... (1m50s elapsed)
vsphere_virtual_machine.kubevm2: Still creating... (2m0s elapsed)
vsphere_virtual_machine.kubevm1: Still creating... (2m0s elapsed)
vsphere_virtual_machine.kubevm1: Still creating... (2m10s elapsed)
vsphere_virtual_machine.kubevm2: Still creating... (2m10s elapsed)
vsphere_virtual_machine.kubevm1: Still creating... (2m20s elapsed)
vsphere_virtual_machine.kubevm2: Still creating... (2m20s elapsed)
vsphere_virtual_machine.kubevm2: Creation complete
vsphere_virtual_machine.kubevm1: Creation complete
data.tls_cert_request.k8s-master: Refreshing state...
tls_locally_signed_cert.k8s-master: Creating...
  allowed_uses.#:        "" => "3"
  allowed_uses.0:        "" => "digital_signature"
  allowed_uses.1:        "" => "server_auth"
  allowed_uses.2:        "" => "client_auth"
  ca_cert_pem:           "" => "1f4e8dcaad9d7db4c336870c58f07d329a7d478e"
  ca_key_algorithm:      "" => "RSA"
  ca_private_key_pem:    "" => "edaa28b9f7276e83b374886d052acc7de8a012a7"
  cert_pem:              "" => "<computed>"
  cert_request_pem:      "" => "d0d0e01d59ebdd7f1e6849805444963bf9d8c794"
  early_renewal_hours:   "" => "0"
  validity_end_time:     "" => "<computed>"
  validity_period_hours: "" => "8760"
  validity_start_time:   "" => "<computed>"
tls_locally_signed_cert.k8s-master: Creation complete
data.template_file.configure_node: Refreshing state...
data.template_file.configure_master: Refreshing state...
null_resource.node2: Creating...
null_resource.master: Creating...
null_resource.node2: Provisioning with 'remote-exec'...
null_resource.master: Provisioning with 'remote-exec'...
null_resource.master (remote-exec): Connecting to remote host via SSH...
null_resource.master (remote-exec):   Host: 192.168.178.149
null_resource.master (remote-exec):   User: root
null_resource.master (remote-exec):   Password: true
null_resource.master (remote-exec):   Private key: false
null_resource.master (remote-exec):   SSH Agent: false
null_resource.node2 (remote-exec): Connecting to remote host via SSH...
null_resource.node2 (remote-exec):   Host: 192.168.178.148
null_resource.node2 (remote-exec):   User: root
null_resource.node2 (remote-exec):   Password: true
null_resource.node2 (remote-exec):   Private key: false
null_resource.node2 (remote-exec):   SSH Agent: false
null_resource.master (remote-exec): Connected!
null_resource.node2 (remote-exec): Connected!
null_resource.master: Still creating... (10s elapsed)
null_resource.node2: Still creating... (10s elapsed)
null_resource.node2: Still creating... (20s elapsed)
null_resource.master: Still creating... (20s elapsed)
null_resource.node2: Still creating... (30s elapsed)
null_resource.master: Still creating... (30s elapsed)
null_resource.node2: Still creating... (40s elapsed)
null_resource.master: Still creating... (40s elapsed)
null_resource.master: Still creating... (50s elapsed)
null_resource.node2: Still creating... (50s elapsed)
null_resource.node2: Still creating... (1m0s elapsed)
null_resource.master: Still creating... (1m0s elapsed)
null_resource.node2: Still creating... (1m10s elapsed)
null_resource.master: Still creating... (1m10s elapsed)
null_resource.master: Still creating... (1m20s elapsed)
null_resource.node2: Still creating... (1m20s elapsed)
null_resource.node2: Still creating... (1m30s elapsed)
null_resource.master: Still creating... (1m30s elapsed)
null_resource.master: Still creating... (1m40s elapsed)
null_resource.node2: Still creating... (1m40s elapsed)
null_resource.master: Still creating... (1m50s elapsed)
null_resource.node2: Still creating... (1m50s elapsed)
null_resource.node2: Still creating... (2m0s elapsed)
null_resource.master: Still creating... (2m0s elapsed)
null_resource.node2: Still creating... (2m10s elapsed)
null_resource.master: Still creating... (2m10s elapsed)
null_resource.master: Still creating... (2m20s elapsed)
null_resource.node2: Still creating... (2m20s elapsed)
null_resource.master: Still creating... (2m30s elapsed)
null_resource.node2: Still creating... (2m30s elapsed)
null_resource.node2: Still creating... (2m40s elapsed)
null_resource.master: Still creating... (2m40s elapsed)
null_resource.master: Still creating... (2m50s elapsed)
null_resource.node2: Still creating... (2m50s elapsed)
null_resource.node2: Still creating... (3m0s elapsed)
null_resource.master: Still creating... (3m0s elapsed)
null_resource.node2: Still creating... (3m10s elapsed)
null_resource.master: Still creating... (3m10s elapsed)
null_resource.node2: Still creating... (3m20s elapsed)
null_resource.master: Still creating... (3m20s elapsed)
null_resource.node2: Still creating... (3m30s elapsed)
null_resource.master: Still creating... (3m30s elapsed)
null_resource.node2: Still creating... (3m40s elapsed)
null_resource.master: Still creating... (3m40s elapsed)
null_resource.node2: Still creating... (3m50s elapsed)
null_resource.master: Still creating... (3m50s elapsed)
null_resource.node2: Still creating... (4m0s elapsed)
null_resource.master: Still creating... (4m0s elapsed)
null_resource.node2: Still creating... (4m10s elapsed)
null_resource.master: Still creating... (4m10s elapsed)
null_resource.node2: Still creating... (4m20s elapsed)
null_resource.master: Still creating... (4m20s elapsed)
null_resource.node2: Still creating... (4m30s elapsed)
null_resource.master: Still creating... (4m30s elapsed)
null_resource.master: Still creating... (4m40s elapsed)
null_resource.node2: Still creating... (4m40s elapsed)
null_resource.master: Still creating... (4m50s elapsed)
null_resource.node2: Still creating... (4m50s elapsed)
null_resource.master: Still creating... (5m0s elapsed)
null_resource.node2: Still creating... (5m0s elapsed)
Error applying plan:

2 error(s) occurred:

* Failed to upload script: Error reading script: EOF
* Failed to upload script: Error reading script: EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
`

**Comment by abrarshivani** [comment]
@ilchebedelovski Can you ssh into your nodes? If you find that you are been asked to change the password then you need to download ova template again.

**Comment by ilchebedelovski** [comment]
Thank you @abrarshivani , your suggestion resolved my issue!
