### ISSUE TITLE
Honor $GOOGLE_APPLICATION_CREDENTIALS if set

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/kubernetes-anywhere#332]
If using GCE, kubernetes-anywhere requires a file be placed in `phase1/gce/account.json` with the user's credentials in order to bring up a cluster. Other GCE tools/libraries support setting the environment variable `GOOGLE_APPLICATION_CREDENTIALS` to point to the file where your default credentials are stored, so it would be nice if kubernetes-anywhere could check if this was set and use it if `account.json` is missing.

For reference: https://developers.google.com/identity/protocols/application-default-credentials#howtheywork

**Comment by neolit123** [comment]
/reopen

i'm re-opening this as it's seems not possible to remove the runner hack from the kubeadm image yet:
https://github.com/neolit123/test-infra/blob/master/images/kubeadm/runner#L34-L41

**Comment by fabriziopandini** [comment]
/close
Fixed by #557
