### ISSUE TITLE
kubernetes-anywhere vs kubeadm vs kops

### ISSUE THREAD

**Issue by kcl11** [kubernetes/kubernetes-anywhere#340]
This isn't an issue per se, but unsure where else to ask.

First off, just want to say I'm a big fan of what kubernetes-anywhere is trying to do. I came across this post (http://blog.kubernetes.io/2017/01/stronger-foundation-for-creating-and-managing-kubernetes-clusters.html) and was wondering if there is any plan to collaborate with the on-going effort from kubeadm and kops projects.

**Comment by kerneltime** [comment]
kubeadm is a tool to configure k8s where as kube-anywhere and kops are meant to be end to end management of kubernetes clusters. Kube-anywhere does use kubeadm
