### ISSUE TITLE
Space in config is wrongly intepreted by the deployer

### ISSUE THREAD

**Issue by RedDevil69** [kubernetes/kubernetes-anywhere#344]
When variable in config consist space inside is wrongly interpreted during the deployment.
Example for cluster name:
.phase1.vSphere.resourcepool="VIO Mgmt Cluster"

During deployment receiving error
vsphere_virtual_machine.kubevm1: resource pool 'VIO|Mgmt|Cluster' not found

resource_pool:                          "" => "VIO|Mgmt|Cluster"

**Comment by kerneltime** [comment]
Should be fixed in https://github.com/kubernetes/kubernetes-anywhere/pull/345 can you give it a try?

**Comment by RedDevil69** [comment]
Success, thx.
