### ISSUE TITLE
OVA link does not work

### ISSUE THREAD

**Issue by armsby** [kubernetes/kubernetes-anywhere#350]
The link for the OVA is not working is gives Access denied.
Anonymous users does not have storage.objects.get access to object kubernetes-anywhere-for-vsphere-cna-storage/KubernetesAnywhereTemplatePhotonOS.ova.

**Comment by abrarshivani** [comment]
@armsby This is fixed. Can you give a try now?

**Comment by armsby** [comment]
it works now, thank you
