### ISSUE TITLE
*.data.tls_cert_request.K8S-master: unexpected EOF

### ISSUE THREAD

**Issue by prime421** [kubernetes/kubernetes-anywhere#359]
Hello all,

I am a self admitted newbie when it comes to Kubernetes and have been tasked with deploying a cluster for our DEV team.  Using some guides and articles, I was able to:

1.  Install the Photon v1.0 VM and configure it per the articles
2.  Deploy the KubernetesAnywhere .ova (v1.5.4)
3.  Make config succeeds
4.  Make deploy looks like it is going to pass until the very last portion and throws the following error:

*.data.tls_cert_request.K8S-master: unexpected EOF
Makefile:63: recipe for target 'do' failed
make[1]: *** [do] Error 1
make[1]: Leaving directory '/opt/kubernetes-anywhere'
Makefile:41: recipe for target 'deploy-cluster' failed
make: *** [deploy-cluuster] Error 2

I have tried make clear, make destroy, deleting the VMs deployed and re-running the make deploy and it always seems to bomb out on this step.  When I try saying no on the step asking if vCenter uses a self signed cert, it errors right away saying it is insecure.

Our vCenter server is a 2012 R2 server v6 Update 3 with embedded PSC.

Any ideas?  We are stuck.

Thanks in advance!

**Comment by prime421** [comment]
Ok, I no longer am getting this message, however I am getting an error only on the master below.  It seems the other nodes are able to pull the image just fine, the master seems to be the only one having this issue.  Any ideas?

null_resource.master (remote-exec): v1.5.3: Pulling from google-containers/hyperkube-amd64
null_resource.master (remote-exec): Digest: sha256:1c44cdd9526667e5b11b51151940824218a9ca97c6276f8f29830895907147cd
null_resource.master (remote-exec): Status: Image is up to date for gcr.io/google-containers/hyperkube-amd64:v1.5.3
null_resource.master (remote-exec): Unable to find image ‘remarkable/k8s-ignition:v1’ locally
null_resource.master (remote-exec): Pulling repository docker.io/remarkable/k8s-ignition
Error applying plan:

**Comment by prime421** [comment]
I figured this out, nevermind.

**Comment by alejdg** [comment]
@prime421 how did you manage to get through the tls error?

**Comment by prime421** [comment]
Alejdg, so I had a few things going on (like I said, totally new to this):

1.  I did not have a DHCP scope defined, so after the nodes were built I had to give them IP addresses and ultimately ended up creating a scope for our K8S VLAN and the TLS error went away but led to...

2.  SSH wasn't enabled on the nodes, made sure that was enabled and firewall rules to allow ping which cleared that up and lead to...

3.  The last message I got was because I assumed it would create the image, however, I used the default google container image docker.io/cnastorage/k8s-ignition:v1 and after that everything was good.

**Comment by alejdg** [comment]
@prime421 number 1 was my problem too. Thanks for sharing.

**Comment by brettdh** [comment]
@maintainers: It would be great if `make deploy` could detect the DHCP failure and give a more informative message. This error is quite misleading / obfuscated.

**Comment by vmtocloud** [comment]
Same problem here. Ran out of DHCP addresses.
