### ISSUE TITLE
`make deploy` fails to validate

### ISSUE THREAD

**Issue by holiman** [kubernetes/kubernetes-anywhere#364]
I'm having much the same problem as this one: https://github.com/kubernetes/kubernetes-anywhere/issues/260

After deployment, it's stuck in
```
Validation: Expected 5 healthy nodes; found 0. (2870s elapsed)
Validation: Expected 5 healthy nodes; found 0. (2880s elapsed)
Validation: Expected 5 healthy nodes; found 0. (2890s elapsed)
```
Logs: 

`kube@fuzzcluster-master:~$ sudo journalctl -u kubelet 2>&1 | nc termbin.com 9999` : http://termbin.com/3c1h

`kube@fuzzcluster-master:~$ sudo cat /var/log/cloud-init-output.log | nc termbin.com 9999` : http://termbin.com/sdzo

**Comment by colemickens** [comment]
It's because you're using a 1.6 image and this repo isn't updated to handle that.

Right? @mikedanese ?

**Comment by colemickens** [comment]
It's not related to #260 btw.

**Comment by holiman** [comment]
Thanks
