### ISSUE TITLE
DNS, scheduler and dashboard stuck in CrashLoopBackOff

### ISSUE THREAD

**Issue by holiman** [kubernetes/kubernetes-anywhere#365]
Whenever I create a cluster with k8s-anywhere, I wind up with this result: 

```
kube-controller-manager-fuzzcluster-master   1/1       Running            0          6m
kube-dns-v19-4975w                           1/3       CrashLoopBackOff   5          7m
kube-dns-v19-co0uw                           1/3       CrashLoopBackOff   10         7m
kube-proxy-7jxnz                             1/1       Running            0          7m
kube-proxy-d4xi4                             1/1       Running            0          7m
kube-proxy-eewvn                             1/1       Running            0          7m
kube-proxy-p3eho                             1/1       Running            0          7m
kube-proxy-q6doh                             1/1       Running            0          7m
kube-scheduler-fuzzcluster-master            1/1       Running            0          6m
kubernetes-dashboard-1872455951-7lhdk        0/1       CrashLoopBackOff   5          7m
```

I have tried using various versions of kubernetes:
``` 
*
* Phase 2: Node Bootstrapping
*
installer container (phase2.installer_container) [docker.io/cnastorage/k8s-ignition:v1] 
docker registry (phase2.docker_registry) [gcr.io/google-containers] 
kubernetes version (phase2.kubernetes_version) [v1.6.0-beta.4] v1.5.5
```
Have tried `v1.5.1`, `v1.5.5` and `1.4..9` (and `v1.6.0-beta.4` , but that didn't deploy successfully at all with k8s-anywere ). 
I am aware of this: https://github.com/Azure/acs-engine/issues/200 , but I'm not sure what to do to avoid this, or how to fix it after it happens. The issue comments hints at this being fixed.

**Comment by colemickens** [comment]
You'd need to port the fix for that to kubernetes-anywhere, or fix the flags on docker to disable ipmasq/iptables.

Alternatively, you might have a service principal that lacks Write permissions (in that case, it can't write routes and then inter-pod networking doesn't work).

**Comment by holiman** [comment]
> Alternatively, you might have a service principal that lacks Write permissions (in that case, it can't write routes and then inter-pod networking doesn't work).

I think that can be ruled out. 

> You'd need to port the fix for that to kubernetes-anywhere, or fix the flags on docker to disable ipmasq/iptables.

So just to be clear : there's simply no possibility of using any version of k8s-anywhere, or k8s-version, that will work out of the box? I don't know where I'd even start on porting the fix, so I guess my next option would be to use `az` for the deployment instead ... taking the scenic route..

**Comment by colemickens** [comment]
@holiman The Azure team is focused on [acs-engine](https://github.com/Azure/acs-engine) which is the open source core of the Azure Container Service. I would encourage you to look there as there is no investment being made here.

The fix is easy though, if you wanted to port it, you need only add this single line to the ignition scripts in phase2... https://github.com/Azure/acs-engine/blob/master/parts/kubernetesmastercustomdata.yml#L16

Assuming the root cause is the same, I'm just making some assumptions based on your analysis.

**Comment by homotopycolimit** [comment]
I had the same issue after an update on the underlying ubuntu.
I found that I could fix the problem by running this command on master and all nodes:
`sudo iptables -P FORWARD ACCEPT`

**Comment by veliborfrobas** [comment]
Thank you SOOOO much! After update of my hard to make kubernetes cluster it stopped working. I realize that kube-dns is in some trouble but have no idea what to start looking.
Thank you! Thank you! Thank you!
My God, those small things like update can crash a thing... k8s is a looong way to go before any change of getting accepted anywhere except gcloud. Sadly it is. Wonderful, smart thing and to get so many glitches...
