### ISSUE TITLE
Deprecate azure support?

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes-anywhere#366]
I don't have the bandwidth to support `kubernetes-anywhere` alongside `ACS-Engine`.

But I'm not sure what to do about it necessarily...

Thoughts, @mikedanese ? I have no problem with removing it...

**Comment by philips** [comment]
I would like to see how we can bring the Tectonic Installer and Kubernetes Anywhere together. We are currently maintaining an Azure based Terraform installation method here: https://github.com/coreos/tectonic-installer/blob/master/Documentation/install/azure/azure-terraform.md

**Comment by luxas** [comment]
ping @colemickens 
Do you know if anyone uses the Azure thing anymore or if we can remove it by now?
cc @pipejakob

**Comment by shashidharatd** [comment]
+1 for removal. Already its broken. its just an overhead for refactoring the whole project to support kubeadm based deployment and also to deprecate ignition phase2 provider.

**Comment by colemickens** [comment]
I'm not aware of anyone using this. The only users I was aware of have transitioned to other bring-up methods.

+1 on removing it, +10 if it's broken

cc: @brendandburns / @ahowe as an FYI, though I don't anyone at Azure is going to care given their focus on [ACS-Engine](https://github.com/Azure/ACS-Engine)

(Side note, I've worked heavily with 4 bring-up methods and made a couple small feature additions to `tectonic-installer`, my fifth. In my opinion, it is the cleanest, easiest to work with, and most comprehensive option I've seen yet (at least, for Azure). I'm assuming the plan is to keep `kubernetes-anywhere` as being minimal TF + "just invoke kubeadm", but I think it would still be interesting to think about if `tectonic-installer` could ever converge with `kubernetes-anywhere` in the future.)

**Comment by brendandburns** [comment]
Fine with me to delete.



________________________________

**Comment by shashidharatd** [comment]
Azure has already been removed.
/close
