### ISSUE TITLE
vSphere network not found if the name contains a forward slash

### ISSUE THREAD

**Issue by TwoSlick** [kubernetes/kubernetes-anywhere#367]
Example input:
`.phase1.vSphere.network="DHCP_10.1.1.0/24"`

Result:
`Error applying plan:`
`* vsphere_virtual_machine.kubevm2: network '*DHCP_10.1.1.0/24' not found`

**Comment by kerneltime** [comment]
@TwoSlick is this the name of the network in VC?
cc @divyenpatel @abrarshivani

**Comment by TwoSlick** [comment]
I'm not sure what you mean by "VC", but it is the exact name I see in the client.

Here is a screenshot of a similar network.
![network](https://cloud.githubusercontent.com/assets/1937470/24521227/05b252a6-1551-11e7-99d0-c4f3a75a76aa.jpg)

**Comment by divyenpatel** [comment]
@TwoSlick 
I am debugging this issue. We are able to reproduce this issue locally.

I have Network with label: `PG-KubeVM/192.168.0.1`

When specified following the .config file.
`.phase1.vSphere.network="PG-KubeVM/192.168.0.1"`
observed following error while deploying cluster
`vsphere_virtual_machine.kubevm4: network '*PG-KubeVM/192.168.0.1' not found`


cc: @tusharnt @BaluDontu

**Comment by divyenpatel** [comment]
`.phase1.vSphere.network="DHCP_10.1.1.0/24"`
Problem here is terraform is trying to look for the network `24` in the folder 'DHCP_10.1.1.0''

we should use `DHCP_10.1.1.0%2f24`

```
$ govc ls network
/vcqaDC/network/DHCP_10.1.1.0%2f24
/vcqaDC/network/KubeVM-DVUplinks-177
/vcqaDC/network/KubeVM-192.168.0.1
/vcqaDC/network/VM Network
```

there is still a problem with handling '%' in the script.

**Comment by vmtocloud** [comment]
I had this same problem and finally used foldername/switchname in the config and it worked. Even though in vCenter it is listed as foldername/vdsname/switch.
