### ISSUE TITLE
Port kubernetes-anywhere to provision on Packet

### ISSUE THREAD

**Issue by vielmetti** [kubernetes/kubernetes-anywhere#368]
With encouragement from @luxas , this item will track the project to get Kubernetes Anywhere to provision and run services on Packet.

For reference

* [Packet developer API](https://www.packet.net/developers/api/)

**Comment by luxas** [comment]
This will allow us to set up a CI test for kubeadm on arm64 by adding a similar job as https://k8s-testgrid.appspot.com/misc#kubeadm-gce but on Packet.

@packethost and @jacobsmith928 are very kind to provide infra for this :+1:

**Comment by vielmetti** [comment]
The docs mention

"There will be an implementation of GCE/AWS/Azure provisioning that utilizes Terraform."

Does such a thing exist now?

**Comment by vielmetti** [comment]
Work in progress, edit the README file.

https://github.com/vielmetti/kubernetes-anywhere/tree/master/phase1/packet

**Comment by luxas** [comment]
cc @mikedanese @pipejakob @roberthbailey 

They should be able to (and will) help you @vielmetti 
I'm not an expert in these GCE scripts in particular

**Comment by vielmetti** [comment]
Thanks @luxas  !

@mikedanese @pipejakob @roberthbailey - if there's a walk-through of the provisioning process, and some guidelines for what files to change first for a new provider, I'm interested in getting that overview. Packet has an API, but I don't quite understand how this process works end to end, and where the data is pulled from at each stage.

**Comment by pipejakob** [comment]
@vielmetti and I chatted on Slack, and I gave him an overview and pointers about how the current GCE + kubeadm works. It sounds like he has enough to get started now.

**Comment by roberthbailey** [comment]
@vielmetti - is this something you have worked on? As we discussed during a recent cluster lifecycle meeting we hope to deprecate kubernetes-anywhere and move it to the kubernetes graveyard once we are able to port e2e tests for kubeadm over to run on top of the cluster api. And I know you've been looking at making a packet machine controller for the cluster api, which hopefully supersedes this work.

**Comment by luxas** [comment]
IIUC, no more serious work was ever conducted in this area, but the possibility to do this was investigated.
Good news on the Packet Machine controller though!
I'll close this as we'll move from kube-anywhere anyway

**Comment by vielmetti** [comment]
Thanks @roberthbailey @luxas we will be pursuing the Packet machine controller for the cluster API.

**Comment by vielmetti** [comment]
@hh this is the issue I originally raised re kubernetes-anywhere.
