### ISSUE TITLE
Kubernetes-Anywhere Release

### ISSUE THREAD

**Issue by abrarshivani** [kubernetes/kubernetes-anywhere#369]
We don't have any release yet, given that the Kubernetes-Anywhere repo is stable. Can we tag a release now?
// cc @kubernetes/kubernetes-anywhere-admins 
// cc @kubernetes/kubernetes-anywhere-maintainers
// cc @pdhamdhere @tusharnt @BaluDontu @divyenpatel @kerneltime

**Comment by BaluDontu** [comment]
I don't think is kube-anywhere is stable. @divyenpatel has identified few issues w.r.t to new add on weave-net. I will ask divyen, to post more information on this.

**Comment by abrarshivani** [comment]
I plan to tag a release tomorrow EOD. Let me know if any important issue needs to be addressed before release.

**Comment by abrarshivani** [comment]
Done
