### ISSUE TITLE
vSphere: Documentation gap

### ISSUE THREAD

**Issue by alejdg** [kubernetes/kubernetes-anywhere#373]
I believe there is a gap in the steps of  the doc *Getting started on vSphere*. More specifically between [Upload VM Image](https://github.com/kubernetes/kubernetes-anywhere/blob/master/phase1/vsphere/README.md#upload-vm-image-to-be-used-to-vsphere) and [Clone kubernetes-anywhere](https://github.com/kubernetes/kubernetes-anywhere/blob/master/phase1/vsphere/README.md#clone-kubernetes-anywhere).

It is stated in *Upload VM Image* to "**NOT POWER ON THE IMPORTED VM**" but right after it indicates to clone the project. I'm in doubt of where should I clone it. I believe that I should clone the VM, but are there  any details that I need to pay attention to?

**Comment by divyenpatel** [comment]
@alejdg you can git clone kubernetes-anywhere on the guest VM, or on your development machine, which can access the vCenter server.

Once you have kubernetes-anywhere project, you need to build container image using `make docker-dev`. using this image you can deploy cluster.

you should not use template vm, to clone kubernetes-anywhere project. Template VM will be cloned to create master node and worker nodes for kubernetes cluster.

Detailed Steps with snap shots are available at: http://cormachogan.com/2017/02/16/kubernetes-vsphere-kubernetes-anywhere/

@tusharnt @BaluDontu

**Comment by alejdg** [comment]
Thanks for the help @divyenpatel. Now I comprehend it.

Should I close the issue or leave it open so the doc could be extended?

**Comment by divyenpatel** [comment]
I have one PR open to update ReadMe, not yet merged. 
I will add required details. we can close this PR.
