### ISSUE TITLE
Kubernetes 1.6.x support?  (or 1.7 Alpha?)

### ISSUE THREAD

**Issue by robotica72** [kubernetes/kubernetes-anywhere#378]
I believe the current kubernetes-anywhere only support up to 1.5.4 - all 1.6.x deployments fail to validate, and I did see in a closed issue that was known due to repo support.    So two questions, is there a manual method to add 1.6.x  or  when will k8s-anywhere support 1.6.x?

Thanks!

**Comment by divyenpatel** [comment]
@robotica72 

Not sure if you are using vSphere Cloud provider.

You can deploy following recent releases using new ignition image - cnastorage/k8s-ignition:v2

https://github.com/kubernetes/kubernetes/releases/tag/v1.7.0-beta.1
https://github.com/kubernetes/kubernetes/releases/tag/v1.7.0-beta.0
https://github.com/kubernetes/kubernetes/releases/tag/v1.8.0-alpha.0

Once new 1.6 release is available we will update documentation and update installation steps.

CC: @tusharnt @BaluDontu

**Comment by BaluDontu** [comment]
Its 1.7 release not 1.6 release.

**Comment by robotica72** [comment]
Nice - thanks guys, 1.7 Beta 1 looks like it may be a good test....
