### ISSUE TITLE
Dockerfile for gcr.io/mikedanese-k8s/ignite:v3

### ISSUE THREAD

**Issue by philips** [kubernetes/kubernetes-anywhere#379]
I am trying to understand the system and can't find where that comes from. Link?

**Comment by mikedanese** [comment]
https://github.com/kubernetes/kubernetes-anywhere/blob/master/phase2/ignition/Dockerfile

**Comment by mikedanese** [comment]
However it is deprecated in favor of just using kubeadm. Only the GCE provider is moved over which is what we are using to e2e test kubeadm.
