### ISSUE TITLE
Failed to create VM

### ISSUE THREAD

**Issue by billhoph** [kubernetes/kubernetes-anywhere#380]
Is there any log I can extract more detail? I'm sure the mentioned VM template is there, but i have no idea why I kept hitting error in deploying VM. Actually the clone tasks have not been kicked off at all.

Error applying plan:

5 error(s) occurred:

* vsphere_virtual_machine.kubevm2: vm 'KubernetesAnywhereTemplatePhotonOS.ova' not found
* vsphere_virtual_machine.kubevm5: vm 'KubernetesAnywhereTemplatePhotonOS.ova' not found
* vsphere_virtual_machine.kubevm3: vm 'KubernetesAnywhereTemplatePhotonOS.ova' not found
* vsphere_virtual_machine.kubevm4: vm 'KubernetesAnywhereTemplatePhotonOS.ova' not found
* vsphere_virtual_machine.kubevm1: vm 'KubernetesAnywhereTemplatePhotonOS.ova' not found

**Comment by divyenpatel** [comment]
@billhoph  @mvasilenko
 
On your setup do you have VM template with the name `KubernetesAnywhereTemplatePhotonOS.ova` or `KubernetesAnywhereTemplatePhotonOS`?

script is looking for the vm template with name : `KubernetesAnywhereTemplatePhotonOS.ova`
can you make sure the name is correctly specified during the deployment? 

also make sure template is present in the same resource pool or cluster where you want to deploy the kubernetes cluster.

**Comment by mvasilenko** [comment]
I've figured out how to troubleshoot this issue.

You need to download `govc` binary from https://github.com/vmware/govmomi/releases/
or
build and install it the source, by running `go get github.com/vmware/govmomi/govc`

For installation from source, you need to have Go language and working Go environment
```
export GOPATH=$HOME/go
export GOROOT=/usr/local/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
```

Second, configure govc by setting environment variables

```
export GOVC_URL='https://username:password@vcenter-ip-or-hostname/sdk'
export GOVC_DATACENTER=your-dc
export GOVC_INSECURE=true
```

Try to run `govc ls`

On successfull run you will get following output
```
/your-dc/vm
/your-dc/network
/your-dc/host
/your-dc/datastore
```

Then, run `govc ls /your-dc/vm` and you will see your VMs list

In my case, VM named `KubernetesAnywhereTemplatePhotonOS.ova` was placed in
`/your-dc/vm/Discovered virtual machine` directory.

So, I've moved it to the root of datacenter in VCenter web interface and output of `govc ls /your-dc/vm`  now include `/your-dc/vm/KubernetesAnywhereTemplatePhotonOS.ova`

**Comment by mvasilenko** [comment]
@billhoph ping

**Comment by billhoph** [comment]
Sorry for the late reply. Thanks all, the problem has been resolved after moving all the VM into the root directory and a new datastore (as i'm using storage clusters).

**Comment by SamD** [comment]
@billhoph thanks this resolved the problem. People that are familiar with ovftool can also use that as an alternative to govc
