### ISSUE TITLE
VMware vSphere 6.5 deploy error

### ISSUE THREAD

**Issue by spyworldxp** [kubernetes/kubernetes-anywhere#389]
The current "terraform" on kubernetes-anywhere doesn't support vSphere 6.5. Please upgrade hashicorp/terraform to the latest version.

**Comment by msterin** [comment]
Hmm. I Just git cloned master and built, and deployed to Version 6.5.0 Build 4944578 
Can you provide the error message or more info on what is the config and what is failing ?

**Comment by spyworldxp** [comment]
it work now. Everything okay.
