### ISSUE TITLE
vSphere vCenter

### ISSUE THREAD

**Issue by adamstrawson** [kubernetes/kubernetes-anywhere#398]
This is a question rather than an issue. The guide on vsphere deployment mentions that it requires vCenter, is this vCenter Server Foundation or vCenter Server Standard, or can it be either?

**Comment by adamstrawson** [comment]
@divyenpatel Any thoughts on this? Just want to make sure I order the correct license.

**Comment by divyenpatel** [comment]
Let me forward the question to @msterin, @pdhamdhere

**Comment by divyenpatel** [comment]
@adamstrawson Kubernetes should work on both edition.

VMware vCenter Server Foundation is for smaller environments and supports only 3  vsphere hosts.

please refer http://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/whitepaper/vmware-vsphere_pricing-white-paper.pdf

know about key features and capabilities of each edition - http://store.vmware.com/store/vmware/en_US/cat/ThemeID.2485600/categoryID.66249000?src=WWW_eBIZ_productpage_vCenter_Standard_Buy_US#pid-282870000

please contact VMware sales and discuss your need.

**Comment by adamstrawson** [comment]
Thanks @divyenpatel, appreciate the response.

I was looking at Foundation, but just wanted to make sure that version would work fine before purchasing.
