### ISSUE TITLE
Error on make docker-dev command

### ISSUE THREAD

**Issue by jarduini** [kubernetes/kubernetes-anywhere#402]
I´m having an erro when trying to execute make docker-dev command:

[root@lxl1pupkb001 kubernetes-anywhere-0.1.0]# make docker-dev
docker build -t kubernetes-anywhere:v0.0.1 .
Sending build context to Docker daemon 220.7 kB
Step 1 : FROM mhart/alpine-node:6.4.0
 ---> ecd37ad77c2b
Step 2 : RUN apk add --update bash
 ---> Running in 7884e8249a70
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.4/main: operation timed out
WARNING: Ignoring APKINDEX.167438ca.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz

- cat /etc/sysconfig/docker
OPTIONS='-H unix:///var/run/docker.sock --ip-forward=true --iptables=true --ip-masq=true --selinux-enabled=true -G docker --dns 10.8.3.44 --dns-search servicos.com.br --label environment=lab --label name=lxl1pupkb001 --log-driver=json-file --log-opt max-size=50m --mtu=1450'

- docker version:
Docker version 1.12.6, build 1398f24/1.12.6

-kubernetes-anywhere version:
kubernetes-anywhere-0.1.0

I´m behind a proxy so i exported http_proxy.
What i´m missing here?

**Comment by vinayaugustine** [comment]
The fetch is happening within the running container. I modified the docker-build target in Makefile like so:

    docker-build:
            docker build -t $(IMAGE_NAME):$(IMAGE_VERSION) --build-arg http_proxy="MYPROXY" --build-arg https_proxy="MYPROXY" .

(via [How to build Docker Images with Dockerfile behind HTTP_PROXY by Jenkins?](https://stackoverflow.com/a/31987595/6171))

**Comment by jarduini** [comment]
hi @vinayaugustine, thank you for you answer.
I solved it configuring proxy inside the containers.

vi Dockerfile
##########################################
#FROM alpine
FROM mhart/alpine-node:6.4.0
ENV http_proxy http://172.18.0.240:40080
ENV https_proxy https://172.18.0.240:40080

RUN apk add --update bash
ADD ./util/docker-build.sh /opt/
RUN /opt/docker-build.sh

WORKDIR /opt/kubernetes-anywhere
ADD . /opt/kubernetes-anywhere/
CMD make
##########################################
