### ISSUE TITLE
vSphere deployment  build failed 

### ISSUE THREAD

**Issue by g1001p** [kubernetes/kubernetes-anywhere#403]
Dear forum,
I am trying to deploy kubernetes cluster on vsphere.
Actually the target compilation failed with the following error.
I appreciate for any recommendation to handle this issue:
make[1]: Entering directory '/opt/kubernetes-anywhere'
( cd "phase1/$(jq -r '.phase1.cloud_provider' .config.json)"; ./do deploy-cluster )
.tmp/vSphere-k8s.test.tf
Error configuring: 33 error(s) occurred:

* data.template_file.configure_master: missing dependency: tls_self_signed_cert.k8s
* data.template_file.configure_master: missing dependency: tls_locally_signed_cert.k8s
* data.template_file.configure_master: missing dependency: tls_private_key.k8s
* data.template_file.configure_master: missing dependency: tls_locally_signed_cert.k8s
* data.template_file.configure_master: missing dependency: tls_private_key.k8s
* data.template_file.configure_node: missing dependency: tls_private_key.k8s
* data.template_file.configure_node: missing dependency: tls_self_signed_cert.k8s
* data.template_file.configure_node: missing dependency: tls_locally_signed_cert.k8s
* data.template_file.configure_node: missing dependency: tls_locally_signed_cert.k8s
* data.template_file.configure_node: missing dependency: tls_private_key.k8s
* data.tls_cert_request.k8s.test-admin: missing dependency: tls_private_key.k8s
* data.tls_cert_request.k8s.test-admin: missing dependency: tls_private_key.k8s
* data.tls_cert_request.k8s.test-master: missing dependency: tls_private_key.k8s
* data.tls_cert_request.k8s.test-master: missing dependency: tls_private_key.k8s
* data.tls_cert_request.k8s.test-node: missing dependency: tls_private_key.k8s
* data.tls_cert_request.k8s.test-node: missing dependency: tls_private_key.k8s
* null_resource.master: missing dependency: tls_private_key.k8s
* null_resource.master: missing dependency: tls_self_signed_cert.k8s
* null_resource.master: missing dependency: tls_locally_signed_cert.k8s
* tls_locally_signed_cert.k8s.test-admin: missing dependency: tls_private_key.k8s
* tls_locally_signed_cert.k8s.test-admin: missing dependency: tls_private_key.k8s
* tls_locally_signed_cert.k8s.test-admin: missing dependency: data.tls_cert_request.k8s
* tls_locally_signed_cert.k8s.test-admin: missing dependency: tls_self_signed_cert.k8s
* tls_locally_signed_cert.k8s.test-master: missing dependency: tls_private_key.k8s
* tls_locally_signed_cert.k8s.test-master: missing dependency: tls_private_key.k8s
* tls_locally_signed_cert.k8s.test-master: missing dependency: data.tls_cert_request.k8s
* tls_locally_signed_cert.k8s.test-master: missing dependency: tls_self_signed_cert.k8s
* tls_locally_signed_cert.k8s.test-node: missing dependency: tls_self_signed_cert.k8s
* tls_locally_signed_cert.k8s.test-node: missing dependency: tls_private_key.k8s
* tls_locally_signed_cert.k8s.test-node: missing dependency: tls_private_key.k8s
* tls_locally_signed_cert.k8s.test-node: missing dependency: data.tls_cert_request.k8s
* tls_self_signed_cert.k8s.test-root: missing dependency: tls_private_key.k8s
* tls_self_signed_cert.k8s.test-root: missing dependency: tls_private_key.k8s
Makefile:63: recipe for target 'do' failed

**Comment by divyenpatel** [comment]
@g1001p 

Can you please share - /opt/kubernetes-anywhere/.config file?


cc: @tusharnt @BaluDontu

**Comment by divyenpatel** [comment]
@g1001p Can you close this issue?
Looks like you are able to deploy the cluster. https://github.com/kubernetes/kubernetes.github.io/issues/3984#event-1120890053

**Comment by g1001p** [comment]
i checked and see status of this issue closed day ago.
Thank you for great help.

**Comment by divyenpatel** [comment]
I mean to close https://github.com/kubernetes/kubernetes-anywhere/issues/403

**Comment by divyenpatel** [comment]
@g1001p, just in case you still have compilation issue.
We have published pre-build image at `cnastorage/kubernetes-anywhere`


`docker pull cnastorage/kubernetes-anywhere`

`docker run -it --rm --env="PS1=[container]:\w> " --net=host cnastorage/kubernetes-anywhere:latest /bin/bash`

Please Refer updated Getting Started Guide at - https://github.com/kubernetes/kubernetes-anywhere/blob/master/phase1/vsphere/README.md

**Comment by g1001p** [comment]
Looks like you are confusing me with somebody else i am not using
kubernetes-anywhere
