### ISSUE TITLE
Support Openstack in phase 1

### ISSUE THREAD

**Issue by cmluciano** [kubernetes/kubernetes-anywhere#408]
I use Openstack for development and it would be great it Openstack would be a supported cloud provider. I am interested in contributing this functionality if others are interested.

**Comment by shashidharatd** [comment]
@cmluciano, any progress on this? I have a simple implementation that works and would like to collaborate if you already have done some implementation.

**Comment by cmluciano** [comment]
I have not done much yet. Please feel free to submit your patch and I can tack on.

**Comment by cmluciano** [comment]
merged with https://github.com/kubernetes/kubernetes-anywhere/pull/432
