### ISSUE TITLE
vsphere deployment fails (RUNTIME ERROR: Field does not exist: cluster)

### ISSUE THREAD

**Issue by TreverW** [kubernetes/kubernetes-anywhere#409]
After running `make docker-dev` and `make config` specifying vSphere options, then running `make deploy`, I'm getting this error.

    [container]:/opt/kubernetes-anywhere> make deploy
    util/config_to_json .config > .config.json
    make do WHAT=deploy-cluster
    make[1]: Entering directory '/opt/kubernetes-anywhere'
    ( cd "phase1/$(jq -r '.phase1.cloud_provider' .config.json)"; ./do deploy-cluster )
    RUNTIME ERROR: Field does not exist: cluster
    	vSphere.jsonnet:109:22-40	object <anonymous>
    	vSphere.jsonnet:(98:32)-(125:7)	object <anonymous>
    	std.jsonnet:(943:13)-(952:13)	object <anonymous>
    	std.jsonnet:(943:13)-(952:13)	object <anonymous>
    	all.jsonnet:3:49-79	object <anonymous>
    	During manifestation
    Makefile:63: recipe for target 'do' failed
    make[1]: *** [do] Error 1
    make[1]: Leaving directory '/opt/kubernetes-anywhere'
    Makefile:41: recipe for target 'deploy-cluster' failed
    make: *** [deploy-cluster] Error 2

When I look at the `.config.json` that was created, I see that the value I entered for **Deploy Kubernetes Cluster on 'host' or 'cluster' (phase1.vSphere.placement)**  was saved as 

          "placement": "vc-vmhost1",

instead of

          "cluster": "vc-vmhost1",

When I edited `.config.json` and copied the **"placement"** line and changed it to **"cluster"** it worked.

**Comment by divyenpatel** [comment]
@TreverW 

Can you please try this image?

```
docker rmi cnastorage/kubernetes-anywhere:latest
docker pull cnastorage/kubernetes-anywhere
docker run -it --rm --env="PS1=[container]:\w> " --net=host cnastorage/kubernetes-anywhere:latest /bin/bash
```

We had some issue in the cnastorage/kubernetes-anywhere:latest image we published two days before. Made a fix today.


For following option, you need to enter "host", if you want to deploy cluster on one single host. else enter "cluster".
in the next question, you will be asked to enter name of host or name of the cluster based on the option you have selected.

`Deploy Kubernetes Cluster on 'host' or 'cluster' (phase1.vSphere.placement)
`

@TreverW please let us know if this is resolving the  issue you have ovserved.

cc: @tusharnt @BaluDontu

**Comment by TreverW** [comment]
Thank you.  It sounds like I misunderstood the prompt and entered the **name** of my host instead of ‘host’.  

It now works with your instructions.
