### ISSUE TITLE
Kubelet fails to start when generated vsphere.conf contains improperly escaped characters

### ISSUE THREAD

**Issue by jck-ccl** [kubernetes/kubernetes-anywhere#415]
When using the latest cnastorage/kubernetes-anywhere image
And deploying to vSphere
If the vCenter username and password contain characters that require escaping, for example backslash or double quote
Then the generated vSphere.conf file does not have these values properly escaped and the kubelet will not start.
The following error can be seen in 'journalctl -u kubelet'

```
Jul 19 19:10:56 master docker[767]: Error: failed to run Kubelet: could not init cloud provider "vsphere"
: 2:21: unknown escape sequence
Jul 19 19:10:56 master docker[767]: Error: failed to run Kubelet: could not init cloud provider "vsphere"
: 2:21: unknown escape sequence
Jul 19 19:10:56 master systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FA
ILURE
```

Example snippet from /etc/kubernetes/vsphere.conf

```
[Global]
        user = "domain\user"
        password = "mypassword""
       ...
```
Correcting this on each node in the cluster, like this
```
[Global]
        user = "domain\\user"
        password = "mypassword\""
       ...
```
And reloading the kubelet service results in a successful deployment.

**Comment by divyenpatel** [comment]
@jck-ccl PR is merged. You can close this issue.
