### ISSUE TITLE
Configure one host, no resource pool?

### ISSUE THREAD

**Issue by brettdh** [kubernetes/kubernetes-anywhere#418]
Is it possible to configure a single-host server with no resource pool? I have a host, not a cluster, on my vSphere, and no resource pool, and [no ability to create one](https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1004098). (I cannot change the config on the VM host.) If I say "no" to `phase1.vSphere.useresourcepool`, it tries to use one with the same name as the host, which it can't find:
```
* vsphere_virtual_machine.kubevm1: resource pool 'foo.example.com' not found
```

**Comment by brettdh** [comment]
D'oh. I left off the host's enclosing folder. Adding that prefix (i.e. specifying `my folder/foo.example.com` as the host) resolved the issue.

**Comment by OMSKremer** [comment]
Hi, i have the same problem, can you please explain "host's enclosing folder"?

**Comment by brettdh** [comment]
Hi @OMSKremer - I mean that my VM host is laid out like this in vcenter:
```
vcenter.example.com
└─ My Datacenter  
   └─ my_folder
      └─ my-vsphere-host.example.com
         └─ my-vm
```
So in this instance, `my_folder` is the "host's enclosing folder" - just the folder that the host `my-vsphere-host.example.com` happens to be in. So for `.phase1.vSphere.host`, I was initially setting it to `my-vsphere-host.example.com`, which produced the above error. When I changed it to `my-folder/my-vsphere-host.example.com`, it worked.

**Comment by OMSKremer** [comment]
@brettdh Thanks a lot!
