### ISSUE TITLE
vmware esxi 5.5 - ova hardware version

### ISSUE THREAD

**Issue by dayglo** [kubernetes/kubernetes-anywhere#419]
Hi,

We'd like to use k-a on esxi 5.5 which only supports hardware version 10.

Is there any reason you build your OVA template using vmware hardware version 11?

Do you build the OVA with packer or similar? If so please could you share the source?

**Comment by divyenpatel** [comment]
@dayglo We can provide you steps to convert OVA file to support hardware version 10 using vCenter Converter.

VMware Issue: https://github.com/vmware/kubernetes/issues/128

**Comment by divyenpatel** [comment]
@dayglo Please use this image vmx-10 image on esx5.5 - https://storage.googleapis.com/kubernetes-anywhere-for-vsphere-cna-storage/KubernetesAnywhereTemplatePhotonOSESX5.5.ova

**Comment by divyenpatel** [comment]
@dayglo just following up regarding new image I shared above.
Can you please close this issue, if you are able to deploy cluster using this image.

**Comment by psyolent** [comment]
Thanks for sharing that link

**Comment by divyenpatel** [comment]
@dayglo provided links works fine for @psyolent on ESX 5.5
Can you close this issue?
