### ISSUE TITLE
Cluster Upgrade

### ISSUE THREAD

**Issue by jessicaochen** [kubernetes/kubernetes-anywhere#431]
Since k8s anywhere already covers lifecycle events of deploy and destroy clusters, how about adding a make command of upgrade-cluster that can upgrade clusters? I am probing community interest (and/or objections).

I am specifically interested in getting this working for kubeadm/gce and am working on prototypes/designs. I do plan on a design that should be generic enough to work easily with other phase 1 and phase 2 providers.

**Comment by luxas** [comment]
cc @kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by luxas** [comment]
@jessicaochen Please go ahead and do that, SGTM :+1:
cc @mikedanese

**Comment by roberthbailey** [comment]
+1

**Comment by jessicaochen** [comment]
Upgrade Cluster Approach Proposal: https://docs.google.com/a/google.com/document/d/1PoDeqD8qu1KbAd-fb7xOVB1G7YTyD6VLLlhaVB3QeA4/edit?usp=sharing

**Comment by marrik96** [comment]
+1 on upgrade

**Comment by roberthbailey** [comment]
@jessicaochen - this was implemented in #450 right? Can we mark as fixed?

**Comment by jessicaochen** [comment]
Only master upgrade is implemented at this point since it was the motivating upgrade need for E2E tests. I suppose I can close this and if some folks feel a need/want node upgrades, they can re-open and take over.
