### ISSUE TITLE
Steps for Getting started on GCE unclear

### ISSUE THREAD

**Issue by prateekgogia** [kubernetes/kubernetes-anywhere#433]
In the [getting started guide](https://github.com/kubernetes/kubernetes-anywhere/blob/master/phase1/gce/README.md) for GCE, it mentions the following - 

> You will be logged into your dev shell:
> If kubeadm is the phase2.provider, then login to gcloud by calling:
> $ gcloud auth login

I was able to reach to the point, where it takes you to the dev shell. However, in the next step it is not clear _`If kubeadm is the phase2.provider`_ or something else and there is no way to check which provider is it. If I skip this step, it errors out saying - 

```
Error asking for user input: 1 error(s) occurred:

* provider.google: file: open account.json: no such file or directory in:

`${file("account.json")}`
```

**Comment by prateekgogia** [comment]
`make deploy` also fails for GCE, I think this is a separate issue.

**Comment by serjo77** [comment]
Authenticating with Google Cloud services requires a JSON file which we call the account file.
This file is downloaded directly from the Google Developers Console. To make the process more straightforwarded, it is documented here:

Log into the Google Developers Console and select a project.

The API Manager view should be selected, click on "Credentials" on the left, then "Create credentials", and finally "Service account key".

Select "Compute Engine default service account" in the "Service account" dropdown, and select "JSON" as the key type.

Clicking "Create" will download your credentials.

Save json file to phase1/gce/account.json
