### ISSUE TITLE
null_resource.$cluster-master: 1 error(s) occurred

### ISSUE THREAD

**Issue by nthaler-mit** [kubernetes/kubernetes-anywhere#454]
I'm attempting to deploy a kubernetes cluster against a test vSphere 6.5 U1 endpoint, but fail each time with a null_resource message against the master (potentially during the phase1 cluster deploy phase)

Nothing in the environment appears too usual: hypervisors in sync using strata 1 ntp time sources, shared iSCSI datastore, dvPortgroup backed by a DHCP server, cluster has sufficient resources.    The resulting workers and master DHCP without issue.  

I've tried the deploy from both a PhotonOS and Ubuntu 16.04 system; no difference.

root@XXXX [ ~ ]# docker pull cnastorage/kubernetes-anywhere
Using default tag: latest
latest: Pulling from cnastorage/kubernetes-anywhere
Digest: sha256:e2ee18aa00b3b6f9ea7a6b8d1ee117384cc8bec11f100bc6f9aaca7941c04e45
Status: Image is up to date for cnastorage/kubernetes-anywhere:latest
root@XXXX [ ~ ]# docker run -it -v /tmp:/tmp --rm --env="PS1=[container]:\w> " --net=host cnastorage/kubernetes-anywhere:latest /bin/bash

* Phase 1: Cluster Resource Provisioning
*
number of nodes (phase1.num_nodes) [1]
kubernetes cluster name (phase1.cluster_name) [psod]
SSH user to login to OS for provisioning (phase1.ssh_user) []
*
* cloud provider: gce, azure or vsphere
*
cloud provider: gce, azure or vsphere (phase1.cloud_provider) [vsphere]
  *
  * vSphere configuration
  *
  vCenter URL Ex: 10.192.10.30 or myvcenter.io (without https://) (phase1.vSphere.url) [XXXXXX]
  vCenter port (phase1.vSphere.port) [443]
  vCenter username (phase1.vSphere.username) [kub.service@vsphere.local]
  vCenter password (phase1.vSphere.password) [XXXXX]
  Does host use self-signed cert (phase1.vSphere.insecure) [Y/n/?]
  Datacenter (phase1.vSphere.datacenter) [XXXX]
  Datastore (phase1.vSphere.datastore) [iSCSI-LUN0]
  Deploy Kubernetes Cluster on 'host' or 'cluster' (phase1.vSphere.placement) [cluster]
    vsphere cluster name. Please make sure that all the hosts in the cluster are time-synchronized otherwise some of the nodes can remain in pending state for ever due to expired certificate (phase1.vSphere.cluster) [Sandbox]
  Do you want to use the existing resource pool on the host or cluster? [yes, no] (phase1.vSphere.useresourcepool) [no]
  VM Folder name or Path (e.g kubernetes, VMFolder1/dev-cluster, VMFolder1/Test Group1/test-cluster). Folder path will be created if not present (phase1.vSphere.vmfolderpath) [kubernetes]
  Number of vCPUs for each VM (phase1.vSphere.vcpu) [1]
  Memory for VM (phase1.vSphere.memory) [2048]
  Network for VM (phase1.vSphere.network) [dvInternal]
  Name of the template VM imported from OVA. If Template file is not available at the destination location specify vm path (phase1.vSphere.template) [KubernetesAnywhereTemplatePhotonOS.ova]
  Flannel Network (phase1.vSphere.flannel_net) [172.1.0.0/16]
*
* Phase 2: Node Bootstrapping
*
kubernetes version (phase2.kubernetes_version) [v1.6.5]
bootstrap provider (phase2.provider) [ignition]
  installer container (phase2.installer_container) [docker.io/cnastorage/k8s-ignition:v2]
  docker registry (phase2.docker_registry) [gcr.io/google-containers]
*
* Phase 3: Deploying Addons
*
Run the addon manager? (phase3.run_addons) [Y/n/?]
  Run kube-proxy? (phase3.kube_proxy) [Y/n/?]
  Run the dashboard? (phase3.dashboard) [Y/n/?]
  Run heapster? (phase3.heapster) [Y/n/?]
  Run kube-dns? (phase3.kube_dns) [Y/n/?]
  Run weave-net? (phase3.weave_net) [N/y/?]
#
# configuration written to .config

===

make[1]: Entering directory '/opt/kubernetes-anywhere'
( cd "phase1/vsphere"; ./do deploy-cluster )
psod/.tmp/vSphere-psod.tf
tls_private_key.psod-root: Refreshing state... (ID: 0ba2b3d31bf7a02afc558fe42bd9afd2cad5bc16)
tls_private_key.psod-node: Refreshing state... (ID: 643b42ec6d597289c746ea0efaaa845ab2926573)
tls_private_key.psod-admin: Refreshing state... (ID: b7926dfd99f46c23979c0e7b382664b61db3e2a3)
tls_private_key.psod-master: Refreshing state... (ID: 5ba8fdab299ba466b21763040e2c268c8aae98e5)
tls_self_signed_cert.psod-root: Refreshing state... (ID: 107725442640741129313727620414884837682)
tls_cert_request.psod-node: Refreshing state... (ID: 79530e7f191ad0c96a0481a58b7bdf7a1955e53a)
tls_cert_request.psod-admin: Refreshing state... (ID: d3a4a063528546961cdb0782524e1fe45a5fdd7c)
data.template_file.cloudprovider: Refreshing state...
tls_locally_signed_cert.psod-admin: Refreshing state... (ID: 37005829126929334050474979607585762354)
tls_locally_signed_cert.psod-node: Refreshing state... (ID: 249377147565960010910775338019743846965)
vsphere_folder.cluster_folder: Refreshing state... (ID: XXXXXX/kubernetes)
vsphere_virtual_machine.kubevm1: Creating...
  datacenter:                             "" => "W92-153"
  detach_unknown_disks_on_delete:         "" => "false"
  disk.#:                                 "" => "1"
  disk.3642767325.bootable:               "" => "true"
  disk.3642767325.controller_type:        "" => "scsi"
  disk.3642767325.datastore:              "" => "iSCSI-LUN0"
  disk.3642767325.iops:                   "" => ""
  disk.3642767325.keep_on_remove:         "" => ""
  disk.3642767325.key:                    "" => "<computed>"
  disk.3642767325.name:                   "" => ""
  disk.3642767325.size:                   "" => ""
  disk.3642767325.template:               "" => "KubernetesAnywhereTemplatePhotonOS.ova"
  disk.3642767325.type:                   "" => "thin"
  disk.3642767325.uuid:                   "" => "<computed>"
  disk.3642767325.vmdk:                   "" => ""
  domain:                                 "" => "vsphere.local"
  enable_disk_uuid:                       "" => "true"
  folder:                                 "" => "kubernetes"
  linked_clone:                           "" => "false"
  memory:                                 "" => "2048"
  memory_reservation:                     "" => "0"
  name:                                   "" => "XXXXXX-master"
  network_interface.#:                    "" => "1"
  network_interface.0.ip_address:         "" => "<computed>"
  network_interface.0.ipv4_address:       "" => "<computed>"
  network_interface.0.ipv4_gateway:       "" => "<computed>"
  network_interface.0.ipv4_prefix_length: "" => "<computed>"
  network_interface.0.ipv6_address:       "" => "<computed>"
  network_interface.0.ipv6_gateway:       "" => "<computed>"
  network_interface.0.ipv6_prefix_length: "" => "<computed>"
  network_interface.0.label:              "" => "dvInternal"
  network_interface.0.mac_address:        "" => "<computed>"
  network_interface.0.subnet_mask:        "" => "<computed>"
  resource_pool:                          "" => "Sandbox"
  skip_customization:                     "" => "true"
  time_zone:                              "" => "Etc/UTC"
  uuid:                                   "" => "<computed>"
  vcpu:                                   "" => "1"
vsphere_virtual_machine.kubevm2: Creating...
  datacenter:                             "" => "XXXXXX"
  detach_unknown_disks_on_delete:         "" => "false"
  disk.#:                                 "" => "1"
  disk.3642767325.bootable:               "" => "true"
  disk.3642767325.controller_type:        "" => "scsi"
  disk.3642767325.datastore:              "" => "iSCSI-LUN0"
  disk.3642767325.iops:                   "" => ""
  disk.3642767325.keep_on_remove:         "" => ""
  disk.3642767325.key:                    "" => "<computed>"
  disk.3642767325.name:                   "" => ""
  disk.3642767325.size:                   "" => ""
  disk.3642767325.template:               "" => "KubernetesAnywhereTemplatePhotonOS.ova"
  disk.3642767325.type:                   "" => "thin"
  disk.3642767325.uuid:                   "" => "<computed>"
  disk.3642767325.vmdk:                   "" => ""
  domain:                                 "" => "vsphere.local"
  enable_disk_uuid:                       "" => "true"
  folder:                                 "" => "kubernetes"
  linked_clone:                           "" => "false"
  memory:                                 "" => "2048"
  memory_reservation:                     "" => "0"
  name:                                   "" => "psod-node1"
  network_interface.#:                    "" => "1"
  network_interface.0.ip_address:         "" => "<computed>"
  network_interface.0.ipv4_address:       "" => "<computed>"
  network_interface.0.ipv4_gateway:       "" => "<computed>"
  network_interface.0.ipv4_prefix_length: "" => "<computed>"
  network_interface.0.ipv6_address:       "" => "<computed>"
  network_interface.0.ipv6_gateway:       "" => "<computed>"
  network_interface.0.ipv6_prefix_length: "" => "<computed>"
  network_interface.0.label:              "" => "dvInternal"
  network_interface.0.mac_address:        "" => "<computed>"
  network_interface.0.subnet_mask:        "" => "<computed>"
  resource_pool:                          "" => "Sandbox"
  skip_customization:                     "" => "true"
  time_zone:                              "" => "Etc/UTC"
  uuid:                                   "" => "<computed>"
  vcpu:                                   "" => "1"
vsphere_virtual_machine.kubevm1: Still creating... (10s elapsed)
vsphere_virtual_machine.kubevm2: Still creating... (10s elapsed)
vsphere_virtual_machine.kubevm1: Still creating... (20s elapsed)
vsphere_virtual_machine.kubevm2: Still creating... (20s elapsed)
vsphere_virtual_machine.kubevm1: Still creating... (30s elapsed)
vsphere_virtual_machine.kubevm2: Still creating... (30s elapsed)
vsphere_virtual_machine.kubevm1: Still creating... (40s elapsed)
vsphere_virtual_machine.kubevm2: Still creating... (40s elapsed)
vsphere_virtual_machine.kubevm1: Still creating... (50s elapsed)
vsphere_virtual_machine.kubevm2: Still creating... (50s elapsed)
vsphere_virtual_machine.kubevm1: Still creating... (1m0s elapsed)
vsphere_virtual_machine.kubevm2: Still creating... (1m0s elapsed)
vsphere_virtual_machine.kubevm2: Creation complete (ID: kubernetes/XXXXXX-node1)
vsphere_virtual_machine.kubevm1: Creation complete (ID: kubernetes/XXXXXX-master)
tls_cert_request.psod-master: Creating...
  cert_request_pem:       "" => "<computed>"
  dns_names.#:            "" => "6"
  dns_names.0:            "" => "XXXXXX-master"
  dns_names.1:            "" => "kubernetes"
  dns_names.2:            "" => "kubernetes.default"
  dns_names.3:            "" => "kubernetes.default.svc"
  dns_names.4:            "" => "kubernetes.default.svc.local"
  dns_names.5:            "" => "kubernetes.default.svc.local"
  ip_addresses.#:         "" => "2"
  ip_addresses.0:         "" => "192.168.1.23"
  ip_addresses.1:         "" => "10.0.0.1"
  key_algorithm:          "" => "RSA"
  private_key_pem:        "" => "e500946bb7e58d9340a3e121a31567ea6352cbb1"
  subject.#:              "" => "1"
  subject.0.common_name:  "" => "psod-master_certificate"
  subject.0.organization: "" => "kubernetes-anywhere"
tls_cert_request.psod-master: Creation complete (ID: 0aad068b5658eea027f3d2817ce5afdfdf922b64)
tls_locally_signed_cert.XXXXXX-master: Creating...
  allowed_uses.#:        "" => "3"
  allowed_uses.0:        "" => "digital_signature"
  allowed_uses.1:        "" => "server_auth"
  allowed_uses.2:        "" => "client_auth"
  ca_cert_pem:           "" => "eef9eaeb30f6c98df8e08188f068e33e12edd3de"
  ca_key_algorithm:      "" => "RSA"
  ca_private_key_pem:    "" => "fcecff1466dd6719d01fce7c59725365d2cb9f87"
  cert_pem:              "" => "<computed>"
  cert_request_pem:      "" => "314c9517c678a3ed8ef110707400d239f45ad53e"
  early_renewal_hours:   "" => "0"
  validity_end_time:     "" => "<computed>"
  validity_period_hours: "" => "8760"
  validity_start_time:   "" => "<computed>"
tls_locally_signed_cert.psod-master: Creation complete (ID: 66437661694879197104917205874988962678)
data.template_file.configure_node: Refreshing state...
data.template_file.configure_master: Refreshing state...
null_resource.psod-node2: Creating...
null_resource.psod-master: Creating...
null_resource.psod-master: Provisioning with 'remote-exec'...
null_resource.psod-node2: Provisioning with 'remote-exec'...
null_resource.psod-node2 (remote-exec): Connecting to remote host via SSH...
null_resource.psod-node2 (remote-exec):   Host: 192.168.1.30
null_resource.psod-node2 (remote-exec):   User: root
null_resource.psod-node2 (remote-exec):   Password: true
null_resource.psod-node2 (remote-exec):   Private key: false
null_resource.psod-node2 (remote-exec):   SSH Agent: false
null_resource.psod-master (remote-exec): Connecting to remote host via SSH...
null_resource.psod-master (remote-exec):   Host: 192.168.1.23
null_resource.psod-master (remote-exec):   User: root
null_resource.psod-master (remote-exec):   Password: true
null_resource.psod-master (remote-exec):   Private key: false
null_resource.psod-master (remote-exec):   SSH Agent: false
null_resource.psod-node2 (remote-exec): Connected!
null_resource.psod-node2 (remote-exec): Created symlink from /etc/systemd/system/multi-user.target.wants/flannelc.service to /usr/lib/systemd/system/flannelc.service.
null_resource.psod-master: Still creating... (10s elapsed)
null_resource.psod-node2: Still creating... (10s elapsed)
null_resource.psod-master (remote-exec): Connecting to remote host via SSH...
null_resource.psod-master (remote-exec):   Host: 192.168.1.23
null_resource.psod-master (remote-exec):   User: root
null_resource.psod-master (remote-exec):   Password: true
null_resource.psod-master (remote-exec):   Private key: false
null_resource.psod-master (remote-exec):   SSH Agent: false
null_resource.psod-node2: Still creating... (20s elapsed)
null_resource.psod-master: Still creating... (20s elapsed)
null_resource.psod-master: Still creating... (30s elapsed)
null_resource.psod-node2: Still creating... (30s elapsed)
null_resource.psod-master (remote-exec): Connecting to remote host via SSH...
null_resource.psod-master (remote-exec):   Host: 192.168.1.23
null_resource.psod-master (remote-exec):   User: root
null_resource.psod-master (remote-exec):   Password: true
null_resource.psod-master (remote-exec):   Private key: false
null_resource.psod-master (remote-exec):   SSH Agent: false
null_resource.psod-node2: Still creating... (40s elapsed)
null_resource.psod-master: Still creating... (40s elapsed)
null_resource.psod-master (remote-exec): Connecting to remote host via SSH...
null_resource.psod-master (remote-exec):   Host: 192.168.1.23
null_resource.psod-master (remote-exec):   User: root
null_resource.psod-master (remote-exec):   Password: true
null_resource.psod-master (remote-exec):   Private key: false
null_resource.psod-master (remote-exec):   SSH Agent: false
null_resource.psod-master: Still creating... (50s elapsed)
null_resource.psod-node2: Still creating... (50s elapsed)
null_resource.psod-node2: Still creating... (1m0s elapsed)
null_resource.psod-master: Still creating... (1m0s elapsed)
null_resource.psod-master (remote-exec): Connecting to remote host via SSH...
null_resource.psod-master (remote-exec):   Host: 192.168.1.23
null_resource.psod-master (remote-exec):   User: root
null_resource.psod-master (remote-exec):   Password: true
null_resource.psod-master (remote-exec):   Private key: false
null_resource.psod-master (remote-exec):   SSH Agent: false
null_resource.psod-master (remote-exec): Connected!
null_resource.psod-master (remote-exec): Created symlink from /etc/systemd/system/multi-user.target.wants/etcd.service to /usr/lib/systemd/system/etcd.service.
null_resource.psod-master (remote-exec): Created symlink from /etc/systemd/system/multi-user.target.wants/flanneld.service to /usr/lib/systemd/system/flanneld.service.
null_resource.psod-master: Still creating... (1m10s elapsed)
null_resource.psod-node2: Still creating... (1m10s elapsed)
null_resource.psod-node2: Still creating... (1m20s elapsed)
null_resource.psod-master: Still creating... (1m20s elapsed)
null_resource.psod-master: Still creating... (1m30s elapsed)
null_resource.psod-node2: Still creating... (1m30s elapsed)
null_resource.psod-node2: Creation complete (ID: 7034267004627362524)
null_resource.psod-master: Still creating... (1m40s elapsed)
null_resource.psod-master: Still creating... (1m50s elapsed)
null_resource.psod-master: Still creating... (2m0s elapsed)
null_resource.psod-master: Still creating... (2m10s elapsed)
null_resource.psod-master: Still creating... (2m20s elapsed)
null_resource.psod-master: Still creating... (2m30s elapsed)
Error applying plan:

1 error(s) occurred:

* null_resource.XXXXXX-master: 1 error(s) occurred:

* Script exited with non-zero exit status: 1

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

Makefile:77: recipe for target 'do' failed
make[1]: *** [do] Error 1
make[1]: Leaving directory '/opt/kubernetes-anywhere'
Makefile:49: recipe for target 'deploy-cluster' failed
make: *** [deploy-cluster] Error 2

**Comment by divyenpatel** [comment]
I see node VMs are getting private addresses - `192.168.1.23`, your deployment container should be able to connect to these VMs in this private network. 

I think you need to put your docker host in the same network – `dvInternal`, and should try deploying from there.
