### ISSUE TITLE
vsphere - make deploy fails on vSphere 6 (vcenter) deployment

### ISSUE THREAD

**Issue by jhedman2** [kubernetes/kubernetes-anywhere#460]
Wondering if anyone can help, tried multiple times, including starting from scratch, but the deployment process fails every time with the same error:

[container]:/opt/kubernetes-anywhere> make deploy
util/config_to_json /opt/kubernetes-anywhere/.config > /opt/kubernetes-anywhere/.config.json
make do WHAT=deploy-cluster
make[1]: Entering directory '/opt/kubernetes-anywhere'
( cd "phase1/vsphere"; ./do deploy-cluster )
phase1.k8slab/.tmp/vSphere-phase1.k8slab.tf
Error asking for user input: Error parsing address 'null_resource.phase1.k8slab-master': Problem parsing address: "null_resource.phase1.k8slab-master"
Makefile:70: recipe for target 'do' failed
make[1]: *** [do] Error 1
make[1]: Leaving directory '/opt/kubernetes-anywhere'
Makefile:48: recipe for target 'deploy-cluster' failed
make: *** [deploy-cluster] Error 2

This is a lab vsphere environment, vCenter 6.0.0 u3, vSphere 6.  Self signed vCenter, tried both IP and FQDN vCenter url, standard port 443.  tried multiple logins as well.  verified l3 connectivity to vCenter and internet/dns.

any help appreciated.

**Comment by divyenpatel** [comment]
@jhedman2 Can you share `/opt/kubernetes-anywhere/.config` file

**Comment by jhedman2** [comment]
Thank you for the response!  Here's the output of the file, please note
obviously I edited the password, just for safety sake.

-------------------------

# Automatically generated file; DO NOT EDIT.
# Kubernetes Minimal Turnup Configuration
#

#
# Phase 1: Cluster Resource Provisioning
#
.phase1.num_nodes=4
.phase1.cluster_name="kubernetes"
.phase1.ssh_user=""
.phase1.cloud_provider="vsphere"

#
# vSphere configuration
#
.phase1.vSphere.url="192.168.1.5"
.phase1.vSphere.port=443
.phase1.vSphere.username="k8sadmin@vsphere.local"
.phase1.vSphere.password="****blankedforsafety****"
.phase1.vSphere.insecure=y
.phase1.vSphere.datacenter="5280Hedmans.Local"
.phase1.vSphere.datastore="homenas03_nfs01"
.phase1.vSphere.placement="cluster"
.phase1.vSphere.cluster="PrimaryESXi"
.phase1.vSphere.useresourcepool="yes"
.phase1.vSphere.resourcepool="K8SLab"
.phase1.vSphere.vmfolderpath="K8SLab"
.phase1.vSphere.vcpu=2
.phase1.vSphere.memory=2048
.phase1.vSphere.network="K8SVLAN13"
.phase1.vSphere.template="KubernetesAnywhereTemplatePhotonOS.ova"
.phase1.vSphere.flannel_net="172.1.0.0/16"

#
# Phase 2: Node Bootstrapping
#
.phase2.kubernetes_version="v1.6.5"
.phase2.provider="ignition"
.phase2.installer_container="docker.io/cnastorage/k8s-ignition:v2"
.phase2.docker_registry="gcr.io/google-containers"

#
# Phase 3: Deploying Addons
#
.phase3.run_addons=y
.phase3.kube_proxy=y
.phase3.dashboard=y
.phase3.heapster=y
.phase3.kube_dns=y
# .phase3.weave_net is not set

**Comment by jhedman2** [comment]
Alright, so just ran the deploy process again and not sure why, but I'm
getting a different error, but it's progress at least.  I've validated that
the VM with the associated name exists in the appropriate resource pool in
vCenter and I've deployed this directly from the OVA that was downloaded.
The VM has NOT been powered on in anyway.  It's also in the same folder as
the .config file, and is already set to use the right datastore and VM
network.  But here's the current error (but it does seem to be successfully
authenticating to vCenter now).

Error applying plan:

5 error(s) occurred:

* vsphere_virtual_machine.kubevm2: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm2: vm 'KubernetesAnywhereTemplatePhotonOS'
not found
* vsphere_virtual_machine.kubevm1: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm1: vm 'KubernetesAnywhereTemplatePhotonOS'
not found
* vsphere_virtual_machine.kubevm4: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm4: vm 'KubernetesAnywhereTemplatePhotonOS'
not found
* vsphere_virtual_machine.kubevm3: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm3: vm 'KubernetesAnywhereTemplatePhotonOS'
not found
* vsphere_virtual_machine.kubevm5: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm5: vm 'KubernetesAnywhereTemplatePhotonOS'
not found

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by jhedman2** [comment]
What a learning experience, So I was able to get past that error, turns out that for some reason putting the template VM in a folder fails to deploy, but placing it in the root of the datacenter in vCenter works okay.  Even when using the absolute path to the VM.

However, I am now stuck at the following error.  Does this deployment require the use of vDS in vCenter or is this compatible with standard vSwitches (I know, why am I still using these, in short because my lab had a lot of reliability issues, and vDS became a problem every time I had to reconnect everything).

5 error(s) occurred:

* vsphere_virtual_machine.kubevm3: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm3: path '*K8SVLAN13' resolves to multiple networks
* vsphere_virtual_machine.kubevm2: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm2: path '*K8SVLAN13' resolves to multiple networks
* vsphere_virtual_machine.kubevm4: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm4: path '*K8SVLAN13' resolves to multiple networks
* vsphere_virtual_machine.kubevm1: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm1: path '*K8SVLAN13' resolves to multiple networks
* vsphere_virtual_machine.kubevm5: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm5: path '*K8SVLAN13' resolves to multiple networks

**Comment by jhedman2** [comment]
Also, is it normal for the script to put the asterisk in front of the Network name?  this is the vSwitch network label in vCenter.

**Comment by divyenpatel** [comment]
@jhedman2 good to know you figured out the issue regarding locating template OVA file. 

> "Does this deployment require the use of vDS in vCenter or is this compatible with standard vSwitches?"

Yes deployment is compatible with standard vSwitch.


> Also, is it normal for the script to put the asterisk in front of the Network name? this is the vSwitch network label in vCenter.

This is not normal, Can you try out specifying network path, if it is not in the root.
In my case I use 'VM Network' which is directly located under `/datacenter/network`

```
$ govc ls /datacenter/network
/datacenter/network/VM Network
```

may be in your case `K8SVLAN13` is not located directly under `network`. Can you specify path and see if it helps?

**Comment by jhedman2** [comment]
Thanks again for the response.  So interestingly enough, the network i was trying to use was in the root of the DC, and trying to give the full path, including /mydc/network/networklabel or /mydc/networklabel didn't work.  However, once I created a "Network Folder" in vCenter and put the network in that folder, the script began to work!  It's deploying the VM's as we speak!  Might be a good note to add in the directions

**Comment by divyenpatel** [comment]
@jhedman2 Can you disable IPV6 in the network and try again?

**Comment by jhedman2** [comment]
Good lord, that seemed to work, but then died at this point.  I wish there was a better way to test various vSphere components prior to the script kicking off.

Error applying plan:

5 error(s) occurred:

* vsphere_virtual_machine.kubevm4: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm4: A specified parameter was not correct: spec.deviceChange.device.port.switchUuid
* vsphere_virtual_machine.kubevm2: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm2: A specified parameter was not correct: spec.deviceChange.device.port.switchUuid
* vsphere_virtual_machine.kubevm5: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm5: A specified parameter was not correct: spec.deviceChange.device.port.switchUuid
* vsphere_virtual_machine.kubevm1: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm1: A specified parameter was not correct: spec.deviceChange.device.port.switchUuid
* vsphere_virtual_machine.kubevm3: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm3: A specified parameter was not correct: spec.deviceChange.device.port.switchUuid

**Comment by jhedman2** [comment]
I tried manually adding a nic to each of the vm's created. didn't seem to help.  Oddly enough, running the script again removed them all.  I'm at a loss, if there were a better way to troubleshoot this, and if I knew more about what was happening i'd love to troubleshoot it more myself.

thanks for your help again.  Feel like I'm getting close!

**Comment by jhedman2** [comment]
So I did some more digging, and I simply can't find that parameter in any file on my side.  I looked through all of the deployment configuration files after making a build, and couldn't find anything that looked strange.

All of the deploy files I could find that referenced the Switch label didn't look off either.  sort of at a stand still.

**Comment by jhedman2** [comment]
Sorry to be a nag, any thoughts on this?

**Comment by divyenpatel** [comment]
@jhedman2 
Could be an issue with Terraform. You can try out this new image.

```
docker run -it -v /tmp:/tmp --rm --env="PS1=[container]:\w> " --net=host divyen/kubernetes-anywhere:11302017 /bin/bash
```
