### ISSUE TITLE
Openstack provider reuse existing network and router

### ISSUE THREAD

**Issue by cmluciano** [kubernetes/kubernetes-anywhere#466]
Upon filling in the config options for my open stack network, I noted that the scripts created a new network instead of re-using my existing network. It would be great to have a switch to flip off creation of a new neutron router in favor of reusing an existing configuration.

cc @shashidharatd @dims

**Comment by cmluciano** [comment]
cc @jamiehannaford

**Comment by jamiehannaford** [comment]
So basically a new `network_name` option that, if set, wouldn't trigger a new network create?

**Comment by cmluciano** [comment]
I think that it is creating a new network regardless of whether it exists or not. 

My preference would be the opposite. If "do not create" is unset, reuse the existing switch and assign a public IP from an existing pool.

**Comment by ss22ever** [comment]
cc @ss22ever

**Comment by cmluciano** [comment]
@ss22ever I think we need to add an optional to the openstack.jsonnet that will only run the router tasks if a Kconfig flag is satisfied.
