### ISSUE TITLE
Can not deploy Kubernetes Cluster on vSphere with admin user password containing char '$'

### ISSUE THREAD

**Issue by ccit-spence** [kubernetes/kubernetes-anywhere#469]
Not sure the other information that needs to be provided.  This is the error:

`RUNTIME ERROR: Unrecognised conversion type: $`

**Comment by divyenpatel** [comment]
@ccit-spence  You can escape `$` in the password using `$$`.
I faced this issue before and it works with escaping `$` with `$`.
