### ISSUE TITLE
Calico CNI testing failing on k8s master

### ISSUE THREAD

**Issue by cmluciano** [kubernetes/kubernetes-anywhere#471]
Dashboard: https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#kubeadm-gce-cni-calico

**Comment by shashidharatd** [comment]
@cmluciano, i suspect this could be due to `POD_NETWORK_CIDR` being empty in case of calico cni plugin, here https://github.com/kubernetes/kubernetes-anywhere/blob/master/phase1/gce/configure-vm-kubeadm.sh#L76

**Comment by cmluciano** [comment]
Cool, I suspected the CIDR was the problem. I had to change some of the values in [this PR](https://github.com/kubernetes/kubernetes-anywhere/pull/475) for the setup to work correctly on Openstack. 

I don't see the same lines in the Openstack phase1. Should they be added?

**Comment by tmjd** [comment]
It sounds like this is not a Calico problem but a setup issue. If any help is needed understanding Calico's setup or requirements please ping me or @ozdanborne.
