### ISSUE TITLE
OpenStack fails using default phase2 config - Documentation too sparse

### ISSUE THREAD

**Issue by f0o** [kubernetes/kubernetes-anywhere#487]
Hi,

When attempting to deploy this on openstack it just errors with:
`RUNTIME ERROR: Unsupported phase2 provider in config`

if I change it from ignition to kubeadm it does continue but there's absolutely no documentation on what a valid option is or not, I had to dig the code to find this alternative.

Even with kubeadm it fails at a later stage (kubelet doesnt start).

Is there an actual working example with OpenStack?

//Edit: Also no DNS is being set for the network that terraform creates, so you always need to fiddle with the subnet before the first VM boots to add a DNS server.

**Comment by codebauss** [comment]
I have been able to get it working and agree the documentation and code for that matter can use some additional love. Re DNS, can you explain a bit more issue you are having? I am not having any issue with setup with correct configuration details.

**Comment by f0o** [comment]
What config options are you using and which OS?

So far I've only discovered that I need to specify kubeadm and minimum version of v1.7.0 but even then the kubelet on the master won't start..

I've tried centos and coreos until I saw that it relies on apt-get. Now I'm trying with Ubuntu 17.04

About the DNS, for me it creates a network without any DNS settings so the instances fail to lookup any domains as they don't get any DNS servers from the DHCP.

**Comment by codebauss** [comment]
I am using Ubuntu 16.04 with OpenStack Ocata
Here is what 'make config' generates for my .config:
#
# Automatically generated file; DO NOT EDIT.
# Kubernetes Minimal Turnup Configuration
#

#
# Phase 1: Cluster Resource Provisioning
#
.phase1.num_nodes=3
.phase1.cluster_name="k8s"
.phase1.ssh_user="ubuntu"
.phase1.cloud_provider="openstack"

#
# Openstack configuration
#
.phase1.openstack.os_image="xenial"
.phase1.openstack.flavor_name="m1.medium"
.phase1.openstack.ssh_key_file="/opt/kubernetes-anywhere/id_rsa"
.phase1.openstack.project_name="admin"
.phase1.openstack.domain_name="Default"
.phase1.openstack.auth_url="http://10.145.81.106:5000/v3"
.phase1.openstack.username="admin"
.phase1.openstack.password="Mc3ikupo"
.phase1.openstack.network_name="k8s-net"
.phase1.openstack.network_cidr="192.168.10.0/24"
.phase1.openstack.floatingip_pool_name="flat"
.phase1.openstack.external_gateway="7232f25c-9ff7-4039-8600-99c4efbade6f"

#
# Phase 2: Node Bootstrapping
#
.phase2.kubernetes_version="v1.8.3"
.phase2.docker_registry="gcr.io/google-containers"
.phase2.provider="kubeadm"
.phase2.kubeadm.version="stable"
.phase2.kubelet_version="stable"
.phase2.kubeadm.master_upgrade.method="upgrade"
.phase2.kube_context_name="k8s"
# .phase2.enable_cloud_provider is not set

#
# Phase 3: Deploying Addons
#
.phase3.run_addons=y
# .phase3.dashboard is not set
.phase3.heapster=y
# .phase3.weave_net is not set
.phase3.cni="weave"

**Comment by f0o** [comment]
Regarding DNS: Terraform creates a valid subnet with empty DNS settings, so the DHCP does not push any DNS Servers to the VMs, thus they cant resolve any names. I need to edit the subnet manually to add the DNS servers before the VMs bootup or else they fail instantly.

Regardless; I've gotten further now using Ubuntu 16.04 instead of 17.04 and I got the master up and running.

However the nodes' kubelet are failing with `unable to load client CA file /etc/kubernetes/pki/ca.crt`.

Any pointers?
