### ISSUE TITLE
Issue with "cnastorage/kubernetes-anywhere:lastest" on vsphere 5.5

### ISSUE THREAD

**Issue by panggou** [kubernetes/kubernetes-anywhere#512]
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
cnastorage/kubernetes-anywhere   latest              f6197e2e3666        4 months ago        713 MB
cnastorage/kubernetes-anywhere   vmc                 e42e2191e6a7        5 months ago        710.9 MB

cnastorage/kubernetes-anywhere:vmc --> works!

cnastorage/kubernetes-anywhere:latest --> doesnt work with the same .config!!!
make deploy reaches the last stage but the following loops indefinitely.
Validation: Expected 5 healthy nodes; found 1. (10s elapsed)
Validation: Expected 5 healthy nodes; found 1. (20s elapsed)
Validation: Expected 5 healthy nodes; found 1. (30s elapsed)
Validation: Expected 5 healthy nodes; found 1. (40s elapsed)
Validation: Expected 5 healthy nodes; found 1. (50s elapsed)
Validation: Expected 5 healthy nodes; found 1. (60s elapsed)
Validation: Expected 5 healthy nodes; found 1. (70s elapsed)
Validation: Expected 5 healthy nodes; found 1. (80s elapsed)
Validation: Expected 5 healthy nodes; found 1. (90s elapsed)
Validation: Expected 5 healthy nodes; found 1. (100s elapsed)
Validation: Expected 5 healthy nodes; found 1. (110s elapsed)
Validation: Expected 5 healthy nodes; found 1. (120s elapsed)
Validation: Expected 5 healthy nodes; found 1. (130s elapsed)
Validation: Expected 5 healthy nodes; found 1. (140s elapsed)

What is the difference between "cnastorage/kubernetes-anywhere:vmc" and "cnastorage/kubernetes-anywhere:latest"?  They are both v1.65.

Where do I get newer version of kubernetes-anywhere that deploys v1.7+?

Thanks in advance.

**Comment by panggou** [comment]
@divyenpatel 
I am using "divyen/kubernetes-anywhere:11302017", reach the last stage but the validation is stucked permanently...

/usr/local/bin/kubectl_v1.8.4         100%[=======================================================================>]  49.91M  23.0MB/s    in 2.2s

2018-01-25 03:19:06 (23.0 MB/s) - '/usr/local/bin/kubectl_v1.8.4' saved [52334123/52334123]

make[1]: Leaving directory '/opt/kubernetes-anywhere'
KUBECONFIG="$(pwd)/phase1/vsphere/clusters/K8S/kubeconfig.json" ./util/validate
Validation: Expected 4 (workers + master) nodes; found 0. (10s elapsed)
Validation: Expected 4 (workers + master) nodes; found 0. (20s elapsed)
Validation: Expected 4 (workers + master) nodes; found 0. (30s elapsed)
Validation: Expected 4 (workers + master) nodes; found 0. (40s elapsed)
Validation: Expected 4 (workers + master) nodes; found 0. (50s elapsed)
Validation: Expected 4 (workers + master) nodes; found 0. (60s elapsed)
Validation: Expected 4 (workers + master) nodes; found 0. (70s elapsed)
Validation: Expected 4 (workers + master) nodes; found 0. (80s elapsed)
Validation: Expected 4 (workers + master) nodes; found 0. (90s elapsed)
Validation: Expected 4 (workers + master) nodes; found 0. (100s elapsed)

Any ideas?

**Comment by panggou** [comment]
"make config" ended with the following:
Validation: Expected 4 (workers + master) nodes; found 0. (1200s elapsed)
Timeout exceeded.
Makefile:65: recipe for target 'validate-cluster-up' failed
make: *** [validate-cluster-up] Error 1

**Comment by divyenpatel** [comment]
@panggou Can you login to the master node and  execute `docker ps`. Do you see API-Server is up?

**Comment by panggou** [comment]
![image](https://user-images.githubusercontent.com/35447525/35374011-0e317826-01dc-11e8-9747-826155c366fc.png)

nothing under "docker ps" on master node.

**Comment by panggou** [comment]
from the master node I can:
1. ping all other nodes
2. ping the internet

**Comment by panggou** [comment]
Ok I  recreate the cluster same results but from master node "docker ps" looks different this time.

root@XXX-master [ ~ ]# docker ps
CONTAINER ID        IMAGE                                             COMMAND                  CREATED             STATUS              PORTS               NAMES
6d6ad5b7786d        gcr.io/google-containers/hyperkube-amd64:v1.8.4   "/hyperkube kubelet -"   5 minutes ago       Up 5 minutes                            prickly_shirley

No luck.
Any comments welcome.

Note: 
- I have the same issues with "nastorage/kubernetes-anywhere:latest" but "cnastorage/kubernetes-anywhere:**vmc**" works.

**Comment by panggou** [comment]
Any comments on this one?

**Comment by WuTangDangie** [comment]
Try this for the ignition image:

docker.io/cnastorage/k8s-ignition:v1.8-dev-release-with-kubelet-fix

**Comment by panggou** [comment]
docker.io/cnastorage/k8s-ignition:v1.8-dev-release-with-kubelet-fix works, I managed to deploy v1.9.3.

But I need something v1.7+
May I know what is the ignition to use for v1.7+?

**Comment by divyenpatel** [comment]
@panggou 

For 1.7 use this ignition image - `docker.io/divyen/k8s-ignition:nightly`

For 1.8 another one with etcd3 is - `docker.io/cnastorage/etcd3-ignition:latest`

**Comment by SailingYYC** [comment]
Good afternoon @divyenpatel,

We've tried nearly every combination conceivable. Can you confirm that `divyen/kubernetes-anywhere:11302017` using `docker.io/cnastorage/etcd3-ignition:k8smaster` as the ignition image will be able to stand up a Kubernetes v1.9.3 cluster on vSphere 6.5 with the [KubernetesAnywhereTemplatePhotonOS.ova](https://storage.googleapis.com/kubernetes-anywhere-for-vsphere-cna-storage/KubernetesAnywhereTemplatePhotonOS.ova)?

Most appreciated,
Colin

**Comment by WuTangDangie** [comment]
@SailingYYC 

I was having the same problem.  Take a look at issue #495 (ticker's comment towards the bottom).  Basically what worked for me was everything as written in the original kubernetes-anywhere on vSphere document, but with this ignition image:

docker.io/cnastorage/k8s-ignition:v1.8-dev-release-with-kubelet-fix

**Comment by divyenpatel** [comment]
@SailingYYC 

> Can you confirm that divyen/kubernetes-anywhere:11302017 using docker.io/cnastorage/etcd3-ignition:k8smaster as the ignition image will be able to stand up a Kubernetes v1.9.3 cluster on vSphere 6.5 with the KubernetesAnywhereTemplatePhotonOS.ova?

Yes that should work. I use `cnastorage/kubernetes-anywhere:latest` for deploying 1.9 cluster.

Thanks @WuTangDangie for pointing to https://github.com/kubernetes/kubernetes-anywhere/issues/495#issuecomment-370033863

**Comment by SailingYYC** [comment]
@divyenpatel and @WuTangDangie thank you for the info.

I was able to stand up the cluster with:
- `cnastorage/kubernetes-anywhere:latest`
- `docker.io/cnastorage/k8s-ignition:v1.8-dev-release-with-kubelet-fix`
**Note:** I have yet to validate the storage-provisioner.

I can also confirm that `docker.io/cnastorage/etcd3-ignition:k8smaster` failed to stand up a cluster using `cnastorage/kubernetes-anywhere:latest`, `divyen/kubernetes-anywhere:11302017`, and a freshly built container of `kubernetes/kubernetes-anywhere`.

I'm going to attempt to rebuild the cluster with the latest `kubernetes-anywhere` and `docker.io/cnastorage/k8s-ignition:v1.8-dev-release-with-kubelet-fix`.

@divyenpatel Is there anything magical about `cnastorage/kubernetes-anywhere:latest`?

**Comment by SailingYYC** [comment]
As a side note, I had hoped to use `docker.io/cnastorage/k8s-ignition:v1.8-dev-release-with-kubelet-fix` with a newer version of Kubernetes-Anywhere, both the divyen and kubernetes-anywhere master branch, and can confirm both fail.

Also using the `.config`, ignition image, and `cnastorage/kubernetes-anywhere:latest` I was successful with the first time failed to varying degrees on 5 successive attempts. It took removing all traces from vSphere, including the OVA and restarting to get an operational cluster again.

**Comment by tickers** [comment]
there's some updated info [#495](https://github.com/kubernetes/kubernetes-anywhere/issues/495#issuecomment-378424671)
