### ISSUE TITLE
socat install 

### ISSUE THREAD

**Issue by tickers** [kubernetes/kubernetes-anywhere#525]
Trying to install Helm and the main error according to Helm is that socat is not installed and so far I have not found a tdnf that would work and the source install requires a compiler, installed GCC, still fails to build so I am stuck and would appreciate any insight. 

If I find a way I will post my steps. 

Running Kubernetes 1.9.3 on VMWare 6.5.

**Comment by beanallergy** [comment]
What works for me is to install it on the PhotonOS template, following the steps from here https://github.com/kubernetes/kubernetes-anywhere/issues/495#issuecomment-378424671
