### ISSUE TITLE
Fail to deploy k8s cluster 1.8 on vSphere

### ISSUE THREAD

**Issue by haooliveira84** [kubernetes/kubernetes-anywhere#547]
#
# Phase 2: Node Bootstrapping
#
.phase2.kubernetes_version="v1.8.15"
.phase2.docker_registry="gcr.io/google-containers"
.phase2.provider="ignition"
.phase2.proxy_mode="iptables"
.phase2.installer_container="docker.io/cnastorage/etcd3-ignition:latest"

Log docker log on ignite 
`root@LNX-DEV-K8S-master [ ~ ]# docker logs a798461cd92b                                                                                                                 + export IGNITION_CONFIG_FILE=/usr/share/oem/ignite.json                                                                                                                + mkdir -p /usr/share/oem                                                                                                                                               + jsonnet --output-file /usr/share/oem/ignite.json --tla-code-file cfg=/etc/kubernetes/k8s_config.json --jpath /opt/kubernetes-anywhere /opt/kubernetes-anywhere/ignite.jsonnet                                                                                                                                                                 + ignition -oem file -stage files --root /mnt/root                                                                                                                      **ERROR    : unable to open syslog: Unix syslog delivery error**                                                                                                            INFO     : Ignition v0.12.1-1-g6ff90ec-dirty                                                                                                                            DEBUG    : parsed url from cmdline: ""                                                                                                                                  INFO     : no config URL provided                                                                                                                                       INFO     : using config file at "/usr/share/oem/ignite.json"    `

**Comment by haooliveira84** [comment]
@rbjorklin Thanks, but I have just tested with `v1.8-dev-release-with-kubelet-fix` image and I don't have success
My vspere is 6.0
`# Phase 1: Cluster Resource Provisioning
#
.phase1.num_nodes=4
.phase1.cluster_name="LNX-K8S"
.phase1.ssh_user=""
.phase1.cloud_provider="vsphere"

#
# vSphere configuration
#
.phase1.vSphere.url="vcenter.vshepre.local"
.phase1.vSphere.port=443
.phase1.vSphere.username="administrator@vshepre.local"
.phase1.vSphere.password="pass"
.phase1.vSphere.insecure=y
.phase1.vSphere.datacenter="DC-vcenter"
.phase1.vSphere.datastore="VMDTA--SRC-01"
.phase1.vSphere.placement="cluster"
.phase1.vSphere.cluster=""
.phase1.vSphere.useresourcepool="no"
.phase1.vSphere.vmfolderpath="Kubernetes/DEV"
.phase1.vSphere.vcpu=8
.phase1.vSphere.memory=8192
.phase1.vSphere.network="VM Network"
.phase1.vSphere.template="Kubernetes/Templates/KubernetesAnywhereTemplatePhotonOS"
.phase1.vSphere.flannel_net="172.1.0.0/16"

#
# Phase 2: Node Bootstrapping
#
.phase2.kubernetes_version="v1.9.1"
.phase2.docker_registry="gcr.io/google-containers"
.phase2.provider="ignition"
.phase2.installer_container="docker.io/cnastorage/k8s-ignition:v1.8-dev-release""

#
# Phase 3: Deploying Addons
#
.phase3.run_addons=y
.phase3.kube_proxy=y
.phase3.kube_dns=y
.phase3.dashboard=y
.phase3.heapster=y`

**Comment by maldex** [comment]
i know i had kubernetes-anywhere installing just fine around a year ago and unfortunately didn't document enough, but i'm going nuts here. Been spending hours and i did not get any combination running. Neither with the 'docker-dev' container nor with any other mentioned prebuild kubernetes-anywhere-container. Also none of the combinations of kubernetes_version nor installer_container seems to work for me this time.

I'm running ESXi 6.5u2 and 6.7 with vCenter 6.7.

all i ever get from the master-node logs is kublet complainig about `Failed to list *v1.Node: Get https://192.168.18.165/api/v1/nodes?fieldSelector=metadata.name%3Dmaster&limit=500&resourceVersion=0: dial tcp 192.168.18.165:443: getsockopt: connection refused`

any idea?

**Comment by haooliveira84** [comment]
Solved: use kubespray
