### ISSUE TITLE
Deployment instructions are unclear

### ISSUE THREAD

**Issue by paulbellamy** [kubernetes/kubernetes-anywhere#55]
I _guess_ I run the toolbox, then run some commands inside it?

Could there be a `weaveworks/kubernetes-anywhere:deploy` image that just does all this?
Or just a `weaveworks/kubernetes-anywhere:toolbox deploy` tool, or something?

**Comment by errordeveloper** [comment]
I've discussed this with @peterbourgon and @rade earlier, and the conclusion was to avoid too much wrapping.

How about this:
```
docker run … toolbox sh -c 'setup-kubelet-volumes && compose -p kube up -d'
```
