### ISSUE TITLE
Cluster unavailable after sitting idle over night

### ISSUE THREAD

**Issue by armontero** [kubernetes/kubernetes-anywhere#550]
Hello!

I recently just installed a new cluster running 1.11.1 following the suggestions from another issue thread.  Some folks on that thread mentioned they had this problem as well, but I figured it might make sense to start a new thread since this is technically a different issue.  

Basically, the cluster behaves fine so long as it is being actively used.  However, when I try to get pods first thing in the morning, the response is:

`The connection to the server 192.168.1.168 was refused - did you specify the right host or port?`

If I go to vmware and restart all of the cluster vm's, everything will work fine all day.  Anybody have any thoughts?

**Comment by neolit123** [comment]
seems like the API server is not listening.
what output do you get from:
```
journalctl -xeu kubelet
```

**Comment by armontero** [comment]
I will run this the next time I encounter the problem and post the results.

**Comment by neolit123** [comment]
> I will run this the next time I encounter the problem and post the results.

please reopen the issue if needed. thanks.
/close

**Comment by armontero** [comment]
This morning I tried connecting to the cluster again and it has stopped responding.  The journalctl command you gave returns no output:

`amontero@apollo:~/code$ journalctl -xeu kubelet
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
-- Logs begin at Sat 2018-07-21 18:29:04 PDT, end at Tue 2018-07-31 09:07:52 PDT. --
-- No entries --
amontero@apollo:~/code$ 
`

What else should I try while I am experiencing the issue?
