### ISSUE TITLE
Cluster unavailable after being left alone over night

### ISSUE THREAD

**Issue by armontero** [kubernetes/kubernetes-anywhere#551]
Hello!

I'm recreating this issue as it is still occurring.  This morning when I try to get pods, I'm getting the same message:
`amontero@apollo:~/code$ kubectl get pods
The connection to the server 192.168.1.168 was refused - did you specify the right host or port?
amontero@apollo:~/code$`

Journalctl is not giving any helpful information either:
`amontero@apollo:~/code$ journalctl -xeu kubelet
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
-- Logs begin at Sat 2018-07-21 18:29:04 PDT, end at Tue 2018-07-31 09:29:38 PDT. --
-- No entries --
amontero@apollo:~/code$`

Any thoughts on next steps to debug?  Thanks!

**Comment by armontero** [comment]
Ok - I wasn't running that command in the right place.  Here's the output:

[journalctl-xeu-kubelet.txt](https://github.com/kubernetes/kubernetes-anywhere/files/2247407/journalctl-xeu-kubelet.txt)

**Comment by armontero** [comment]
Ok, after looking at the journalctl output, there are many entries similar to this:

`Jul 31 23:18:01 kubernetes-master docker[373]: I0731 23:18:01.264629     405 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/vnd.kubernetes.protobuf, */*" -H "User-Agent: hyperkube/v1.11.1 (linux/amd64) kubernetes/b1b2997" 'https://192.168.1.168/api/v1/nodes?fieldSelector=metadata.name%3Dkubernetes-master&limit=500&resourceVersion=0'
Jul 31 23:18:01 kubernetes-master docker[373]: I0731 23:18:01.265566     405 round_trippers.go:405] GET https://192.168.1.168/api/v1/nodes?fieldSelector=metadata.name%3Dkubernetes-master&limit=500&resourceVersion=0  in 0 milliseconds
Jul 31 23:18:01 kubernetes-master docker[373]: I0731 23:18:01.266227     405 round_trippers.go:411] Response Headers:
Jul 31 23:18:01 kubernetes-master docker[373]: E0731 23:18:01.266937     405 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Get https://192.168.1.168/api/v1/nodes?fieldSelector=metadata.name%3Dkubernetes-master&limit=500&resourceVersion=0: dial tcp 192.168.1.168:443: connect: connection refused`

Assuming that this could have something to do with the network, I restarted flanneld and it came right back online.

Does anyone have an idea why this is happening?  Any suggestions on how to resolve?  Thanks!

**Comment by armontero** [comment]
I left the cluster alone for a minute and lost connection again.  I got frustrated and rebooted all the vm's again.  It's back and working.

This is a super annoying bug.  I didn't use the kubelet fix ignition image when I built this cluster.  Could that be what is causing this?  I'm getting close to trashing this cluster and building one with the other ignition image.  If anyone has any ideas, I'd appreciate it.  Thanks!

**Comment by neolit123** [comment]
i'd suggest you try getting some feedback on the vmware related issues in the #sig-vmware channel on the k8s slack. folks might have a better idea about know issues.

in terms of `kubernetes/kubernetes-anywhere` the project is not actively maintained and SIG Cluster Lifecycle has plans to deprecate it, or at least deprecate it's usage in certain areas.
