### ISSUE TITLE
Make Deploy Runtime Error

### ISSUE THREAD

**Issue by jescuderotraining** [kubernetes/kubernetes-anywhere#553]
I get the following error when trying to deploy cluster

[container]:/opt/kubernetes-anywhere> make deploy
util/config_to_json /opt/kubernetes-anywhere/.config > /opt/kubernetes-anywhere/.config.json
make do WHAT=deploy-cluster
make[1]: Entering directory '/opt/kubernetes-anywhere'
( cd "phase1/vsphere"; ./do deploy-cluster )
RUNTIME ERROR: Format required number at 0, got string
        std.jsonnet:(477:21)-(478:56)   function <format_code>
        std.jsonnet:557:29-73   thunk <s>
        std.jsonnet:562:38      thunk <str>
        std.jsonnet:369:36-38
        std.jsonnet:369:25-39   thunk <w>
        std.jsonnet:365:17      thunk <w>
        std.jsonnet:361:20      function <aux>
        std.jsonnet:365:13-22   function <padding>
        std.jsonnet:369:13-43   function <pad_left>
        std.jsonnet:562:29-52   thunk <s_padded>
        ...
        vSphere.jsonnet:138:21-133      thunk <array_element>
        vSphere.jsonnet:(136:27)-(141:19)       object <anonymous>
        vSphere.jsonnet:(135:32)-(142:17)       object <anonymous>
        vSphere.jsonnet:(134:27)-(143:12)       thunk <array_element>
        vSphere.jsonnet:(134:26)-(147:13)       object <anonymous>
        vSphere.jsonnet:(127:39)-(148:9)        object <anonymous>
        std.jsonnet:(943:13)-(952:13)   object <anonymous>
        std.jsonnet:(943:13)-(952:13)   object <anonymous>
        all.jsonnet:3:49-79     object <anonymous>
        During manifestation
Makefile:70: recipe for target 'do' failed
make[1]: *** [do] Error 1
make[1]: Leaving directory '/opt/kubernetes-anywhere'
Makefile:48: recipe for target 'deploy-cluster' failed
make: *** [deploy-cluster] Error 2

Here is my .config file
#
# Automatically generated file; DO NOT EDIT.
# Kubernetes Minimal Turnup Configuration
#

#
# Phase 1: Cluster Resource Provisioning
#
.phase1.num_nodes=4
.phase1.cluster_name="kubernetes"
.phase1.ssh_user=""
.phase1.cloud_provider="vsphere"

#
# vSphere configuration
#
.phase1.vSphere.url="my-vcsa.com"
.phase1.vSphere.port=443
.phase1.vSphere.username="domain\service_account"
.phase1.vSphere.password="password"
.phase1.vSphere.insecure=y
.phase1.vSphere.datacenter="Data-Center"
.phase1.vSphere.datastore="Studio_DS/1500MTU/esx_ucs_ssd_ds2"
.phase1.vSphere.placement="cluster"
.phase1.vSphere.cluster="UCS-Studio"
.phase1.vSphere.useresourcepool="no"
.phase1.vSphere.vmfolderpath="kubernetes"
.phase1.vSphere.vcpu=4
.phase1.vSphere.memory=8192
.phase1.vSphere.network="My_dvSwitch/VLAN-235%2f236-VDI"
.phase1.vSphere.template="Templates/Linux/Photon/KubernetesAnywhereTemplatePhotonOS.ova"
.phase1.vSphere.flannel_net="172.1.0.0/16"

#
# Phase 2: Node Bootstrapping
#
.phase2.kubernetes_version="v1.6.5"
.phase2.provider="ignition"
.phase2.installer_container="docker.io/cnastorage/k8s-ignition:v2"
.phase2.docker_registry="gcr.io/google-containers"

#
# Phase 3: Deploying Addons
#
.phase3.run_addons=y
.phase3.kube_proxy=y
.phase3.dashboard=y
.phase3.heapster=y
.phase3.kube_dns=y
# .phase3.weave_net is not set

**Comment by armontero** [comment]
Can you post your config?  It looks like it's complaining about expecting a numerical value and getting a string.

/opt/kubernetes-anywhere/.config.json

**Comment by jescuderotraining** [comment]
This is what my config looks like

**Comment by armontero** [comment]
Can you post the terminal output when the script stops?  Other areas to look at:

1. datastore:  Your datastore name is a full path - on my installation it was just datastore1.  Just make sure that this is an accurate datastore name and not a folder within the datastore.
2. network: Same thing here, I think my network was VMnetwork.  As long as this is a valid network name within your vsphere environment, it should be ok.
3.  template: When I import the OVA into my vsphere, it drops the ".ova" part of the name.  It will fail if this name is not accurate for how the template is named in your vsphere instance.

Hopefully one of these is what is tripping up the install.

**Comment by jescuderotraining** [comment]
ca_cert_pem:           "" => "7ec23eae74f45fcc88fdd781aa0bf6e2c43d81bb"
  ca_key_algorithm:      "" => "RSA"
  ca_private_key_pem:    "" => "1b72f9fe40a0c3632b5448dcf666a9cba539b4dc"
  cert_pem:              "" => "<computed>"
  cert_request_pem:      "" => "1bacb8a2fac5460f8261757a44e8ad58715dd046"
  early_renewal_hours:   "" => "0"
  validity_end_time:     "" => "<computed>"
  validity_period_hours: "" => "8760"
  validity_start_time:   "" => "<computed>"
tls_locally_signed_cert.kubernetes-admin: Creation complete (ID: 20127330562482735934435046188435546328)
Error applying plan:

5 error(s) occurred:

* vsphere_virtual_machine.kubevm3: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm3: network '*Tiburon_dvSwitch/VLAN-235/236-VDI' not found
* vsphere_virtual_machine.kubevm2: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm2: network '*Tiburon_dvSwitch/VLAN-235/236-VDI' not found
* vsphere_virtual_machine.kubevm5: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm5: network '*Tiburon_dvSwitch/VLAN-235/236-VDI' not found
* vsphere_virtual_machine.kubevm4: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm4: network '*Tiburon_dvSwitch/VLAN-235/236-VDI' not found
* vsphere_virtual_machine.kubevm1: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm1: network '*Tiburon_dvSwitch/VLAN-235/236-VDI' not found

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
Makefile:70: recipe for target 'do' failed
make[1]: *** [do] Error 1
make[1]: Leaving directory '/opt/kubernetes-anywhere'
Makefile:48: recipe for target 'deploy-cluster' failed
make: *** [deploy-cluster] Error 2
[container]:/opt/kubernetes-anywhere> vi .config 
[container]:/opt/kubernetes-anywhere> make clean 
( if [[ ! -z "vsphere" && ! -z "kubernetes" ]];then rm -rf phase3/vsphere/.tmp/ phase1/vsphere/kubernetes/; fi )
[container]:/opt/kubernetes-anywhere> make deploy
util/config_to_json /opt/kubernetes-anywhere/.config > /opt/kubernetes-anywhere/.config.json
make do WHAT=deploy-cluster
make[1]: Entering directory '/opt/kubernetes-anywhere'
( cd "phase1/vsphere"; ./do deploy-cluster )
RUNTIME ERROR: Format required number at 0, got string
        std.jsonnet:(477:21)-(478:56)   function <format_code>
        std.jsonnet:557:29-73   thunk <s>
        std.jsonnet:562:38      thunk <str>
        std.jsonnet:369:36-38
        std.jsonnet:369:25-39   thunk <w>
        std.jsonnet:365:17      thunk <w>
        std.jsonnet:361:20      function <aux>
        std.jsonnet:365:13-22   function <padding>
        std.jsonnet:369:13-43   function <pad_left>
        std.jsonnet:562:29-52   thunk <s_padded>
        ...
        vSphere.jsonnet:138:21-133      thunk <array_element>
        vSphere.jsonnet:(136:27)-(141:19)       object <anonymous>
        vSphere.jsonnet:(135:32)-(142:17)       object <anonymous>
        vSphere.jsonnet:(134:27)-(143:12)       thunk <array_element>
        vSphere.jsonnet:(134:26)-(147:13)       object <anonymous>
        vSphere.jsonnet:(127:39)-(148:9)        object <anonymous>
        std.jsonnet:(943:13)-(952:13)   object <anonymous>
        std.jsonnet:(943:13)-(952:13)   object <anonymous>
        all.jsonnet:3:49-79     object <anonymous>
        During manifestation
Makefile:70: recipe for target 'do' failed
make[1]: *** [do] Error 1
make[1]: Leaving directory '/opt/kubernetes-anywhere'
Makefile:48: recipe for target 'deploy-cluster' failed
make: *** [deploy-cluster] Error 2

**Comment by jescuderotraining** [comment]
What i did to trouble shoot in the beginning was add the variables 1 at a time until  i got to the network part and thats where it fails.

**Comment by armontero** [comment]
Yep - your problem is definitely with that network name.  If you go into vSphere, click the networking icon (top of the left navigation menu, there are four icons - hosts, vms, storage, and network)

When you view that tree, do you see the network you are trying to deploy to (Tiburon_dvSwitch/VLAN-235/236-VDI)?  Also, you just need the network name, not the path down to the network you are trying to use.  For example, for me:
rigel.domainlogic.net (vsphere host)
 ----> Domain Logic Data Center (data center)
         ----> VM Network (network)
In my config, I only put "VM Network".

**Comment by armontero** [comment]
Is the asterisk in front of the VLAN name intentional?  Can you try simplifying the name of that network just for debugging purposes?  It's pretty easy to 'make destroy' and redo everything if you are able to clear this network name as a problem.

**Comment by jescuderotraining** [comment]
it puts that * in the output for some odd reason.
 I will need to create a new dvswitch and vlan for dev.  thats productions unfortunatel

**Comment by jescuderotraining** [comment]
if i use VLAN-235%2f236-VDI then it fails.

[container]:/opt/kubernetes-anywhere> make deploy
util/config_to_json /opt/kubernetes-anywhere/.config > /opt/kubernetes-anywhere/.config.json
make do WHAT=deploy-cluster
make[1]: Entering directory '/opt/kubernetes-anywhere'
( cd "phase1/vsphere"; ./do deploy-cluster )
RUNTIME ERROR: Format required number at 0, got string
        std.jsonnet:(477:21)-(478:56)   function <format_code>
        std.jsonnet:557:29-73   thunk <s>
        std.jsonnet:562:38      thunk <str>
        std.jsonnet:369:36-38
        std.jsonnet:369:25-39   thunk <w>
        std.jsonnet:365:17      thunk <w>
        std.jsonnet:361:20      function <aux>
        std.jsonnet:365:13-22   function <padding>
        std.jsonnet:369:13-43   function <pad_left>
        std.jsonnet:562:29-52   thunk <s_padded>
        ...
        vSphere.jsonnet:138:21-133      thunk <array_element>
        vSphere.jsonnet:(136:27)-(141:19)       object <anonymous>
        vSphere.jsonnet:(135:32)-(142:17)       object <anonymous>
        vSphere.jsonnet:(134:27)-(143:12)       thunk <array_element>
        vSphere.jsonnet:(134:26)-(147:13)       object <anonymous>
        vSphere.jsonnet:(127:39)-(148:9)        object <anonymous>
        std.jsonnet:(943:13)-(952:13)   object <anonymous>
        std.jsonnet:(943:13)-(952:13)   object <anonymous>
        all.jsonnet:3:49-79     object <anonymous>
        During manifestation
Makefile:70: recipe for target 'do' failed
make[1]: *** [do] Error 1
make[1]: Leaving directory '/opt/kubernetes-anywhere'
Makefile:48: recipe for target 'deploy-cluster' failed
make: *** [deploy-cluster] Error 2

**Comment by jescuderotraining** [comment]
in my terraform .tfvars file i have to use My_dvSwitch/VLAN-235%2f236-VDI if not if fails which is why i have paths on most of them

**Comment by armontero** [comment]
Yeah, you're dealing with a more complex vSphere environment than I am it sounds like.  I've been hit by resource names in the past, so I usually try and keep them simple and avoid characters that could potentially need to be escaped or replaced.  Hopefully all goes well when you get a network built up for testing.

The code works if you can get past this - I've been using this for a while and it's awesome.  I've built several clusters over the last few months, but it does take some work once you start trying to deploy past v1.6.5.  I'm running v1.11.1, but it is a little buggy.  I think it's time to update the template to Photon 2.0 and take a look at the ignition images to make sure they work with the current k8s versions.  

In any case, this is definitely the best project I've found for standing up k8s on vsphere - I hope they keep it going!

**Comment by jescuderotraining** [comment]
got it to work.  i used another dvswitch i had for testing.  I received the following error when i used
dvSwitch_test/dvPortGroup

tls_private_key.kubernetes-master: Creation complete (ID: 4cf9bdd7d30e329f17f2017b471d40cd38c3e381)
Error applying plan:

5 error(s) occurred:

* vsphere_virtual_machine.kubevm5: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm5: cannot traverse type VmwareDistributedVirtualSwitch
* vsphere_virtual_machine.kubevm3: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm3: cannot traverse type VmwareDistributedVirtualSwitch
* vsphere_virtual_machine.kubevm2: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm2: cannot traverse type VmwareDistributedVirtualSwitch
* vsphere_virtual_machine.kubevm1: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm1: cannot traverse type VmwareDistributedVirtualSwitch
* vsphere_virtual_machine.kubevm4: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm4: cannot traverse type VmwareDistributedVirtualSwitch


If I just use dvPortGroup the vms will deploy.  I guess i need to find a fix for the current prod environment for future instances. 

Thx for your help
