### ISSUE TITLE
indicate the status of this repo

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes-anywhere#556]
I believe this project is no longer in active development, yet it still serves certain purpose. We should indicate whatever is the case in the readme and repo description, so that it's clear to a newcomer what this is.

cc @roberthbailey @timothysc

**Comment by roberthbailey** [comment]
AFAIK the main purpose of this project is to enable end to end testing of kubeadm (since kubeadm itself doesn't provision infrastructure). Other than that, it isn't being actively maintained and once kubeadm has a different solution for e2e tests we plan to archive it.

**Comment by neolit123** [comment]
the easiest way would be to change the repo description in the lines of:
```
(NOTE: This project is deprecated and used only for kubeadm e2e tests) {concise,reliable,cross-platform} turnup of Kubernetes clusters
```

**Comment by thockin** [comment]
Is there any plan for something different?

**Comment by roberthbailey** [comment]
https://github.com/kubernetes-sigs/cluster-api

**Comment by luxas** [comment]
Does this describe the current state well enough https://github.com/kubernetes/kubernetes-anywhere/pull/577?

**Comment by nikhita** [comment]
Closing the issue since the repo is being archived: https://github.com/kubernetes/org/issues/1812
