### ISSUE TITLE
Terraform instructions are unclear

### ISSUE THREAD

**Issue by paulbellamy** [kubernetes/kubernetes-anywhere#59]
- It's unclear how to access the nodes

`Once instances are up, you can login to any of the 3 worker nodes or the master ...`
Terraform should output the IP of the nodes, so I know where to ssh to after. And what the ssh key is, username?
- I got confused on where to start from, so I started from the aws-ec2 example directory. Apparently I shouldn't have.
- The copy-paste terraform file depends on (and refers to) variables which don't exist.
- Why are `cluster` and `cluster_config_flavour` hardcoded, while everything else you set is a variable?
- What to do (how to run `kubernetes-anywhere-toolbox`) after logging into a box is unclear. Do I `docker run kubernetes-anywhere-toolbox`? but there's no docker?
- `ssh -A` is required for kubernetes-anywhere-toolbox

**Comment by full-of-foo** [comment]
Any developments on this? I too was expecting at least expecting Docker to be provisioned on the nodes
