### ISSUE TITLE
External script targeting Docker for Mac and local Docker in general

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes-anywhere#72]
At the end of the day there is still a bit of a fuff around `docker run` args required for spinning cluster up and down, it'd be more convenient if user could install a simple script that would be as simple as `kubernetes-anywhere [up|down|*]` and handle full vs quick resets as well as upgrades. Updating `~/.kube/config` would be another responsibility of this script.

**Comment by spiddy** [comment]
Working on separate repo until there is an _official_ location for it: https://github.com/harbur/k8s-anywhere.

* Added creation of namespace & DNS.
* Separated up/down (tear down everything) start/stop (keep persistence)

**Comment by errordeveloper** [comment]
@spiddy that's funny, we've been using SOCKS too 👍

**Comment by errordeveloper** [comment]
Also, please see recent changes, I've made API server much easier to access now. May be we should hook-up chat on Slack or IRC next week, what do you think?
