### ISSUE TITLE
build toolbox from alpine

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes-anywhere#85]
It's over 400M right now, can be much smaller.

**Comment by errordeveloper** [comment]
The main problem seems to be with Docker Compose binary, it doesn't work as is.

**Comment by errordeveloper** [comment]
Installing it as a Python package works fine.

**Comment by errordeveloper** [comment]
Ok, after more extensive testing, we have bumped into:
```
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: remove /.pivot_root459018830: device or resource busy"
```
...and it only happens on Docker Machine.

**Comment by mikedanese** [comment]
Done
